/* @generated by scripts/gen-engine-ops.py from core/engine-ops.jsonc.
 * DO NOT EDIT. Append a field to the list and re-run the script.
 * Field ORDER is the ABI. Included from s2script_core.h. */

typedef void (*s2_emit_class_fn)(void* ctx, const char* name, const char* parent);

typedef void (*s2_emit_field_fn)(void* ctx, const char* cls, const char* name, int offset, const char* kind, const char* type_name, const char* inner, int size);

typedef void (*s2_emit_enum_fn)(void* ctx, const char* enum_name, int size, const char* enumerator, long long value);

typedef struct {
    int didHit;
    float fraction;
    float endpos[3];
    float normal[3];
    int allSolid;
    int hitEntHandle;
} S2TraceResult;

typedef int (*s2_schema_offset_fn)(const char* cls, const char* field);
typedef void* (*s2_ent_by_index_fn)(int idx);
typedef void* (*s2_deref_handle_fn)(unsigned int handle);
typedef void (*s2_ent_state_changed_fn)(void* ent, int offset);
typedef void (*s2_concommand_register_fn)(const char* name);
typedef int (*s2_schema_enumerate_fn)(void* ctx, s2_emit_class_fn emit_class, s2_emit_field_fn emit_field, s2_emit_enum_fn emit_enum);
typedef int (*s2_event_subscribe_fn)(const char* name);
typedef int (*s2_event_unsubscribe_fn)(const char* name);
typedef int (*s2_event_get_int_fn)(const char* key);
typedef float (*s2_event_get_float_fn)(const char* key);
typedef int (*s2_event_get_bool_fn)(const char* key);
typedef const char* (*s2_event_get_string_fn)(const char* key);
typedef uint64_t (*s2_event_get_uint64_fn)(const char* key);
typedef int (*s2_event_get_player_slot_fn)(const char* key);
typedef int (*s2_client_valid_fn)(int slot);
typedef int (*s2_client_userid_fn)(int slot);
typedef int (*s2_client_signon_fn)(int slot);
typedef const char* (*s2_client_name_fn)(int slot);
typedef int (*s2_client_find_by_userid_fn)(int userid);
typedef void (*s2_event_set_int_fn)(const char* key, int value);
typedef void (*s2_event_set_float_fn)(const char* key, float value);
typedef void (*s2_event_set_bool_fn)(const char* key, int value);
typedef void (*s2_event_set_string_fn)(const char* key, const char* value);
typedef void (*s2_event_set_uint64_fn)(const char* key, uint64_t value);
typedef int (*s2_event_create_fn)(const char* name);
typedef int (*s2_event_fire_fn)(int dontBroadcast);
typedef const char* (*s2_config_read_fn)(const char* id);
typedef int (*s2_config_write_fn)(const char* id, const char* content);
typedef void (*s2_client_print_fn)(int slot, const char* msg);
typedef const char* (*s2_client_steamid_fn)(int slot);
typedef void (*s2_client_kick_fn)(int slot, const char* reason);
typedef void (*s2_server_command_fn)(const char* cmd);
typedef int (*s2_server_map_valid_fn)(const char* map);
typedef float (*s2_damage_read_float_fn)(int offset);
typedef int (*s2_damage_read_int_fn)(int offset);
typedef void (*s2_damage_write_float_fn)(int offset, float value);
typedef int (*s2_damage_victim_fn)(void);
typedef const char* (*s2_cvar_get_fn)(const char* name);
typedef void (*s2_client_console_print_fn)(int slot, const char* msg);
typedef const char* (*s2_client_address_fn)(int slot);
typedef int (*s2_server_max_clients_fn)(void);
typedef const char* (*s2_server_map_name_fn)(void);
typedef float (*s2_server_game_time_fn)(void);
typedef const char* (*s2_db_data_dir_fn)(void);
typedef int (*s2_event_fire_to_client_fn)(int slot);
typedef const char* (*s2_config_read_file_fn)(const char* name);
typedef int (*s2_config_write_file_fn)(const char* name, const char* content);
typedef int (*s2_trace_shape_fn)(const float* start, const float* end, const float* mins, const float* maxs, unsigned long long interactsWith, unsigned long long interactsExclude, int ignoreEntIdx, int ignoreEntSerial, S2TraceResult* out);
typedef int (*s2_entity_create_fn)(const char* className);
typedef int (*s2_entity_spawn_fn)(int index, int serial);
typedef int (*s2_entity_teleport_fn)(int index, int serial, const float* origin, const float* angles, const float* velocity);
typedef int (*s2_entity_remove_fn)(int index, int serial);
typedef int (*s2_entity_subobj_vcall_fn)(int index, int serial, int subObjOffset, int vtableIndex, int argIndex, int argSerial);
typedef int (*s2_entity_read_handle_vector_fn)(int index, int serial, const int* ptrOffs, int ptrCount, int vectorOff, int maxCount, int* outHandles);
typedef int (*s2_entity_fire_input_fn)(int index, int serial, const char* input, const char* value, int actIdx, int actSerial, int callerIdx, int callerSerial, float delay);
typedef int (*s2_entity_spawn_kv_fn)(int index, int serial, int count, const char* const* keys, const int* types, const char* const* values);
typedef int (*s2_entity_find_by_class_fn)(const char* className, int* outIndices, int* outSerials, int maxCount);
typedef int (*s2_user_message_create_fn)(const char* name);
typedef int (*s2_user_message_set_int_fn)(const char* field, int64_t value);
typedef int (*s2_user_message_set_float_fn)(const char* field, double value);
typedef int (*s2_user_message_set_string_fn)(const char* field, const char* value);
typedef int (*s2_user_message_set_bool_fn)(const char* field, int value);
typedef int (*s2_user_message_send_fn)(const int* slots, int slotCount);
typedef int (*s2_convar_register_fn)(const char* name, const char* help, uint64_t flags, int type, const char* defaultValue, const char* minValue, const char* maxValue);
typedef const char* (*s2_translations_read_fn)(const char* lang, const char* name);
typedef const char* (*s2_client_language_fn)(int slot);
typedef int (*s2_collision_activate_fn)(int index, int serial);
typedef int (*s2_entity_set_model_fn)(int index, int serial, const char* modelName);
typedef int (*s2_entity_listener_install_fn)(void);
typedef const char* (*s2_entity_name_fn)(int index, int serial);
typedef int (*s2_sound_emit_fn)(const char* soundName, int entIndex, int entSerial, const int* slots, int slotCount, float volume);
typedef int (*s2_sound_precache_add_fn)(const char* path);
typedef int (*s2_usercmd_hook_install_fn)(void);
typedef double (*s2_usercmd_read_fn)(int field);
typedef void (*s2_usercmd_write_fn)(int field, double value);
typedef uint64_t (*s2_usercmd_read_buttons_fn)(void);
typedef void (*s2_usercmd_write_buttons_fn)(uint64_t mask);
typedef void (*s2_usercmd_clear_subtick_fn)(void);
typedef int (*s2_transmit_set_fn)(int index, int serial, unsigned long long mask);
typedef int (*s2_transmit_clear_fn)(int index);
typedef void (*s2_transmit_stats_fn)(unsigned long long* out);
typedef int (*s2_voice_set_muted_fn)(int slot, int muted);
typedef int (*s2_voice_get_muted_fn)(int slot);
typedef int (*s2_usermsg_hook_sub_fn)(const char* name, char* canonicalOut, int canonicalLen);
typedef int (*s2_usermsg_hook_unsub_fn)(int id);
typedef int (*s2_usermsg_hook_read_int_fn)(const char* path, long long* out);
typedef int (*s2_usermsg_hook_read_float_fn)(const char* path, double* out);
typedef int (*s2_usermsg_hook_read_string_fn)(const char* path, char* buf, int buflen);
typedef int (*s2_usermsg_hook_has_field_fn)(const char* path);
typedef int (*s2_usermsg_hook_recipients_fn)(unsigned long long* outMask);
typedef int (*s2_usermsg_hook_debug_fn)(char* buf, int buflen);
typedef int (*s2_server_build_number_fn)(void);
typedef void (*s2_crash_test_native_fn)(int kind);
typedef void* (*s2_ent_resolve_fn)(int index, int serial);
typedef long long (*s2_ent_identity_flags_fn)(int index, int serial);
typedef int (*s2_ent_snapshot_fn)(int* out_indices, int* out_serials, int cap);
typedef int (*s2_engine_call_resolve_fn)(const char* kind, const char* module, const char* pattern, const char* resolve, const char* className, int vtableIndex, const char* prologue, char* reasonOut, int reasonCap);
typedef int (*s2_engine_call_invoke_fn)(int callId, int entIndex, int entSerial, int subObjOff, const uint64_t* gp, const unsigned char* gpKind, int gpCount, const double* fp, int fpCount, const char* const* strs, const float* vecs, int retKind, uint64_t* retOut);
typedef int (*s2_voice_audible_set_fn)(int sender, uint64_t mask);
typedef int (*s2_voice_audible_clear_fn)(int sender);
typedef int (*s2_voice_audible_stats_fn)(uint64_t* out);
typedef int (*s2_client_command_fn)(int slot, const char* cmd);
typedef int (*s2_client_fake_command_fn)(int slot, const char* cmd);
typedef long long (*s2_ent_identity_flags_clear_fn)(int index, int serial, unsigned int mask);
typedef int (*s2_defer_selftest_fn)(void);
typedef int (*s2_hook_install_fn)(int hookId, int shape, int64_t addr, char* reasonOut, int reasonCap);
typedef void (*s2_hook_arm_bypass_fn)(int hookId);
typedef void (*s2_hook_disarm_bypass_fn)(int hookId);
typedef int (*s2_hook_read_f32_fn)(void* argView, int idx, float* out);
typedef int (*s2_hook_read_i32_fn)(void* argView, int idx, int32_t* out);
typedef int (*s2_hook_write_f32_fn)(void* argView, int idx, float value);
typedef int (*s2_hook_write_i32_fn)(void* argView, int idx, int32_t value);
typedef int (*s2_hook_receiver_handle_fn)(void* argView, uint32_t* outHandle);
typedef int64_t (*s2_engine_call_address_fn)(int callId);
typedef int (*s2_entity_set_gravity_scale_fn)(int index, int serial, float scale);
typedef int (*s2_entity_apply_abs_velocity_impulse_fn)(int index, int serial, const float* impulse);
typedef int (*s2_entity_stop_sound_fn)(int index, int serial, const char* soundName);
typedef int (*s2_entity_set_body_group_by_name_fn)(int index, int serial, const char* name, int group);
typedef int (*s2_entity_set_model_scale_fn)(int index, int serial, float scale);
typedef int (*s2_cvar_set_fn)(const char* name, const char* value);
typedef int (*s2_hook_read_u16_at_q_fn)(void* argView, int qslot, int offset, uint16_t* out);
typedef int (*s2_hook_self_matches_field_fn)(void* argView, int index, int serial, int offset);

/* The C-ABI engine-ops table. Field ORDER is the ABI. Generated from
 * core/engine-ops.jsonc — must stay index-for-index with the Rust mirror. */
typedef struct {
    s2_schema_offset_fn schema_offset;
    s2_ent_by_index_fn ent_by_index;
    s2_deref_handle_fn deref_handle;
    s2_ent_state_changed_fn ent_state_changed;
    s2_concommand_register_fn concommand_register;
    s2_schema_enumerate_fn schema_enumerate;
    /* --- Slice 5D.1: game-event engine-ops --- */
    s2_event_subscribe_fn event_subscribe;
    s2_event_unsubscribe_fn event_unsubscribe;
    s2_event_get_int_fn event_get_int;
    s2_event_get_float_fn event_get_float;
    s2_event_get_bool_fn event_get_bool;
    s2_event_get_string_fn event_get_string;
    s2_event_get_uint64_fn event_get_uint64;
    s2_event_get_player_slot_fn event_get_player_slot;
    /* --- Slice 5D.2: engine-identity ops --- */
    s2_client_valid_fn client_valid;
    s2_client_userid_fn client_userid;
    s2_client_signon_fn client_signon;
    s2_client_name_fn client_name;
    s2_client_find_by_userid_fn client_find_by_userid;
    /* --- Slice 5D.3: event write/fire ops --- */
    s2_event_set_int_fn event_set_int;
    s2_event_set_float_fn event_set_float;
    s2_event_set_bool_fn event_set_bool;
    s2_event_set_string_fn event_set_string;
    s2_event_set_uint64_fn event_set_uint64;
    s2_event_create_fn event_create;
    s2_event_fire_fn event_fire;
    /* --- Slice 5E.2: config ops --- */
    s2_config_read_fn config_read;
    s2_config_write_fn config_write;
    /* --- Slice 6.1: chat messaging op --- */
    s2_client_print_fn client_print;
    /* --- Slice 6.2: client SteamID op --- */
    s2_client_steamid_fn client_steamid;
    /* --- Slice 6.3: client kick op --- */
    s2_client_kick_fn client_kick;
    /* --- Slice 6.4: server command + map-validity ops --- */
    s2_server_command_fn server_command;
    s2_server_map_valid_fn server_map_valid;
    s2_damage_read_float_fn damage_read_float;
    s2_damage_read_int_fn damage_read_int;
    s2_damage_write_float_fn damage_write_float;
    s2_damage_victim_fn damage_victim;
    s2_cvar_get_fn cvar_get;
    /* --- ban-reason sub-project 2 --- */
    s2_client_console_print_fn client_console_print;
    s2_client_address_fn client_address;
    /* --- reservedslots+basetriggers: server-info ops --- */
    s2_server_max_clients_fn server_max_clients;
    s2_server_map_name_fn server_map_name;
    s2_server_game_time_fn server_game_time;
    /* --- Slice DB: data-dir op --- */
    s2_db_data_dir_fn db_data_dir;
    /* --- Slice menu: per-client event fire --- */
    s2_event_fire_to_client_fn event_fire_to_client;
    /* --- Slice nominations: raw config-file read/write --- */
    s2_config_read_file_fn config_read_file;
    s2_config_write_file_fn config_write_file;
    /* --- Ray-trace slice: CNavPhysicsInterface::TraceShape --- */
    s2_trace_shape_fn trace_shape;
    /* --- Entity-creation lifecycle slice --- */
    s2_entity_create_fn entity_create;
    s2_entity_spawn_fn entity_spawn;
    s2_entity_teleport_fn entity_teleport;
    s2_entity_remove_fn entity_remove;
    /* --- Item slice --- */
    s2_entity_subobj_vcall_fn entity_subobj_vcall;
    s2_entity_read_handle_vector_fn entity_read_handle_vector;
    /* --- Entity-I/O slice --- */
    s2_entity_fire_input_fn entity_fire_input;
    /* --- EKV slice --- */
    s2_entity_spawn_kv_fn entity_spawn_kv;
    /* --- Game-rules + UserMessage slice --- */
    s2_entity_find_by_class_fn entity_find_by_class;
    /* --- UserMessage send family --- */
    s2_user_message_create_fn user_message_create;
    s2_user_message_set_int_fn user_message_set_int;
    s2_user_message_set_float_fn user_message_set_float;
    s2_user_message_set_string_fn user_message_set_string;
    s2_user_message_set_bool_fn user_message_set_bool;
    s2_user_message_send_fn user_message_send;
    /* --- FakeConVar slice --- */
    s2_convar_register_fn convar_register;
    /* --- Translations slice --- */
    s2_translations_read_fn translations_read;
    s2_client_language_fn client_language;
    /* --- Zones real-trigger slice --- */
    s2_collision_activate_fn collision_activate;
    s2_entity_set_model_fn entity_set_model;
    /* --- Entity lifecycle listeners slice --- */
    s2_entity_listener_install_fn entity_listener_install;
    /* --- entity_name slice --- */
    s2_entity_name_fn entity_name;
    /* --- Sound slice --- */
    s2_sound_emit_fn sound_emit;
    s2_sound_precache_add_fn sound_precache_add;
    s2_usercmd_hook_install_fn usercmd_hook_install;
    s2_usercmd_read_fn usercmd_read;
    s2_usercmd_write_fn usercmd_write;
    s2_usercmd_read_buttons_fn usercmd_read_buttons;
    s2_usercmd_write_buttons_fn usercmd_write_buttons;
    s2_usercmd_clear_subtick_fn usercmd_clear_subtick;
    /* --- checktransmit slice --- */
    s2_transmit_set_fn transmit_set;
    s2_transmit_clear_fn transmit_clear;
    s2_transmit_stats_fn transmit_stats;
    s2_voice_set_muted_fn voice_set_muted;
    s2_voice_get_muted_fn voice_get_muted;
    /* --- UserMessage-interception slice --- */
    s2_usermsg_hook_sub_fn usermsg_hook_sub;
    s2_usermsg_hook_unsub_fn usermsg_hook_unsub;
    s2_usermsg_hook_read_int_fn usermsg_hook_read_int;
    s2_usermsg_hook_read_float_fn usermsg_hook_read_float;
    s2_usermsg_hook_read_string_fn usermsg_hook_read_string;
    s2_usermsg_hook_has_field_fn usermsg_hook_has_field;
    s2_usermsg_hook_recipients_fn usermsg_hook_recipients;
    s2_usermsg_hook_debug_fn usermsg_hook_debug;
    /* --- Crash-reporter slice — APPENDED after usermsg_hook_debug --- */
    s2_server_build_number_fn server_build_number;
    /* --- Crash-harness — APPENDED after server_build_number --- */
    s2_crash_test_native_fn crash_test_native;
    /* --- E1 entity-liveness slice --- */
    s2_ent_resolve_fn ent_resolve;
    s2_ent_identity_flags_fn ent_identity_flags;
    s2_ent_snapshot_fn ent_snapshot;
    /* --- Plugin-declared engine calls --- */
    s2_engine_call_resolve_fn engine_call_resolve;
    s2_engine_call_invoke_fn engine_call_invoke;
    /* --- Voice-hearability slice --- */
    s2_voice_audible_set_fn voice_audible_set;
    s2_voice_audible_clear_fn voice_audible_clear;
    s2_voice_audible_stats_fn voice_audible_stats;
    /* --- client-command slice --- */
    s2_client_command_fn client_command;
    s2_client_fake_command_fn client_fake_command;
    /* --- identity-flag clear --- */
    s2_ent_identity_flags_clear_fn ent_identity_flags_clear;
    /* --- deferred-dispatch selftest --- */
    s2_defer_selftest_fn defer_selftest;
    /* --- declarative inbound hooks --- */
    s2_hook_install_fn hook_install;
    s2_hook_arm_bypass_fn hook_arm_bypass;
    /* --- declarative inbound hooks, core half --- */
    s2_hook_disarm_bypass_fn hook_disarm_bypass;
    s2_hook_read_f32_fn hook_read_f32;
    s2_hook_read_i32_fn hook_read_i32;
    s2_hook_write_f32_fn hook_write_f32;
    s2_hook_write_i32_fn hook_write_i32;
    s2_hook_receiver_handle_fn hook_receiver_handle;
    s2_engine_call_address_fn engine_call_address;
    /* --- Entity-property slice --- */
    s2_entity_set_gravity_scale_fn entity_set_gravity_scale;
    s2_entity_apply_abs_velocity_impulse_fn entity_apply_abs_velocity_impulse;
    s2_entity_stop_sound_fn entity_stop_sound;
    s2_entity_set_body_group_by_name_fn entity_set_body_group_by_name;
    s2_entity_set_model_scale_fn entity_set_model_scale;
    /* --- ICvar set — write through ConVarData, not ServerCommand --- */
    s2_cvar_set_fn cvar_set;
    /* --- Pickup-gate accessors — u16 at q[qslot]+schemaOffset; pointer never crosses to JS --- */
    s2_hook_read_u16_at_q_fn hook_read_u16_at_q;
    /* --- Pickup-gate accessors — does this live entity's pointer-at-offset equal the view self --- */
    s2_hook_self_matches_field_fn hook_self_matches_field;
} S2EngineOps;
