// Pure emitter: NavModel → TypeScript declaration file for nav wrappers.
// No I/O, no Date/random — deterministic.

import type { NavModel } from "./model.ts";
import { TSTYPE, VEC_INFO } from "../schemagen/model.ts";

const HEADER = "// GENERATED by `s2script gen-nav` from nav-targets.json — DO NOT EDIT.";

export function emitNavDts(model: NavModel): string {
  // Collect which imports are actually needed.
  let needsEntityRef = false;
  let needsVector = false;
  let needsQAngle = false;
  for (const w of model.wrappers) {
    for (const f of w.fields) {
      if (f.accessorKind === "handle") needsEntityRef = true;
      const vi = VEC_INFO[f.accessorKind];
      if (vi?.cls === "Vector") needsVector = true;
      if (vi?.cls === "QAngle") needsQAngle = true;
    }
  }

  const out: string[] = [HEADER];

  // Emit imports only for what's used.
  const mathTypes: string[] = [];
  if (needsVector) mathTypes.push("Vector");
  if (needsQAngle) mathTypes.push("QAngle");
  if (mathTypes.length) out.push(`import type { ${mathTypes.join(", ")} } from "@s2script/sdk/math";`);
  if (needsEntityRef) out.push('import type { EntityRef } from "@s2script/sdk/entity";');
  out.push("");

  // One interface per wrapper. The write-through caveat is stated ONCE on the interface rather
  // than cloned onto every writable field — repeating it N times buries it.
  for (const w of model.wrappers) {
    if (w.fields.some(f => f.navWritable)) {
      out.push(`/**`);
      out.push(` * Fields NOT marked \`readonly\` are writable.`);
      out.push(` *`);
      out.push(` * A write takes effect immediately — the server reads these during movement — but it is **not**`);
      out.push(` * flagged for replication, because this object is reached through a pointer chain and the`);
      out.push(` * change-notifier addresses the root entity. A client predicting the old value may therefore`);
      out.push(` * see brief mismatch until the next authoritative correction. SourceMod's \`SetEntPropFloat\``);
      out.push(` * on the same fields behaves the same way.`);
      out.push(` */`);
    }
    out.push(`export interface ${w.wrapper} {`);
    for (const f of w.fields) {
      // Read-only unless nav-targets.json opted the field into write-through.
      out.push(`  ${f.navWritable ? "" : "readonly "}${f.propName}: ${TSTYPE[f.accessorKind]};`);
    }
    out.push("}", "");
  }

  return out.join("\n");
}
