// Pure emitter: NavModel → runtime JS (nav wrappers + applyNav).
// No I/O, no Date/random — deterministic.

import type { NavModel } from "./model.ts";
import { VEC_INFO } from "../schemagen/model.ts";
import type { AccessorKind } from "../schemagen/model.ts";

const HEADER = "// GENERATED by `s2script gen-nav` from nav-targets.json — DO NOT EDIT.";
const S = JSON.stringify;

// AccessorKind → EntityRef.*Via method name (for scalar kinds).
const READ_VIA: Partial<Record<AccessorKind, string>> = {
  f32: "readFloat32Via",
  bool: "readBoolVia",
  i8: "readInt8Via",
  i16: "readInt16Via",
  i32: "readInt32Via",
  u8: "readUInt8Via",
  u16: "readUInt16Via",
  u32: "readUInt32Via",
};

// AccessorKind → EntityRef.write*Via. Narrower than READ_VIA on purpose — these are the chain
// writers that exist. buildNavModel already rejects an allowlisted field of any other kind, so a
// missing entry here can never silently degrade a setter into nothing.
const WRITE_VIA: Partial<Record<AccessorKind, string>> = {
  f32: "writeFloat32Via",
  bool: "writeBoolVia",
  i32: "writeInt32Via",
};

export function emitNavJs(model: NavModel): string {
  const out: string[] = [HEADER, "(function () {", "  var off = __s2_schema_offset;"];

  // Collect which Vector/QAngle classes are actually needed.
  const vecClasses = new Set<string>();
  for (const w of model.wrappers) {
    for (const f of w.fields) {
      const vi = VEC_INFO[f.accessorKind];
      if (vi) vecClasses.add(vi.cls);
    }
  }
  for (const cls of [...vecClasses].sort()) {
    out.push(`  var ${cls} = __s2require("@s2script/sdk/math").${cls};`);
  }

  // Emit one constructor + Object.defineProperties block per wrapper.
  for (const w of model.wrappers) {
    // `base` is the summed offset of any embedded hops (0 when there are none), added to every
    // field offset. Kept off the path because `read*Via` DEREFERENCES each path entry, and an
    // embedded struct must not be dereferenced — it is part of the object already reached.
    out.push(`  function ${w.wrapper}(root, path, base) { this.root = root; this.path = path; this.base = base; }`);
    // notifyChanged(): flag the sub-object for replication after a write.
    //
    // Setters deliberately do NOT do this (see the write note below): for most targets the server
    // reads the field every tick and replication is irrelevant. It is NOT irrelevant for anything a
    // CLIENT renders — match stats drive the scoreboard, so a write nobody is told about is a write
    // nobody sees.
    //
    // Notifying at path[0] is exactly what the C# does for this case
    // (`SetStateChanged(controller, "m_pActionTrackingServices")`): the FIRST hop is a field on the
    // root entity, so its offset is the one the engine's dirty-tracking understands. Later hops are
    // inside the pointed-to object and would mark the wrong bytes on the wrong entity — which is why
    // this is a separate, explicit call rather than something a setter does for you.
    out.push(`  ${w.wrapper}.prototype.notifyChanged = function () {`);
    out.push(`    if (this.path.length > 0) this.root.notifyStateChanged(this.path[0]);`);
    out.push(`  };`);
    out.push(`  Object.defineProperties(${w.wrapper}.prototype, {`);
    for (const f of w.fields) {
      // `addOffset` is non-zero only for a flattened value wrapper, where the scalar sits at
      // wrapperOffset + delta. Both wrappers reachable from nav today (GameTime_t, GameTick_t) put
      // m_Value at +0, so this changes no current output — but omitting it would silently read the
      // wrong bytes the moment a wrapper with a non-zero value offset came into range.
      const own = `off(${S(f.declaringClass)},${S(f.rawName)})`;
      const withDelta = f.addOffset ? `${own} + ${f.addOffset}` : own;
      const resolve = `${withDelta} + this.base`;
      let getter: string;
      const kind = f.accessorKind;
      if (kind === "u64") {
        getter = `get: function () { var v = this.root.readUInt64Via(this.path, ${resolve}); return v === null ? null : v.toString(); }`;
      } else if (kind === "i64") {
        getter = `get: function () { var v = this.root.readInt64Via(this.path, ${resolve}); return v === null ? null : v.toString(); }`;
      } else if (VEC_INFO[kind]) {
        const vi = VEC_INFO[kind]!;
        getter = `get: function () { var a = this.root.readFloatsChain(this.path, ${resolve}, ${vi.count}); return a === null ? null : new ${vi.cls}(a[0], a[1], a[2]); }`;
      } else if (kind === "handle") {
        getter = `get: function () { return this.root.readHandleVia(this.path, ${resolve}); }`;
      } else {
        const method = READ_VIA[kind];
        if (!method) continue;  // unrecognised kind (should not happen with a well-formed model)
        getter = `get: function () { return this.root.${method}(this.path, ${resolve}); }`;
      }
      // A setter only for allowlisted fields. NOTE: no notifyStateChanged — it resolves the ROOT
      // entity, and a chain write changes a SUBOBJECT, so notifying with a chain-relative offset
      // would mark the wrong bytes on the wrong object. The write lands (the server reads these
      // every tick); it just is not flagged for replication. See the design spec §6.
      const wmethod = f.navWritable ? WRITE_VIA[kind] : undefined;
      const setter = wmethod
        ? `, set: function (v) { this.root.${wmethod}(this.path, ${resolve}, v); }`
        : "";
      out.push(`    ${S(f.propName)}: { ${getter}${setter} },`);
    }
    out.push("  });");
  }

  // Build applyNav: per source class, emit per-getter inline hop resolution.
  // Offsets are resolved inside each getter (per access) — self-healing and boot-window-safe:
  // if the schema hasn't warmed yet, off() returns -1 and the guard returns null; the next
  // access re-resolves and succeeds once the schema is live.
  const bySource = new Map<string, typeof model.wrappers[0][]>();
  for (const w of model.wrappers) {
    if (!bySource.has(w.source)) bySource.set(w.source, []);
    bySource.get(w.source)!.push(w);
  }

  out.push("  function applyNav(proto, className) {");
  for (const [src, wrappers] of [...bySource.entries()].sort((a, b) => a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0)) {
    out.push(`    if (className === ${S(src)}) {`);
    for (const w of wrappers) {
      out.push(`      Object.defineProperty(proto, ${S(w.prop)}, {`);
      out.push(`        get: function () {`);
      out.push(`          var _p = [];`);
      for (let i = 0; i < w.path.length; i++) {
        const h = w.path[i];
        out.push(`          var o${i} = off(${S(h.cls)},${S(h.field)}); if (o${i} < 0) return null; _p.push(o${i});`);
      }
      if (w.base.length > 0) {
        out.push(`          var _b = 0;`);
        for (let i = 0; i < w.base.length; i++) {
          const h = w.base[i]!;
          // A failed base lookup must NOT fall through as 0 — that would silently read the start
          // of the target object instead of the embedded struct inside it.
          out.push(`          var b${i} = off(${S(h.cls)},${S(h.field)}); if (b${i} < 0) return null; _b += b${i};`);
        }
        out.push(`          return new ${w.wrapper}(this.ref, _p, _b);`);
      } else {
        out.push(`          return new ${w.wrapper}(this.ref, _p, 0);`);
      }
      out.push(`        }, enumerable: true, configurable: true,`);
      out.push(`      });`);
    }
    out.push("    }");
  }
  out.push("  }");
  out.push("  globalThis.__s2pkg_cs2_nav = { applyNav: applyNav };");
  out.push("})();");
  out.push("");  // trailing newline

  return out.join("\n");
}
