// Pure emitter: event model → events.generated.d.ts source text.
// No I/O, no Date/random — deterministic.

import type { EventDescriptor, GetterKey } from "./model.ts";

const HEADER = "// GENERATED by `s2script gen-events` from event-catalog.json — DO NOT EDIT.";

const GETTER_RET: Record<GetterKey, string> = {
  getBool: "boolean",
  getFloat: "number",
  getInt: "number",
  getPlayerSlot: "number",
  getString: "string",
  getUint64: "string",
};

/** Emit the full events.generated.d.ts source from a built model. */
export function emitEventDts(model: EventDescriptor[]): string {
  const out: string[] = [
    HEADER,
    'import type { GameEvent, HookResultValue } from "@s2script/sdk/events";',
    "",
  ];

  for (const { iface, byGetter } of model) {
    out.push(`export interface ${iface} extends GameEvent {`);
    for (const getter of Object.keys(byGetter) as GetterKey[]) {
      const fields = byGetter[getter];
      if (fields.length === 0) continue;
      const keys = fields.map((f) => `"${f}"`).join(" | ");
      const ret = GETTER_RET[getter];
      out.push(`  ${getter}(key: ${keys}): ${ret};`);
    }
    out.push("}", "");
  }

  out.push("export interface GameEvents {");
  for (const { event, iface } of model) {
    out.push(`  ${event}: ${iface};`);
  }
  out.push("}", "");

  out.push(
    "export function on<K extends keyof GameEvents>(name: K, handler: (ev: GameEvents[K]) => void): void;",
    "export function on(name: string, handler: (ev: GameEvent) => void): void;",
    "export function onPre<K extends keyof GameEvents>(name: K, handler: (ev: GameEvents[K]) => HookResultValue | void): void;",
    "export function onPre(name: string, handler: (ev: GameEvent) => HookResultValue | void): void;",
    "export function fire<K extends keyof GameEvents>(name: K, fields?: Record<string, number | string | boolean | bigint>, dontBroadcast?: boolean): boolean;",
    "export function fire(name: string, fields?: Record<string, number | string | boolean | bigint>, dontBroadcast?: boolean): boolean;",
  );

  return out.join("\n") + "\n";
}
