// Generated by scripts/gen-engine-function-abi.py; do not edit.
pub const PLATFORM: &str = "linux-x86_64-sysv";
pub const RECEIVERS: &[&str] = &["none", "entity"];
pub const ATOMS: &[(&str, usize)] = &[("u8", 1), ("i32", 4), ("u32", 4), ("i64", 8), ("u64", 8), ("f32", 4), ("f64", 8), ("ptr", 8)];
pub const MAX_PARAMETERS: usize = 32;
pub const MAX_CIF_ARGUMENTS: usize = 33;
pub const MAX_STACK_BYTES: usize = 256;
pub const STACK_SAFETY_BUFFER: usize = 128;
pub const GP_REGISTERS: usize = 6;
pub const SSE_REGISTERS: usize = 8;
