// GENERATED by `s2s build` from the plugin's gamedata — DO NOT EDIT.
// The EntityRef import is REQUIRED: a `declare module` augmentation resolves type names in its
// own file scope, so an un-imported EntityRef degrades to an error skipLibCheck can swallow.
import type { EntityRef } from "@s2script/sdk/entity";

declare module "@s2script/sdk/unsafe" {
  interface EngineCalls {
    setDialogVariableStringForPlayer: (self: EntityRef, playerSlot: number, panelId: string, variableName: string, value: string) => void;
    setHasClassForPlayer: (self: EntityRef, playerSlot: number, panelId: string, className: string, status: number) => void;
  }
}
