// GENERATED by `s2s build` from the plugin's gamedata — DO NOT EDIT.
// The EntityRef / HookResultValue imports are REQUIRED: a `declare module` augmentation
// resolves type names in its own file scope.
import type { HookResultValue } from "@s2script/sdk/events";
import type { EntityRef } from "@s2script/sdk/entity";

export interface OnCustomHudClickedView {
  readonly buttonId: string;
  readonly player: EntityRef | null;
}

declare module "@s2script/sdk/unsafe" {
  interface EngineHooks {
    onCustomHudClicked: (handler: (view: OnCustomHudClickedView) => HookResultValue | void) => void;
  }
}
