// @generated by scripts/gen-engine-ops.py from core/engine-ops.jsonc.
// DO NOT EDIT. Append a field to the list and re-run the script.
// Field ORDER is the ABI. This file is `include!`d into v8host.rs so the
// table stays one whole struct in the host (locked: do not split across modules).

/// Schema enumeration callbacks. Core provides these; the shim streams classes/fields.
pub type EmitClassFn = extern "C" fn(ctx: *mut c_void, name: *const c_char, parent: *const c_char);

pub type EmitFieldFn = extern "C" fn(ctx: *mut c_void, cls: *const c_char, name: *const c_char, offset: c_int, kind: *const c_char, type_name: *const c_char, inner: *const c_char, size: c_int,);

pub type EmitEnumFn = extern "C" fn(ctx: *mut c_void, enum_name: *const c_char, size: c_int, enumerator: *const c_char, value: i64,);

/// TraceShape out-struct. Layout is the ABI; mirrors the C S2TraceResult.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct S2TraceResult {
    pub did_hit: c_int,
    pub fraction: f32,
    pub endpos: [f32; 3],
    pub normal: [f32; 3],
    pub all_solid: c_int,
    pub hit_ent_handle: c_int,
}

/// Internal engine-function scalar/host-handle transport. Pointer bits never contain a native address.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct S2FunctionValue {
    pub kind: u8,
    pub flags: u8,
    pub reserved: u16,
    pub aux: u32,
    pub bits: u64,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct S2FunctionFrameInfo {
    pub version: u32,
    pub struct_size: u32,
    pub frame_token: u64,
    pub native_epoch: u64,
    pub invocation_id: u64,
    pub suppressed_owner: u64,
    pub parameter_count: u32,
    pub flags: u32,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct S2FunctionHookStatus {
    pub state: u32,
    pub reserved: u32,
    pub receipt: u64,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct S2FunctionCopyInput {
    pub version: u32,
    pub struct_size: u32,
    pub data: *const u8,
    pub size: u64,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct S2FunctionCopyOutput {
    pub version: u32,
    pub struct_size: u32,
    pub data: *mut u8,
    pub capacity: u64,
    pub size: u64,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct S2FunctionCopyProducer {
    pub version: u32,
    pub struct_size: u32,
    pub domain: u32,
    pub reserved: u32,
    pub digest: [u8; 32],
    pub generation: u64,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct S2FunctionInstanceOwner {
    pub version: u32,
    pub struct_size: u32,
    pub kind: u32,
    pub reserved: u32,
    pub id_digest: [u8; 32],
    pub generation: u64,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct S2FunctionInstancePrepared {
    pub version: u32,
    pub struct_size: u32,
    pub target: i64,
    pub capability: u64,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct S2FunctionInstanceAccess {
    pub version: u32,
    pub struct_size: u32,
    pub target: i64,
    pub frame_token: u64,
    pub native_epoch: u64,
    pub capability: u64,
    pub binding_id: u64,
}

pub type SchemaOffsetFn = extern "C" fn(cls: *const c_char, field: *const c_char) -> c_int;
pub type EntByIndexFn = extern "C" fn(idx: c_int) -> *mut c_void;
pub type DerefHandleFn = extern "C" fn(handle: c_uint) -> *mut c_void;
pub type EntStateChangedFn = extern "C" fn(ent: *mut c_void, offset: c_int);
pub type ConCommandRegisterFn = extern "C" fn(name: *const c_char);
pub type SchemaEnumerateFn = extern "C" fn(ctx: *mut c_void, emit_class: EmitClassFn, emit_field: EmitFieldFn, emit_enum: EmitEnumFn) -> c_int;
pub type EventSubscribeFn = extern "C" fn(name: *const c_char) -> c_int;
pub type EventUnsubscribeFn = extern "C" fn(name: *const c_char) -> c_int;
pub type EventGetIntFn = extern "C" fn(key: *const c_char) -> i32;
pub type EventGetFloatFn = extern "C" fn(key: *const c_char) -> f32;
pub type EventGetBoolFn = extern "C" fn(key: *const c_char) -> c_int;
pub type EventGetStringFn = extern "C" fn(key: *const c_char) -> *const c_char;
pub type EventGetUint64Fn = extern "C" fn(key: *const c_char) -> u64;
pub type EventGetPlayerSlotFn = extern "C" fn(key: *const c_char) -> i32;
pub type ClientValidFn = extern "C" fn(slot: c_int) -> c_int;
pub type ClientUseridFn = extern "C" fn(slot: c_int) -> i32;
pub type ClientSignonFn = extern "C" fn(slot: c_int) -> i32;
pub type ClientNameFn = extern "C" fn(slot: c_int) -> *const c_char;
pub type ClientFindByUseridFn = extern "C" fn(userid: c_int) -> i32;
pub type EventSetIntFn = extern "C" fn(key: *const c_char, value: i32);
pub type EventSetFloatFn = extern "C" fn(key: *const c_char, value: f32);
pub type EventSetBoolFn = extern "C" fn(key: *const c_char, value: c_int);
pub type EventSetStringFn = extern "C" fn(key: *const c_char, value: *const c_char);
pub type EventSetUint64Fn = extern "C" fn(key: *const c_char, value: u64);
pub type EventCreateFn = extern "C" fn(name: *const c_char) -> c_int;
pub type EventFireFn = extern "C" fn(dont_broadcast: c_int) -> c_int;
pub type ConfigReadFn = extern "C" fn(id: *const c_char) -> *const c_char;
pub type ConfigWriteFn = extern "C" fn(id: *const c_char, content: *const c_char) -> c_int;
pub type ClientPrintFn = extern "C" fn(slot: c_int, msg: *const c_char);
pub type ClientSteamidFn = extern "C" fn(slot: c_int) -> *const c_char;
pub type ClientKickFn = extern "C" fn(slot: c_int, reason: *const c_char);
pub type ServerCommandFn = extern "C" fn(cmd: *const c_char);
pub type ServerMapValidFn = extern "C" fn(map: *const c_char) -> c_int;
pub type DamageReadFloatFn = extern "C" fn(offset: c_int) -> f32;
pub type DamageReadIntFn = extern "C" fn(offset: c_int) -> c_int;
pub type DamageWriteFloatFn = extern "C" fn(offset: c_int, value: f32);
pub type DamageVictimFn = extern "C" fn() -> c_int;
pub type CvarGetFn = extern "C" fn(name: *const c_char) -> *const c_char;
pub type ClientConsolePrintFn = extern "C" fn(slot: c_int, msg: *const c_char);
pub type ClientAddressFn = extern "C" fn(slot: c_int) -> *const c_char;
pub type ServerMaxClientsFn = extern "C" fn() -> c_int;
pub type ServerMapNameFn = extern "C" fn() -> *const c_char;
pub type ServerGameTimeFn = extern "C" fn() -> f32;
pub type DbDataDirFn = extern "C" fn() -> *const c_char;
pub type EventFireToClientFn = extern "C" fn(slot: c_int) -> c_int;
pub type ConfigReadFileFn = extern "C" fn(name: *const c_char) -> *const c_char;
pub type ConfigWriteFileFn = extern "C" fn(name: *const c_char, content: *const c_char) -> i32;
pub type TraceShapeFn = extern "C" fn(start: *const f32, end: *const f32, mins: *const f32, maxs: *const f32, interacts_with: u64, interacts_exclude: u64, ignore_ent_idx: c_int, ignore_ent_serial: c_int, out: *mut S2TraceResult,) -> c_int;
pub type EntityCreateFn = extern "C" fn(*const std::os::raw::c_char) -> c_int;
pub type EntitySpawnFn = extern "C" fn(c_int, c_int) -> c_int;
pub type EntityTeleportFn = extern "C" fn(c_int, c_int, *const f32, *const f32, *const f32) -> c_int;
pub type EntityRemoveFn = extern "C" fn(c_int, c_int) -> c_int;
pub type EntitySubobjVcallFn = extern "C" fn(c_int, c_int, c_int, c_int, c_int, c_int) -> c_int;
pub type EntityReadHandleVecFn = extern "C" fn(c_int, c_int, *const c_int, c_int, c_int, c_int, *mut c_int) -> c_int;
pub type EntityFireInputFn = extern "C" fn(c_int, c_int, *const c_char, *const c_char, c_int, c_int, c_int, c_int, f32) -> c_int;
pub type EntitySpawnKvFn = extern "C" fn(c_int, c_int, c_int, *const *const c_char, *const c_int, *const *const c_char) -> c_int;
pub type EntityFindByClassFn = extern "C" fn(*const std::os::raw::c_char, *mut i32, *mut i32, i32) -> i32;
pub type UserMessageCreateFn = extern "C" fn(*const std::os::raw::c_char) -> i32;
pub type UserMessageSetIntFn = extern "C" fn(*const std::os::raw::c_char, i64) -> i32;
pub type UserMessageSetFloatFn = extern "C" fn(*const std::os::raw::c_char, f64) -> i32;
pub type UserMessageSetStringFn = extern "C" fn(*const std::os::raw::c_char, *const std::os::raw::c_char) -> i32;
pub type UserMessageSetBoolFn = extern "C" fn(*const std::os::raw::c_char, i32) -> i32;
pub type UserMessageSendFn = extern "C" fn(*const i32, i32) -> i32;
pub type ConvarRegisterFn = unsafe extern "C" fn(*const std::os::raw::c_char, *const std::os::raw::c_char, u64, i32, *const std::os::raw::c_char, *const std::os::raw::c_char, *const std::os::raw::c_char) -> i32;
pub type TranslationsReadFn = extern "C" fn(lang: *const c_char, name: *const c_char) -> *const c_char;
pub type ClientLanguageFn = extern "C" fn(slot: c_int) -> *const c_char;
pub type CollisionActivateFn = extern "C" fn(c_int, c_int) -> c_int;
pub type EntitySetModelFn = extern "C" fn(c_int, c_int, *const std::os::raw::c_char) -> c_int;
pub type EntityListenerInstallFn = extern "C" fn() -> c_int;
pub type EntityNameFn = extern "C" fn(c_int, c_int) -> *const c_char;
pub type SoundEmitFn = extern "C" fn(*const c_char, c_int, c_int, *const c_int, c_int, f32) -> c_int;
pub type SoundPrecacheAddFn = extern "C" fn(*const c_char) -> c_int;
pub type UsercmdHookInstallFn = extern "C" fn() -> c_int;
pub type UsercmdReadFn = extern "C" fn(c_int) -> f64;
pub type UsercmdWriteFn = extern "C" fn(c_int, f64);
pub type UsercmdReadButtonsFn = extern "C" fn() -> u64;
pub type UsercmdWriteButtonsFn = extern "C" fn(u64);
pub type UsercmdClearSubtickFn = extern "C" fn();
pub type TransmitSetFn = extern "C" fn(index: std::os::raw::c_int, serial: std::os::raw::c_int, mask: u64) -> std::os::raw::c_int;
pub type TransmitClearFn = extern "C" fn(index: std::os::raw::c_int) -> std::os::raw::c_int;
pub type TransmitStatsFn = extern "C" fn(out: *mut u64);
pub type VoiceSetMutedFn = extern "C" fn(c_int, c_int) -> c_int;
pub type VoiceGetMutedFn = extern "C" fn(c_int) -> c_int;
pub type UsermsgHookSubFn = extern "C" fn(*const std::os::raw::c_char, *mut std::os::raw::c_char, c_int) -> c_int;
pub type UsermsgHookUnsubFn = extern "C" fn(c_int) -> c_int;
pub type UsermsgHookReadIntFn = extern "C" fn(*const std::os::raw::c_char, *mut i64) -> c_int;
pub type UsermsgHookReadFloatFn = extern "C" fn(*const std::os::raw::c_char, *mut f64) -> c_int;
pub type UsermsgHookReadStringFn = extern "C" fn(*const std::os::raw::c_char, *mut std::os::raw::c_char, c_int) -> c_int;
pub type UsermsgHookHasFieldFn = extern "C" fn(*const std::os::raw::c_char) -> c_int;
pub type UsermsgHookRecipientsFn = extern "C" fn(*mut u64) -> c_int;
pub type UsermsgHookDebugFn = extern "C" fn(*mut std::os::raw::c_char, c_int) -> c_int;
pub type ServerBuildNumberFn = extern "C" fn() -> c_int;
pub type CrashTestNativeFn = extern "C" fn(kind: c_int);
pub type EntResolveFn = extern "C" fn(c_int, c_int) -> *mut c_void;
pub type EntIdentityFlagsFn = extern "C" fn(c_int, c_int) -> i64;
pub type EntSnapshotFn = extern "C" fn(*mut c_int, *mut c_int, c_int) -> c_int;
pub type EngineCallResolveFn = extern "C" fn(kind: *const c_char, module: *const c_char, pattern: *const c_char, resolve: *const c_char, class_name: *const c_char, vtable_index: c_int, validate_json: *const c_char, reason_out: *mut c_char, reason_cap: c_int) -> c_int;
pub type EngineCallInvokeFn = extern "C" fn(call_id: c_int, ent_index: c_int, ent_serial: c_int, subobj_off: c_int, gp: *const u64, gp_kind: *const u8, gp_count: c_int, fp: *const f64, fp_count: c_int, strs: *const *const c_char, vecs: *const f32, ret_kind: c_int, ret_out: *mut u64) -> c_int;
pub type VoiceAudibleSetFn = extern "C" fn(c_int, u64) -> c_int;
pub type VoiceAudibleClearFn = extern "C" fn(c_int) -> c_int;
pub type VoiceAudibleStatsFn = extern "C" fn(*mut u64) -> c_int;
pub type ClientCommandFn = extern "C" fn(slot: c_int, cmd: *const c_char) -> c_int;
pub type ClientFakeCommandFn = extern "C" fn(slot: c_int, cmd: *const c_char) -> c_int;
pub type EntIdentityFlagsClearFn = extern "C" fn(c_int, c_int, u32) -> i64;
pub type DeferSelftestFn = extern "C" fn() -> c_int;
pub type HookInstallFn = extern "C" fn(c_int, c_int, i64, *mut c_char, c_int) -> c_int;
pub type HookArmBypassFn = extern "C" fn(c_int);
pub type HookDisarmBypassFn = extern "C" fn(c_int);
pub type HookReadF32Fn = extern "C" fn(*mut std::ffi::c_void, c_int, *mut f32) -> c_int;
pub type HookReadI32Fn = extern "C" fn(*mut std::ffi::c_void, c_int, *mut i32) -> c_int;
pub type HookReadStrFn = extern "C" fn(*mut std::ffi::c_void, c_int, *mut std::ffi::c_char, c_int) -> c_int;
pub type HookWriteF32Fn = extern "C" fn(*mut std::ffi::c_void, c_int, f32) -> c_int;
pub type HookWriteI32Fn = extern "C" fn(*mut std::ffi::c_void, c_int, i32) -> c_int;
pub type HookReceiverHandleFn = extern "C" fn(*mut std::ffi::c_void, *mut u32) -> c_int;
pub type EngineCallAddressFn = extern "C" fn(c_int) -> i64;
pub type EntitySetGravityScaleFn = extern "C" fn(c_int, c_int, f32) -> c_int;
pub type EntityApplyAbsVelocityImpulseFn = extern "C" fn(c_int, c_int, *const f32) -> c_int;
pub type EntityStopSoundFn = extern "C" fn(c_int, c_int, *const std::os::raw::c_char) -> c_int;
pub type EntitySetBodyGroupByNameFn = extern "C" fn(c_int, c_int, *const std::os::raw::c_char, c_int) -> c_int;
pub type EntitySetModelScaleFn = extern "C" fn(c_int, c_int, f32) -> c_int;
pub type CvarSetFn = extern "C" fn(name: *const c_char, value: *const c_char) -> c_int;
pub type HookReadU16AtQFn = extern "C" fn(*mut std::ffi::c_void, c_int, c_int, *mut u16) -> c_int;
pub type HookSelfMatchesFieldFn = extern "C" fn(*mut std::ffi::c_void, c_int, c_int, c_int) -> c_int;
pub type SdkhookVpAddFn = extern "C" fn(c_int, c_int, *const c_char, c_int) -> c_int;
pub type SdkhookVpRemoveFn = extern "C" fn(c_int, c_int, *const c_char, c_int) -> c_int;
pub type SdkhookVpDropFn = extern "C" fn(c_int, c_int) -> c_int;
pub type PluginFunctionOverridesFn = extern "C" fn(*const c_char) -> *const c_char;
pub type FunctionPrepareFn = extern "C" fn(*const c_char, *const c_char, *const c_char, *const c_char, *mut c_char, c_int) -> i64;
pub type FunctionCallFn = extern "C" fn(i64, u64, *const S2FunctionValue, c_int, *mut S2FunctionValue, *mut c_char, c_int) -> c_int;
pub type FunctionHookAcquireFn = extern "C" fn(i64, *mut c_char, c_int) -> i64;
pub type FunctionHookReleaseFn = extern "C" fn(i64) -> c_int;
pub type FunctionTargetReleaseFn = extern "C" fn(i64) -> c_int;
pub type FunctionHookStatusFn = extern "C" fn(i64, *mut S2FunctionHookStatus, *mut c_char, c_int) -> c_int;
pub type FunctionFrameReadFn = extern "C" fn(i64, u64, u64, *const c_char, c_int, u8, *mut S2FunctionValue, *mut c_char, c_int) -> c_int;
pub type FunctionFrameWriteFn = extern "C" fn(i64, u64, u64, *const c_char, c_int, *const S2FunctionValue, *mut c_char, c_int) -> c_int;
pub type FunctionFrameCommitFn = extern "C" fn(i64, u64, u64, *const c_char, c_int, *const S2FunctionValue, *mut c_char, c_int) -> c_int;
pub type FunctionFrameOverrideReturnFn = extern "C" fn(i64, u64, u64, *const c_char, *const S2FunctionValue, *mut S2FunctionValue, *mut c_char, c_int) -> c_int;
pub type FunctionCallCopyFn = extern "C" fn(i64, u64, *const S2FunctionValue, c_int, *mut S2FunctionValue, *const S2FunctionCopyInput, *mut S2FunctionCopyOutput, *const S2FunctionCopyProducer, *mut c_char, c_int) -> c_int;
pub type FunctionFrameReadCopyFn = extern "C" fn(i64, u64, u64, *const c_char, c_int, *mut S2FunctionValue, *mut S2FunctionCopyOutput, *mut c_char, c_int) -> c_int;
pub type FunctionFrameWriteCopyFn = extern "C" fn(i64, u64, u64, *const c_char, c_int, *const S2FunctionValue, *const S2FunctionCopyInput, *const S2FunctionCopyProducer, *mut c_char, c_int) -> c_int;
pub type FunctionFrameCommitCopyFn = extern "C" fn(i64, u64, u64, *const c_char, c_int, *const S2FunctionValue, *const S2FunctionCopyInput, *const S2FunctionCopyProducer, *mut c_char, c_int) -> c_int;
pub type FunctionFrameOverrideReturnCopyFn = extern "C" fn(i64, u64, u64, *const c_char, *const S2FunctionValue, *const S2FunctionCopyInput, *const S2FunctionCopyProducer, *mut S2FunctionValue, *mut S2FunctionCopyOutput, *mut c_char, c_int) -> c_int;
pub type FunctionPrepareInstanceFn = extern "C" fn(u64, *const S2FunctionInstanceOwner, *const c_char, *const c_char, *const c_char, *mut S2FunctionInstancePrepared, *mut c_char, c_int) -> c_int;
pub type FunctionInstanceActivateFn = extern "C" fn(u64, *const S2FunctionInstanceOwner, *mut c_char, c_int) -> c_int;
pub type FunctionInstanceReleaseFn = extern "C" fn(u64) -> c_int;
pub type FunctionFrameReadInstanceFn = extern "C" fn(*const S2FunctionInstanceAccess, c_int, *mut S2FunctionValue, *mut c_char, c_int) -> c_int;
pub type FunctionFrameFieldReadFn = extern "C" fn(*const S2FunctionInstanceAccess, c_int, u32, *mut S2FunctionValue, *mut c_char, c_int) -> c_int;
pub type FunctionFrameFieldWriteFn = extern "C" fn(*const S2FunctionInstanceAccess, c_int, u32, *const S2FunctionValue, *mut c_char, c_int) -> c_int;
pub type FunctionFrameHiddenReferencedByFn = extern "C" fn(*const S2FunctionInstanceAccess, c_int, *const S2FunctionValue, u32, *mut c_int, *mut c_char, c_int) -> c_int;

/// The C-ABI engine-ops table. Field ORDER is the ABI.
///
/// Generated from `core/engine-ops.jsonc`. Append-only across a release
/// boundary; a field may be deleted in the same zip (A5b). Do not reorder.
/// `Default` is all-None — test fixtures override the fields they need.
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct S2EngineOps {
    pub schema_offset: Option<SchemaOffsetFn>,
    pub ent_by_index: Option<EntByIndexFn>, // unused since E1 (kept for ABI order)
    pub deref_handle: Option<DerefHandleFn>, // unused since E1 (kept for ABI order)
    pub ent_state_changed: Option<EntStateChangedFn>,
    pub concommand_register: Option<ConCommandRegisterFn>,
    pub schema_enumerate: Option<SchemaEnumerateFn>,
    // --- Slice 5D.1: game-event engine-ops ---
    pub event_subscribe: Option<EventSubscribeFn>,
    pub event_unsubscribe: Option<EventUnsubscribeFn>,
    pub event_get_int: Option<EventGetIntFn>,
    pub event_get_float: Option<EventGetFloatFn>,
    pub event_get_bool: Option<EventGetBoolFn>,
    pub event_get_string: Option<EventGetStringFn>,
    pub event_get_uint64: Option<EventGetUint64Fn>,
    pub event_get_player_slot: Option<EventGetPlayerSlotFn>,
    // --- Slice 5D.2: engine-identity ops ---
    pub client_valid: Option<ClientValidFn>,
    pub client_userid: Option<ClientUseridFn>,
    pub client_signon: Option<ClientSignonFn>,
    pub client_name: Option<ClientNameFn>,
    pub client_find_by_userid: Option<ClientFindByUseridFn>,
    // --- Slice 5D.3: event write/fire ops ---
    pub event_set_int: Option<EventSetIntFn>,
    pub event_set_float: Option<EventSetFloatFn>,
    pub event_set_bool: Option<EventSetBoolFn>,
    pub event_set_string: Option<EventSetStringFn>,
    pub event_set_uint64: Option<EventSetUint64Fn>,
    pub event_create: Option<EventCreateFn>,
    pub event_fire: Option<EventFireFn>,
    // --- Slice 5E.2: config ops ---
    pub config_read: Option<ConfigReadFn>,
    pub config_write: Option<ConfigWriteFn>,
    // --- Slice 6.1: chat messaging op ---
    pub client_print: Option<ClientPrintFn>,
    // --- Slice 6.2: client SteamID op ---
    pub client_steamid: Option<ClientSteamidFn>,
    // --- Slice 6.3: client kick op ---
    pub client_kick: Option<ClientKickFn>,
    // --- Slice 6.4: server command + map-validity ops ---
    pub server_command: Option<ServerCommandFn>,
    pub server_map_valid: Option<ServerMapValidFn>,
    pub damage_read_float: Option<DamageReadFloatFn>,
    pub damage_read_int: Option<DamageReadIntFn>,
    pub damage_write_float: Option<DamageWriteFloatFn>,
    pub damage_victim: Option<DamageVictimFn>,
    pub cvar_get: Option<CvarGetFn>,
    // --- ban-reason sub-project 2 ---
    pub client_console_print: Option<ClientConsolePrintFn>,
    pub client_address: Option<ClientAddressFn>,
    // --- reservedslots+basetriggers: server-info ops ---
    pub server_max_clients: Option<ServerMaxClientsFn>,
    pub server_map_name: Option<ServerMapNameFn>,
    pub server_game_time: Option<ServerGameTimeFn>,
    // --- Slice DB: data-dir op ---
    pub db_data_dir: Option<DbDataDirFn>,
    // --- Slice menu: per-client event fire ---
    pub event_fire_to_client: Option<EventFireToClientFn>,
    // --- Slice nominations: raw config-file read/write ---
    pub config_read_file: Option<ConfigReadFileFn>,
    pub config_write_file: Option<ConfigWriteFileFn>,
    // --- Ray-trace slice: CNavPhysicsInterface::TraceShape ---
    pub trace_shape: Option<TraceShapeFn>,
    // --- Entity-creation lifecycle slice ---
    pub entity_create: Option<EntityCreateFn>,
    pub entity_spawn: Option<EntitySpawnFn>,
    pub entity_teleport: Option<EntityTeleportFn>,
    pub entity_remove: Option<EntityRemoveFn>,
    // --- Item slice ---
    pub entity_subobj_vcall: Option<EntitySubobjVcallFn>,
    pub entity_read_handle_vector: Option<EntityReadHandleVecFn>,
    // --- Entity-I/O slice ---
    pub entity_fire_input: Option<EntityFireInputFn>,
    // --- EKV slice ---
    pub entity_spawn_kv: Option<EntitySpawnKvFn>,
    // --- Game-rules + UserMessage slice ---
    pub entity_find_by_class: Option<EntityFindByClassFn>,
    // --- UserMessage send family ---
    pub user_message_create: Option<UserMessageCreateFn>,
    pub user_message_set_int: Option<UserMessageSetIntFn>,
    pub user_message_set_float: Option<UserMessageSetFloatFn>,
    pub user_message_set_string: Option<UserMessageSetStringFn>,
    pub user_message_set_bool: Option<UserMessageSetBoolFn>,
    pub user_message_send: Option<UserMessageSendFn>,
    // --- FakeConVar slice ---
    pub convar_register: Option<ConvarRegisterFn>,
    // --- Translations slice ---
    pub translations_read: Option<TranslationsReadFn>,
    pub client_language: Option<ClientLanguageFn>,
    // --- Zones real-trigger slice ---
    pub collision_activate: Option<CollisionActivateFn>,
    pub entity_set_model: Option<EntitySetModelFn>,
    // --- Entity lifecycle listeners slice ---
    pub entity_listener_install: Option<EntityListenerInstallFn>,
    // --- entity_name slice ---
    pub entity_name: Option<EntityNameFn>,
    // --- Sound slice ---
    pub sound_emit: Option<SoundEmitFn>,
    pub sound_precache_add: Option<SoundPrecacheAddFn>,
    pub usercmd_hook_install: Option<UsercmdHookInstallFn>,
    pub usercmd_read: Option<UsercmdReadFn>,
    pub usercmd_write: Option<UsercmdWriteFn>,
    pub usercmd_read_buttons: Option<UsercmdReadButtonsFn>,
    pub usercmd_write_buttons: Option<UsercmdWriteButtonsFn>,
    pub usercmd_clear_subtick: Option<UsercmdClearSubtickFn>,
    // --- checktransmit slice ---
    pub transmit_set: Option<TransmitSetFn>,
    pub transmit_clear: Option<TransmitClearFn>,
    pub transmit_stats: Option<TransmitStatsFn>,
    pub voice_set_muted: Option<VoiceSetMutedFn>,
    pub voice_get_muted: Option<VoiceGetMutedFn>,
    // --- UserMessage-interception slice ---
    pub usermsg_hook_sub: Option<UsermsgHookSubFn>,
    pub usermsg_hook_unsub: Option<UsermsgHookUnsubFn>,
    pub usermsg_hook_read_int: Option<UsermsgHookReadIntFn>,
    pub usermsg_hook_read_float: Option<UsermsgHookReadFloatFn>,
    pub usermsg_hook_read_string: Option<UsermsgHookReadStringFn>,
    pub usermsg_hook_has_field: Option<UsermsgHookHasFieldFn>,
    pub usermsg_hook_recipients: Option<UsermsgHookRecipientsFn>,
    pub usermsg_hook_debug: Option<UsermsgHookDebugFn>,
    // --- Crash-reporter slice — APPENDED after usermsg_hook_debug ---
    pub server_build_number: Option<ServerBuildNumberFn>,
    // --- Crash-harness — APPENDED after server_build_number ---
    pub crash_test_native: Option<CrashTestNativeFn>,
    // --- E1 entity-liveness slice ---
    pub ent_resolve: Option<EntResolveFn>,
    pub ent_identity_flags: Option<EntIdentityFlagsFn>,
    pub ent_snapshot: Option<EntSnapshotFn>,
    // --- Plugin-declared engine calls ---
    pub engine_call_resolve: Option<EngineCallResolveFn>,
    pub engine_call_invoke: Option<EngineCallInvokeFn>,
    // --- Voice-hearability slice ---
    pub voice_audible_set: Option<VoiceAudibleSetFn>,
    pub voice_audible_clear: Option<VoiceAudibleClearFn>,
    pub voice_audible_stats: Option<VoiceAudibleStatsFn>,
    // --- client-command slice ---
    pub client_command: Option<ClientCommandFn>,
    pub client_fake_command: Option<ClientFakeCommandFn>,
    // --- identity-flag clear ---
    pub ent_identity_flags_clear: Option<EntIdentityFlagsClearFn>,
    // --- deferred-dispatch selftest ---
    pub defer_selftest: Option<DeferSelftestFn>,
    // --- declarative inbound hooks ---
    pub hook_install: Option<HookInstallFn>,
    pub hook_arm_bypass: Option<HookArmBypassFn>,
    // --- declarative inbound hooks, core half ---
    pub hook_disarm_bypass: Option<HookDisarmBypassFn>,
    pub hook_read_f32: Option<HookReadF32Fn>,
    pub hook_read_i32: Option<HookReadI32Fn>,
    pub hook_read_str: Option<HookReadStrFn>,
    pub hook_write_f32: Option<HookWriteF32Fn>,
    pub hook_write_i32: Option<HookWriteI32Fn>,
    pub hook_receiver_handle: Option<HookReceiverHandleFn>,
    pub engine_call_address: Option<EngineCallAddressFn>,
    // --- Entity-property slice ---
    pub entity_set_gravity_scale: Option<EntitySetGravityScaleFn>,
    pub entity_apply_abs_velocity_impulse: Option<EntityApplyAbsVelocityImpulseFn>,
    pub entity_stop_sound: Option<EntityStopSoundFn>,
    pub entity_set_body_group_by_name: Option<EntitySetBodyGroupByNameFn>,
    pub entity_set_model_scale: Option<EntitySetModelScaleFn>,
    // --- ICvar set — write through ConVarData, not ServerCommand ---
    pub cvar_set: Option<CvarSetFn>,
    // --- Pickup-gate accessors — u16 at q[qslot]+schemaOffset; pointer never crosses to JS ---
    pub hook_read_u16_at_q: Option<HookReadU16AtQFn>,
    // --- Pickup-gate accessors — does this live entity's pointer-at-offset equal the view self ---
    pub hook_self_matches_field: Option<HookSelfMatchesFieldFn>,
    // --- SDKHooks VP — install per-entity SourceHook ---
    pub sdkhook_vp_add: Option<SdkhookVpAddFn>,
    pub sdkhook_vp_remove: Option<SdkhookVpRemoveFn>,
    pub sdkhook_vp_drop: Option<SdkhookVpDropFn>,
    // --- Immutable bounded plugin engine-function override snapshot ---
    pub plugin_function_overrides: Option<PluginFunctionOverridesFn>,
    // --- Shared native engine-function targets (opaque handles) ---
    pub function_prepare: Option<FunctionPrepareFn>,
    pub function_call: Option<FunctionCallFn>,
    pub function_hook_acquire: Option<FunctionHookAcquireFn>,
    pub function_hook_release: Option<FunctionHookReleaseFn>,
    pub function_target_release: Option<FunctionTargetReleaseFn>,
    pub function_hook_status: Option<FunctionHookStatusFn>,
    pub function_frame_read: Option<FunctionFrameReadFn>,
    pub function_frame_write: Option<FunctionFrameWriteFn>,
    pub function_frame_commit: Option<FunctionFrameCommitFn>,
    pub function_frame_override_return: Option<FunctionFrameOverrideReturnFn>,
    pub function_call_copy: Option<FunctionCallCopyFn>,
    pub function_frame_read_copy: Option<FunctionFrameReadCopyFn>,
    pub function_frame_write_copy: Option<FunctionFrameWriteCopyFn>,
    pub function_frame_commit_copy: Option<FunctionFrameCommitCopyFn>,
    pub function_frame_override_return_copy: Option<FunctionFrameOverrideReturnCopyFn>,
    pub function_prepare_instance: Option<FunctionPrepareInstanceFn>,
    pub function_instance_activate: Option<FunctionInstanceActivateFn>,
    pub function_instance_release: Option<FunctionInstanceReleaseFn>,
    pub function_frame_read_instance: Option<FunctionFrameReadInstanceFn>,
    pub function_frame_field_read: Option<FunctionFrameFieldReadFn>,
    pub function_frame_field_write: Option<FunctionFrameFieldWriteFn>,
    pub function_frame_hidden_referenced_by: Option<FunctionFrameHiddenReferencedByFn>,
}

impl S2EngineOps {
    /// Every field `None`. Test fixtures spread this and override what they wire.
    pub fn none() -> Self {
        Self::default()
    }
}
