// Pure emitter: NavModel → runtime JS (nav wrappers + applyNav).
// No I/O, no Date/random — deterministic.

import type { NavModel } from "./model.ts";
import { VEC_INFO } from "../schemagen/model.ts";
import type { AccessorKind } from "../schemagen/model.ts";

const HEADER = "// GENERATED by `s2script gen-nav` from nav-targets.json — DO NOT EDIT.";
const S = JSON.stringify;

// AccessorKind → EntityRef.*Via method name (for scalar kinds).
const READ_VIA: Partial<Record<AccessorKind, string>> = {
  f32: "readFloat32Via",
  bool: "readBoolVia",
  i8: "readInt8Via",
  i16: "readInt16Via",
  i32: "readInt32Via",
  u8: "readUInt8Via",
  u16: "readUInt16Via",
  u32: "readUInt32Via",
};

export function emitNavJs(model: NavModel): string {
  const out: string[] = [HEADER, "(function () {", "  var off = __s2_schema_offset;"];

  // Collect which Vector/QAngle classes are actually needed.
  const vecClasses = new Set<string>();
  for (const w of model.wrappers) {
    for (const f of w.fields) {
      const vi = VEC_INFO[f.accessorKind];
      if (vi) vecClasses.add(vi.cls);
    }
  }
  for (const cls of [...vecClasses].sort()) {
    out.push(`  var ${cls} = __s2require("@s2script/math").${cls};`);
  }

  // Emit one constructor + Object.defineProperties block per wrapper.
  for (const w of model.wrappers) {
    out.push(`  function ${w.wrapper}(root, path) { this.root = root; this.path = path; }`);
    out.push(`  Object.defineProperties(${w.wrapper}.prototype, {`);
    for (const f of w.fields) {
      const resolve = `off(${S(f.declaringClass)},${S(f.rawName)})`;
      let getter: string;
      const kind = f.accessorKind;
      if (kind === "u64") {
        getter = `get: function () { var v = this.root.readUInt64Via(this.path, ${resolve}); return v === null ? null : v.toString(); }`;
      } else if (kind === "i64") {
        getter = `get: function () { var v = this.root.readInt64Via(this.path, ${resolve}); return v === null ? null : v.toString(); }`;
      } else if (VEC_INFO[kind]) {
        const vi = VEC_INFO[kind]!;
        getter = `get: function () { var a = this.root.readFloatsChain(this.path, ${resolve}, ${vi.count}); return a === null ? null : new ${vi.cls}(a[0], a[1], a[2]); }`;
      } else if (kind === "handle") {
        getter = `get: function () { return this.root.readHandleVia(this.path, ${resolve}); }`;
      } else {
        const method = READ_VIA[kind];
        if (!method) continue;  // unrecognised kind (should not happen with a well-formed model)
        getter = `get: function () { return this.root.${method}(this.path, ${resolve}); }`;
      }
      out.push(`    ${S(f.propName)}: { ${getter} },`);
    }
    out.push("  });");
  }

  // Build applyNav: per source class, emit per-getter inline hop resolution.
  // Offsets are resolved inside each getter (per access) — self-healing and boot-window-safe:
  // if the schema hasn't warmed yet, off() returns -1 and the guard returns null; the next
  // access re-resolves and succeeds once the schema is live.
  const bySource = new Map<string, typeof model.wrappers[0][]>();
  for (const w of model.wrappers) {
    if (!bySource.has(w.source)) bySource.set(w.source, []);
    bySource.get(w.source)!.push(w);
  }

  out.push("  function applyNav(proto, className) {");
  for (const [src, wrappers] of [...bySource.entries()].sort((a, b) => a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0)) {
    out.push(`    if (className === ${S(src)}) {`);
    for (const w of wrappers) {
      out.push(`      Object.defineProperty(proto, ${S(w.prop)}, {`);
      out.push(`        get: function () {`);
      out.push(`          var _p = [];`);
      for (let i = 0; i < w.path.length; i++) {
        const h = w.path[i];
        out.push(`          var o${i} = off(${S(h.cls)},${S(h.field)}); if (o${i} < 0) return null; _p.push(o${i});`);
      }
      out.push(`          return new ${w.wrapper}(this.ref, _p);`);
      out.push(`        }, enumerable: true, configurable: true,`);
      out.push(`      });`);
    }
    out.push("    }");
  }
  out.push("  }");
  out.push("  globalThis.__s2pkg_cs2_nav = { applyNav: applyNav };");
  out.push("})();");
  out.push("");  // trailing newline

  return out.join("\n");
}
