// Pure emitter: NavModel → runtime JS (nav wrappers + applyNav).
// No I/O, no Date/random — deterministic.

import type { NavModel } from "./model.ts";
import { VEC_INFO } from "../schemagen/model.ts";
import type { AccessorKind } from "../schemagen/model.ts";

const HEADER = "// GENERATED by `s2script gen-nav` from nav-targets.json — DO NOT EDIT.";
const S = JSON.stringify;

// AccessorKind → EntityRef.*Via method name (for scalar kinds).
const READ_VIA: Partial<Record<AccessorKind, string>> = {
  f32: "readFloat32Via",
  bool: "readBoolVia",
  i8: "readInt8Via",
  i16: "readInt16Via",
  i32: "readInt32Via",
  u8: "readUInt8Via",
  u16: "readUInt16Via",
  u32: "readUInt32Via",
};

export function emitNavJs(model: NavModel): string {
  const out: string[] = [HEADER, "(function () {", "  var off = __s2_schema_offset;"];

  // Collect which Vector/QAngle classes are actually needed.
  const vecClasses = new Set<string>();
  for (const w of model.wrappers) {
    for (const f of w.fields) {
      const vi = VEC_INFO[f.accessorKind];
      if (vi) vecClasses.add(vi.cls);
    }
  }
  for (const cls of [...vecClasses].sort()) {
    out.push(`  var ${cls} = __s2require("@s2script/math").${cls};`);
  }

  // Emit one constructor + Object.defineProperties block per wrapper.
  for (const w of model.wrappers) {
    out.push(`  function ${w.wrapper}(root, path) { this.root = root; this.path = path; }`);
    out.push(`  Object.defineProperties(${w.wrapper}.prototype, {`);
    for (const f of w.fields) {
      const resolve = `off(${S(f.declaringClass)},${S(f.rawName)})`;
      let getter: string;
      const kind = f.accessorKind;
      if (kind === "u64") {
        getter = `get: function () { var v = this.root.readUInt64Via(this.path, ${resolve}); return v === null ? null : v.toString(); }`;
      } else if (kind === "i64") {
        getter = `get: function () { var v = this.root.readInt64Via(this.path, ${resolve}); return v === null ? null : v.toString(); }`;
      } else if (VEC_INFO[kind]) {
        const vi = VEC_INFO[kind]!;
        getter = `get: function () { var a = this.root.readFloatsChain(this.path, ${resolve}, ${vi.count}); return a === null ? null : new ${vi.cls}(a[0], a[1], a[2]); }`;
      } else if (kind === "handle") {
        getter = `get: function () { return this.root.readHandleVia(this.path, ${resolve}); }`;
      } else {
        const method = READ_VIA[kind];
        if (!method) continue;  // unrecognised kind (should not happen with a well-formed model)
        getter = `get: function () { return this.root.${method}(this.path, ${resolve}); }`;
      }
      out.push(`    ${S(f.propName)}: { ${getter} },`);
    }
    out.push("  });");
  }

  // Build the NAV table: source class → array of nav entries.
  // The path array stores pre-computed off() calls (inlined literals) that resolve at module-load time.
  // applyNav checks at call time whether any pre-resolved offset is < 0 (field not found → null).
  const bySource = new Map<string, typeof model.wrappers>();
  for (const w of model.wrappers) {
    if (!bySource.has(w.source)) bySource.set(w.source, []);
    bySource.get(w.source)!.push(w);
  }

  out.push("  var NAV = {");
  for (const [src, wrappers] of [...bySource.entries()].sort((a, b) => a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0)) {
    out.push(`    ${S(src)}: [`);
    for (const w of wrappers) {
      // Inline off() calls in the path array — literals in the generated code, resolved at module load.
      const pathStr = w.path.map(h => `off(${S(h.cls)},${S(h.field)})`).join(", ");
      out.push(`      { prop: ${S(w.prop)}, wrapper: ${w.wrapper}, path: [${pathStr}] },`);
    }
    out.push("    ],");
  }
  out.push("  };");

  // applyNav: per source class, defines a getter per nav entry.
  // The getter validates that no pre-resolved offset is negative, then constructs the wrapper.
  out.push(
    "  function applyNav(proto, className) {",
    "    var entries = NAV[className]; if (!entries) return;",
    "    for (var i = 0; i < entries.length; i++) {",
    "      (function(entry) {",
    "        Object.defineProperty(proto, entry.prop, { get: function () {",
    "          for (var j = 0; j < entry.path.length; j++) { if (entry.path[j] < 0) return null; }",
    "          return new entry.wrapper(this.ref, entry.path);",
    "        }, enumerable: true, configurable: true });",
    "      })(entries[i]);",
    "    }",
    "  }",
    "  globalThis.__s2pkg_cs2_nav = { applyNav: applyNav };",
    "})();",
  );

  return out.join("\n");
}
