import type { SchemaModel } from "./model.ts";
import { TSTYPE } from "./model.ts";

const HEADER = "// GENERATED by `s2script gen-schema` from schema-catalog.json — DO NOT EDIT.";

export function emitDts(model: SchemaModel): string {
  const names = new Set(model.classes.map((c) => c.className));
  const out: string[] = [HEADER, 'import type { EntityRef } from "@s2script/entity";', ""];
  for (const c of model.classes) {
    const ext = c.parent && names.has(c.parent) ? ` extends ${c.parent}` : "";
    out.push(`export interface ${c.className}${ext} {`);
    for (const f of c.ownFields) {
      const ro = f.writable ? "" : "readonly ";
      out.push(`  ${ro}${f.propName}: ${TSTYPE[f.accessorKind]};`);
    }
    out.push("}", "");
  }
  return out.join("\n");
}
