import type { SchemaModel } from "./model.ts";
import { flattenedFields, READ, WRITE } from "./model.ts";

const HEADER = "// GENERATED by `s2script gen-schema` from schema-catalog.json — DO NOT EDIT.";
const S = JSON.stringify;

export function emitJs(model: SchemaModel): string {
  const out: string[] = [HEADER, "(function () {", "  var off = __s2_schema_offset;", "  var A = {};"];
  for (const c of model.classes) {
    out.push(`  A[${S(c.className)}] = {`);
    for (const f of flattenedFields(model, c.className)) {
      const resolve = `off(${S(f.declaringClass)},${S(f.rawName)})`;
      let entry = `get: function () { return this.ref.${READ[f.accessorKind]}(${resolve}); }`;
      if (f.writable) {
        const wm = WRITE[f.accessorKind]!;
        entry += `, set: function (v) { var o = ${resolve}; if (this.ref.${wm}(o, v)) this.ref.notifyStateChanged(o); }`;
      }
      out.push(`    ${S(f.propName)}: { ${entry} },`);
    }
    out.push("  };");
  }
  out.push(
    "  function applyAccessors(proto, className) {",
    "    var defs = A[className]; if (!defs) return;",
    "    for (var name in defs) {",
    "      Object.defineProperty(proto, name, { get: defs[name].get, set: defs[name].set, enumerable: true, configurable: true });",
    "    }",
    "  }",
    "  function wrap(className, ref) { var o = { ref: ref }; applyAccessors(o, className); return o; }",
    "  globalThis.__s2pkg_cs2_schema = { applyAccessors: applyAccessors, wrap: wrap };",
    "})();",
  );
  return out.join("\n");
}
