import type { ArgKind, PluginGamedata, RetKind } from "./types.ts";

const ARG_TS: Record<ArgKind, string> = {
  bool: "boolean", int: "number", float: "number",
  string: "string", vector: "readonly [number, number, number]",
  entity: "EntityRef | null",
};
const RET_TS: Record<RetKind, string> = {
  void: "void", bool: "boolean | null", int: "number | null",
  float: "number | null", entity: "EntityRef | null",
};

/** Emit `.s2script/gamedata.d.ts`. Deterministic: calls are sorted by name. */
export function generateGamedataTypes(gd: PluginGamedata): string {
  const calls = gd.calls ?? {};
  const lines = Object.keys(calls)
    .sort()
    .map((name) => {
      const decl = calls[name]!;
      const params = ["self: EntityRef", ...decl.args.map((a, i) => `a${i}: ${ARG_TS[a]}`)];
      return `    ${name}: (${params.join(", ")}) => ${RET_TS[decl.returns]};`;
    });

  const body = lines.length ? `\n${lines.join("\n")}\n  ` : "\n  ";
  return [
    "// GENERATED by `s2s build` from the plugin's gamedata — DO NOT EDIT.",
    "// The EntityRef import is REQUIRED: a `declare module` augmentation resolves type names in its",
    "// own file scope, so an un-imported EntityRef degrades to an error skipLibCheck can swallow.",
    'import type { EntityRef } from "@s2script/sdk/entity";',
    "",
    'declare module "@s2script/sdk/unsafe" {',
    `  interface EngineCalls {${body}}`,
    "}",
    "",
  ].join("\n");
}
