import type { ArgKind, PluginGamedata, RetKind } from "./types.ts";

// `vector` MUST be the structural {x,y,z} shape, NOT a tuple. Core marshals a vector arg by reading
// the `x`/`y`/`z` PROPERTIES off the JS value (core/src/v8host.rs, "vector" arm), each defaulting to
// 0.0 when absent. A tuple type therefore inverts the contract: passing a real `Vector` (which is
// {x,y,z}) would fail typecheck, while passing `[1,2,3]` would typecheck and silently hand the engine
// (0,0,0). This shape accepts Vector, QAngle, and plain object literals — everything core can read —
// and correctly rejects arrays.
const VECTOR_TS = "{ readonly x: number; readonly y: number; readonly z: number }";

const ARG_TS: Record<ArgKind, string> = {
  bool: "boolean", int: "number", float: "number",
  string: "string", vector: VECTOR_TS,
  entity: "EntityRef | null",
};
const RET_TS: Record<RetKind, string> = {
  void: "void", bool: "boolean | null", int: "number | null",
  float: "number | null", entity: "EntityRef | null",
};

/** Emit `.s2script/gamedata.d.ts`. Deterministic: calls are sorted by name. */
export function generateGamedataTypes(gd: PluginGamedata): string {
  const calls = gd.calls ?? {};
  const lines = Object.keys(calls)
    .sort()
    .map((name) => {
      const decl = calls[name]!;
      const params = ["self: EntityRef", ...decl.args.map((a, i) => `a${i}: ${ARG_TS[a]}`)];
      return `    ${name}: (${params.join(", ")}) => ${RET_TS[decl.returns]};`;
    });

  const body = lines.length ? `\n${lines.join("\n")}\n  ` : "\n  ";
  return [
    "// GENERATED by `s2s build` from the plugin's gamedata — DO NOT EDIT.",
    "// The EntityRef import is REQUIRED: a `declare module` augmentation resolves type names in its",
    "// own file scope, so an un-imported EntityRef degrades to an error skipLibCheck can swallow.",
    'import type { EntityRef } from "@s2script/sdk/entity";',
    "",
    'declare module "@s2script/sdk/unsafe" {',
    `  interface EngineCalls {${body}}`,
    "}",
    "",
  ].join("\n");
}
