// Pure emitter: hook model → hooks.generated.d.ts source text.
// No I/O, no Date/random — deterministic. Every name (view interface, ctx interface) is already
// fully derived in the model — this file only lays out text.

import type { CtxNamespace, GamedataHooks, HookDescriptor } from "./model.ts";
import { buildPluginHookList } from "./model.ts";

const HEADER =
  "// GENERATED by `s2script gen-hooks` from gamedata/cs2/game.cs2.jsonc's `hooks` — DO NOT EDIT.";

/** One hook's view interface: `mutable` params are writable (plain), everything else — including a
 *  surfaced receiver, which is never itself mutable — is `readonly`. Mirrors the hand-written
 *  `DamageInfo` view in `packages/sdk/damage.d.ts` (mutable `damage` is plain; the rest `readonly`). */
/**
 * Params that are TEXT rather than a number, keyed by shape and positional index.
 *
 * A descriptor's `params` list carries only NAMES — the types come from the shape, because the
 * shape is what fixes each slot's class in the shim. Every shape's params were scalars until
 * `this_i64_i64_i64` (the HUD-click receiver), whose one surfaced param is a `std::string` the
 * thunk copies into the arg view. Emitting that as `number` would typecheck and then hand a handler
 * a string at runtime, so the mapping lives here rather than being inferred.
 */
const STRING_PARAMS: Readonly<Record<string, ReadonlySet<number>>> = {
  this_i64_i64_i64: new Set([0]),
};

function emitViewIface(h: HookDescriptor): string[] {
  const out = [`export interface ${h.viewIface} {`];
  const strings = STRING_PARAMS[h.shape] ?? new Set<number>();
  h.params.forEach((p, i) => {
    const mod = p.mutable ? "" : "readonly ";
    out.push(`  ${mod}${p.name}: ${strings.has(i) ? "string" : "number"};`);
  });
  if (h.receiverAs !== null) {
    out.push(`  readonly ${h.receiverAs}: EntityRef | null;`);
  }
  out.push("}", "");
  return out;
}

/** Emit the full hooks.generated.d.ts source from a built model. */
export function emitHookDts(model: CtxNamespace[]): string {
  const out: string[] = [
    HEADER,
    'import type { HookResultValue } from "@s2script/sdk/events";',
    'import type { EntityRef } from "@s2script/sdk/entity";',
    "",
  ];

  for (const { hooks } of model) {
    for (const h of hooks) {
      out.push(...emitViewIface(h));
    }
  }

  for (const { ctxIface, hooks } of model) {
    out.push(`export interface ${ctxIface} {`);
    for (const h of hooks) {
      out.push(`  ${h.name}(handler: (view: ${h.viewIface}) => HookResultValue | void): void;`);
    }
    out.push("}", "");
  }

  out.push('declare module "@s2script/sdk/plugin" {');
  out.push("  interface PluginContext {");
  for (const { ns, ctxIface } of model) {
    out.push(`    readonly ${ns}: ${ctxIface};`);
  }
  out.push("  }");
  out.push("}");

  return out.join("\n") + "\n";
}

const PLUGIN_HEADER =
  "// GENERATED by `s2s build` from the plugin's gamedata — DO NOT EDIT.";

/** Emit `.s2script/hooks.d.ts`: per-hook views plus an `EngineHooks` augmentation of
 *  `@s2script/sdk/unsafe`. The subscribe factory is `Engine.hook(name)` — not a `ctx` namespace —
 *  so a plugin cannot clobber a built-in `ctx` member by picking an `expose.ctx` that collides. */
export function emitPluginHookDts(hooks: GamedataHooks): string {
  const list = buildPluginHookList(hooks);
  const out: string[] = [
    PLUGIN_HEADER,
    "// The EntityRef / HookResultValue imports are REQUIRED: a `declare module` augmentation",
    "// resolves type names in its own file scope.",
    'import type { HookResultValue } from "@s2script/sdk/events";',
    'import type { EntityRef } from "@s2script/sdk/entity";',
    "",
  ];
  for (const h of list) {
    out.push(...emitViewIface(h));
  }
  out.push('declare module "@s2script/sdk/unsafe" {');
  out.push("  interface EngineHooks {");
  for (const h of list) {
    out.push(`    ${h.name}: (handler: (view: ${h.viewIface}) => HookResultValue | void) => void;`);
  }
  out.push("  }");
  out.push("}");
  out.push("");
  return out.join("\n");
}
