// Pure emitter: hook model → hooks.generated.d.ts source text.
// No I/O, no Date/random — deterministic. Every name (view interface, ctx interface) is already
// fully derived in the model — this file only lays out text.

import type { CtxNamespace, HookDescriptor } from "./model.ts";

const HEADER =
  "// GENERATED by `s2script gen-hooks` from gamedata/cs2/game.cs2.jsonc's `hooks` — DO NOT EDIT.";

/** One hook's view interface: `mutable` params are writable (plain), everything else — including a
 *  surfaced receiver, which is never itself mutable — is `readonly`. Mirrors the hand-written
 *  `DamageInfo` view in `packages/sdk/damage.d.ts` (mutable `damage` is plain; the rest `readonly`). */
function emitViewIface(h: HookDescriptor): string[] {
  const out = [`export interface ${h.viewIface} {`];
  for (const p of h.params) {
    const mod = p.mutable ? "" : "readonly ";
    out.push(`  ${mod}${p.name}: number;`);
  }
  if (h.receiverAs !== null) {
    out.push(`  readonly ${h.receiverAs}: EntityRef | null;`);
  }
  out.push("}", "");
  return out;
}

/** Emit the full hooks.generated.d.ts source from a built model. */
export function emitHookDts(model: CtxNamespace[]): string {
  const out: string[] = [
    HEADER,
    'import type { HookResultValue } from "@s2script/sdk/events";',
    'import type { EntityRef } from "@s2script/sdk/entity";',
    "",
  ];

  for (const { hooks } of model) {
    for (const h of hooks) {
      out.push(...emitViewIface(h));
    }
  }

  for (const { ctxIface, hooks } of model) {
    out.push(`export interface ${ctxIface} {`);
    for (const h of hooks) {
      out.push(`  ${h.name}(handler: (view: ${h.viewIface}) => HookResultValue | void): void;`);
    }
    out.push("}", "");
  }

  out.push('declare module "@s2script/sdk/plugin" {');
  out.push("  interface PluginContext {");
  for (const { ns, ctxIface } of model) {
    out.push(`    readonly ${ns}: ${ctxIface};`);
  }
  out.push("  }");
  out.push("}");

  return out.join("\n") + "\n";
}
