// Generated by scripts/gen-engine-function-abi.py; do not edit.
export const PLATFORM = "linux-x86_64-sysv" as const;
export const RECEIVERS = ["none", "entity"] as const;
export const ATOM_WIDTHS = {"f32": 4, "f64": 8, "i32": 4, "i64": 8, "ptr": 8, "u32": 4, "u64": 8, "u8": 1} as const;
export const maxParameters = 32 as const;
export const maxCifArguments = 33 as const;
export const maxStackBytes = 256 as const;
export const stackSafetyBuffer = 128 as const;
export const gpRegisters = 6 as const;
export const sseRegisters = 8 as const;
