// GENERATED by `s2s build` from the plugin's gamedata — DO NOT EDIT.
// The EntityRef import is REQUIRED: a `declare module` augmentation resolves type names in its
// own file scope, so an un-imported EntityRef degrades to an error skipLibCheck can swallow.
import type { EntityRef } from "@s2script/sdk/entity";

declare module "@s2script/sdk/unsafe" {
  interface EngineCalls {
    dropActiveWeaponRejected: (self: EntityRef) => void;
    ignite: (self: EntityRef, flFlameLifetime: number, nFlags: number, pAttacker: EntityRef | null, flSize: number) => void;
  }
}
