#!/usr/bin/env node
// Extract the CS2 `CsItem` weapon/item-name constant map from CounterStrikeSharp's
// Modules/Entities/Constants/CsItem.cs enum.
//
// CS2's weapon/item entity names ("weapon_ak47", "item_kevlar", ...) are game CONTENT (stable
// across binary patches) — we borrow CSSharp's maintained CsItem enum rather than hand-typing
// ~90 strings. Only entries carrying their OWN [EnumMember(Value="...")] attribute are emitted
// (bare aliases like `KevlarHelmet = AssaultSuit,` reuse another member's numeric enum value, not
// a string — they're intentionally skipped; giveNamedItem() takes a string, and the primary name
// for that string is already emitted).
//
// Usage:  node scripts/extract-csitem.mjs <path-to-CSSharp-repo>
// Writes:
//   games/cs2/js/csitem.generated.js
//   packages/cs2/csitem.generated.d.ts
// Source ref: CounterStrikeSharp tag v1.0.363 (commit 75b68f2265be09eb09230de7632e70b1bcc40fde),
// https://github.com/roflmuffin/CounterStrikeSharp — recorded here + in
// docs/superpowers/specs/2026-07-09-items-design.md for reproducibility.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const cssharp = process.argv[2];
if (!cssharp) {
  console.error("usage: extract-csitem.mjs <CSSharp-repo-path>");
  process.exit(1);
}

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const srcPath = join(cssharp, "managed/CounterStrikeSharp.API/Modules/Entities/Constants/CsItem.cs");
const src = readFileSync(srcPath, "utf8");

// [EnumMember(Value = "weapon_ak47")]\n        AK47 = 400, / AK47,
const entries = {};
for (const m of src.matchAll(/\[EnumMember\(Value\s*=\s*"([^"]+)"\)\]\s*\n\s*([A-Za-z0-9_]+)/g)) {
  const [, value, name] = m;
  if (name in entries && entries[name] !== value) {
    console.error(`[extract-csitem] WARNING: duplicate name ${name} (${entries[name]} vs ${value}), keeping first`);
    continue;
  }
  entries[name] = value;
}

const names = Object.keys(entries).sort();
if (names.length === 0) {
  console.error("[extract-csitem] no entries extracted — check the source path/format");
  process.exit(1);
}

const jsLines = names.map((n) => `  ${n}: ${JSON.stringify(entries[n])}`).join(",\n");
const jsOut =
  "// GENERATED by scripts/extract-csitem.mjs from CounterStrikeSharp's CsItem.cs — DO NOT EDIT.\n" +
  "globalThis.__s2pkg_cs2 = globalThis.__s2pkg_cs2 || {};\n" +
  "globalThis.__s2pkg_cs2.CsItem = Object.freeze({\n" +
  jsLines +
  "\n});\n";

const dtsLines = names.map((n) => `  readonly ${n}: ${JSON.stringify(entries[n])};`).join("\n");
const dtsOut =
  "// GENERATED by scripts/extract-csitem.mjs from CounterStrikeSharp's CsItem.cs — DO NOT EDIT.\n" +
  "export declare const CsItem: {\n" +
  dtsLines +
  "\n};\n";

const jsPath = join(repoRoot, "games/cs2/js/csitem.generated.js");
const dtsPath = join(repoRoot, "packages/cs2/csitem.generated.d.ts");
mkdirSync(dirname(jsPath), { recursive: true });
mkdirSync(dirname(dtsPath), { recursive: true });
writeFileSync(jsPath, jsOut);
writeFileSync(dtsPath, dtsOut);

console.error(`[extract-csitem] ${names.length} item(s) extracted -> ${jsPath}, ${dtsPath}`);
