#!/usr/bin/env python3
"""Generate capability bounds only. No native prototype catalog is permitted."""
import argparse
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
p = argparse.ArgumentParser()
p.add_argument('--check', action='store_true')
args = p.parse_args()
spec = json.loads((root / 'shim/engine-function-abi.jsonc').read_text())
lines = ['// Generated by scripts/gen-engine-function-abi.py; do not edit.',
         'namespace capabilities {', f'inline constexpr char Platform[] = "{spec["platform"]}";']
for key in ('maxParameters', 'maxCifArguments', 'maxStackBytes', 'stackSafetyBuffer', 'gpRegisters', 'sseRegisters'):
    lines.append(f'inline constexpr std::size_t {key} = {spec[key]};')
lines += ['struct Atom { const char* name; std::size_t width; };', 'inline constexpr Atom atoms[] = {']
lines += [f'    {{"{name}", {width}}},' for name, width in spec['atoms'].items()]
lines += ['};', 'inline constexpr const char* receivers[] = {' + ', '.join(json.dumps(x) for x in spec['receivers']) + '};', '} // namespace capabilities', '']
out = root / 'shim/src/engine_function_abi.generated.inc'
text = '\n'.join(lines)
ts_out = root / 'packages/sdk/src/engine-functions/abi.generated.ts'
ts_lines = ['// Generated by scripts/gen-engine-function-abi.py; do not edit.',
            f'export const PLATFORM = {json.dumps(spec["platform"])} as const;',
            f'export const RECEIVERS = {json.dumps(spec["receivers"])} as const;',
            f'export const ATOM_WIDTHS = {json.dumps(spec["atoms"], sort_keys=True)} as const;']
for key in ('maxParameters', 'maxCifArguments', 'maxStackBytes', 'stackSafetyBuffer', 'gpRegisters', 'sseRegisters'):
    ts_lines.append(f'export const {key} = {spec[key]} as const;')
ts_text = '\n'.join(ts_lines) + '\n'
rust_out = root / 'core/src/engine_functions/abi.generated.rs'
rust_lines = ['// Generated by scripts/gen-engine-function-abi.py; do not edit.',
              f'pub const PLATFORM: &str = {json.dumps(spec["platform"])};',
              'pub const RECEIVERS: &[&str] = &[' + ', '.join(json.dumps(x) for x in spec['receivers']) + '];',
              'pub const ATOMS: &[(&str, usize)] = &[' + ', '.join(f'({json.dumps(k)}, {v})' for k, v in spec['atoms'].items()) + '];']
for key, name in [('maxParameters','MAX_PARAMETERS'), ('maxCifArguments','MAX_CIF_ARGUMENTS'), ('maxStackBytes','MAX_STACK_BYTES'), ('stackSafetyBuffer','STACK_SAFETY_BUFFER'), ('gpRegisters','GP_REGISTERS'), ('sseRegisters','SSE_REGISTERS')]:
    rust_lines.append(f'pub const {name}: usize = {spec[key]};')
rust_text = '\n'.join(rust_lines) + '\n'
if args.check:
    if not rust_out.exists() or rust_out.read_text() != rust_text:
        raise SystemExit('FAIL engine function Rust ABI capability artifact is stale')
    if not out.exists() or out.read_text() != text:
        raise SystemExit('FAIL engine function ABI capability artifact is stale')
    if not ts_out.exists() or ts_out.read_text() != ts_text:
        raise SystemExit('FAIL engine function TypeScript ABI capability artifact is stale')
    print('PASS engine function ABI capability freshness (bounds, no prototypes)')
else:
    out.write_text(text)
    ts_out.parent.mkdir(parents=True, exist_ok=True)
    ts_out.write_text(ts_text)

if not args.check:
    rust_out.parent.mkdir(parents=True, exist_ok=True)
    rust_out.write_text(rust_text)
