#!/usr/bin/env python3
"""Generate capability bounds only. No native prototype catalog is permitted."""
import argparse
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
p = argparse.ArgumentParser()
p.add_argument('--check', action='store_true')
args = p.parse_args()
spec = json.loads((root / 'shim/engine-function-abi.jsonc').read_text())
lines = ['// Generated by scripts/gen-engine-function-abi.py; do not edit.',
         'namespace capabilities {', f'inline constexpr char Platform[] = "{spec["platform"]}";']
for key in ('maxParameters', 'maxCifArguments', 'maxStackBytes', 'stackSafetyBuffer', 'gpRegisters', 'sseRegisters'):
    lines.append(f'inline constexpr std::size_t {key} = {spec[key]};')
lines += ['struct Atom { const char* name; std::size_t width; };', 'inline constexpr Atom atoms[] = {']
lines += [f'    {{"{name}", {width}}},' for name, width in spec['atoms'].items()]
lines += ['};', 'inline constexpr const char* receivers[] = {' + ', '.join(json.dumps(x) for x in spec['receivers']) + '};', '} // namespace capabilities', '']
out = root / 'shim/src/engine_function_abi.generated.inc'
text = '\n'.join(lines)
if args.check:
    if not out.exists() or out.read_text() != text:
        raise SystemExit('FAIL engine function ABI capability artifact is stale')
    print('PASS engine function ABI capability freshness (bounds, no prototypes)')
else:
    out.write_text(text)
