#!/usr/bin/env python3
"""Generate S2EngineOps from one declarative list (A7).

Source of truth: core/engine-ops.jsonc
Emits:
  core/src/engine_ops.generated.rs
  shim/include/s2script_engine_ops.generated.h
  shim/src/s2script_engine_ops_fill.generated.inc

`--check` regenerates to a temp dir and diffs against the committed copies.
`--extract` bootstraps the jsonc from the current handwritten declarations
(used once; the jsonc is the list after that).
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts" / "lib"))
from jsonc import strip_jsonc_comments  # noqa: E402

LIST = ROOT / "core" / "engine-ops.jsonc"
OUT_RS = ROOT / "core" / "src" / "engine_ops.generated.rs"
OUT_H = ROOT / "shim" / "include" / "s2script_engine_ops.generated.h"
OUT_INC = ROOT / "shim" / "src" / "s2script_engine_ops_fill.generated.inc"

BANNER_RS = """// @generated by scripts/gen-engine-ops.py from core/engine-ops.jsonc.
// DO NOT EDIT. Append a field to the list and re-run the script.
// Field ORDER is the ABI. This file is `include!`d into v8host.rs so the
// table stays one whole struct in the host (locked: do not split across modules).
"""

BANNER_H = """/* @generated by scripts/gen-engine-ops.py from core/engine-ops.jsonc.
 * DO NOT EDIT. Append a field to the list and re-run the script.
 * Field ORDER is the ABI. Included from s2script_core.h. */
"""

BANNER_INC = """/* @generated by scripts/gen-engine-ops.py from core/engine-ops.jsonc.
 * DO NOT EDIT. Included from s2script_mm.cpp's Load() ops assembly. */
"""


def load_list() -> dict:
    raw = LIST.read_text()
    return json.loads(strip_jsonc_comments(raw))


def emit_rs_clean(data: dict) -> str:
    out: list[str] = [BANNER_RS.rstrip(), ""]
    for h in data.get("helpers", []):
        if h.get("comment"):
            for c in h["comment"].splitlines():
                out.append(f"/// {c}" if c else "///")
        if h["kind"] == "fn":
            uns = "unsafe " if h.get("unsafe") else ""
            sig = h["rust"]
            out.append(f"pub type {h['name']} = {uns}{sig};")
        elif h["kind"] == "struct":
            out.append("#[repr(C)]")
            out.append("#[derive(Clone, Copy)]")
            out.append(f"pub struct {h['name']} {{")
            for f in h["rust_fields"]:
                out.append(f"    pub {f['name']}: {f['ty']},")
            out.append("}")
        out.append("")

    seen_aliases = {h["name"] for h in data.get("helpers", []) if h["kind"] == "fn"}
    for op in data["ops"]:
        if op["alias"] in seen_aliases:
            continue
        if op.get("alias_comment"):
            for c in op["alias_comment"].splitlines():
                out.append(f"/// {c}" if c else "///")
        uns = "unsafe " if op.get("unsafe") else ""
        out.append(f"pub type {op['alias']} = {uns}{op['rust']};")
        seen_aliases.add(op["alias"])
    out.append("")
    out.append("/// The C-ABI engine-ops table. Field ORDER is the ABI.")
    out.append("///")
    out.append("/// Generated from `core/engine-ops.jsonc`. Append-only across a release")
    out.append("/// boundary; a field may be deleted in the same zip (A5b). Do not reorder.")
    out.append("/// `Default` is all-None — test fixtures override the fields they need.")
    out.append("#[repr(C)]")
    out.append("#[derive(Clone, Copy, Default)]")
    out.append("pub struct S2EngineOps {")
    current_group = None
    for op in data["ops"]:
        group = op.get("group")
        if group and group != current_group:
            out.append(f"    // --- {group} ---")
            current_group = group
        line = f"    pub {op['name']}: Option<{op['alias']}>,"
        if op.get("note"):
            line += f" // {op['note']}"
        out.append(line)
    out.append("}")
    out.append("")
    out.append("impl S2EngineOps {")
    out.append("    /// Every field `None`. Test fixtures spread this and override what they wire.")
    out.append("    pub fn none() -> Self {")
    out.append("        Self::default()")
    out.append("    }")
    out.append("}")
    out.append("")
    return "\n".join(out)


def emit_h(data: dict) -> str:
    out: list[str] = [BANNER_H.rstrip(), ""]
    for h in data.get("helpers", []):
        if h.get("c_comment"):
            out.append(f"/* {h['c_comment']} */")
        if h["kind"] == "fn":
            out.append(f"typedef {h['c_ret']} (*{h['c_name']})({h['c_params']});")
        elif h["kind"] == "struct":
            out.append("typedef struct {")
            for f in h["c_fields"]:
                out.append(f"    {f['ty']} {f['name']};")
            out.append(f"}} {h['c_name']};")
        out.append("")

    seen = {h.get("c_name") for h in data.get("helpers", [])}
    for op in data["ops"]:
        c_name = f"s2_{op['name']}_fn"
        if c_name in seen:
            continue
        if op.get("c_comment"):
            out.append(f"/* {op['c_comment']} */")
        out.append(f"typedef {op['c_ret']} (*{c_name})({op['c_params']});")
        seen.add(c_name)
    out.append("")
    out.append("/* The C-ABI engine-ops table. Field ORDER is the ABI. Generated from")
    out.append(" * core/engine-ops.jsonc — must stay index-for-index with the Rust mirror. */")
    out.append("typedef struct {")
    current_group = None
    for op in data["ops"]:
        group = op.get("group")
        if group and group != current_group:
            out.append(f"    /* --- {group} --- */")
            current_group = group
        c_name = f"s2_{op['name']}_fn"
        out.append(f"    {c_name} {op['name']};")
    out.append("} S2EngineOps;")
    out.append("")
    return "\n".join(out)


def emit_inc(data: dict) -> str:
    out: list[str] = [BANNER_INC.rstrip(), ""]
    current_group = None
    for op in data["ops"]:
        shim = op.get("shim")
        if not shim:
            raise SystemExit(f"op {op['name']} has no shim= implementation symbol")
        group = op.get("group")
        if group and group != current_group:
            out.append(f"    // --- {group} ---")
            current_group = group
        out.append(f"    ops.{op['name']} = &{shim};")
    out.append("")
    return "\n".join(out)


def write_outputs(data: dict, dest_rs: Path, dest_h: Path, dest_inc: Path) -> None:
    dest_rs.write_text(emit_rs_clean(data))
    dest_h.write_text(emit_h(data))
    dest_inc.write_text(emit_inc(data))


def check() -> int:
    data = load_list()
    with tempfile.TemporaryDirectory() as td:
        t = Path(td)
        write_outputs(data, t / "rs", t / "h", t / "inc")
        bad = []
        for got, want, label in (
            (t / "rs", OUT_RS, OUT_RS.relative_to(ROOT)),
            (t / "h", OUT_H, OUT_H.relative_to(ROOT)),
            (t / "inc", OUT_INC, OUT_INC.relative_to(ROOT)),
        ):
            if not want.exists() or got.read_text() != want.read_text():
                bad.append(str(label))
        if bad:
            print("check-engine-ops-generated: FAIL — stale generated file(s):", file=sys.stderr)
            for b in bad:
                print(f"  {b}", file=sys.stderr)
            print("  Re-run: python3 scripts/gen-engine-ops.py", file=sys.stderr)
            return 1
    print(f"check-engine-ops-generated: OK — {len(data['ops'])} ops, three generated files match")
    return 0


# ---------------------------------------------------------------------------
# Extractor (bootstrap). Parses the handwritten declarations once.
# ---------------------------------------------------------------------------

def _balanced_from(src: str, open_idx: int) -> str:
    """src[open_idx] is '('; return the inside, exclusive of the matching ')'. """
    depth, i, n = 1, open_idx + 1, len(src)
    while i < n:
        ch = src[i]
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                return src[open_idx + 1 : i]
        i += 1
    raise SystemExit("unbalanced paren")


def extract() -> dict:
    rs = (ROOT / "core" / "src" / "v8host.rs").read_text()
    h = (ROOT / "shim" / "include" / "s2script_core.h").read_text()
    cpp = (ROOT / "shim" / "src" / "s2script_mm.cpp").read_text()

    # Rust fn aliases between SchemaOffsetFn and the struct.
    aliases: dict[str, dict] = {}
    for m in re.finditer(
        r'^(?:pub )?type (\w+)\s*=\s*(unsafe\s+)?extern "C" fn\(',
        rs,
        re.M,
    ):
        name = m.group(1)
        if name in ("LogFn", "HookRequestFn"):
            continue
        inside = _balanced_from(rs, m.end() - 1)
        after = rs[m.end() - 1 + 1 + len(inside) + 1 :]  # after the closing )
        ret_m = re.match(r"\s*(->\s*[^;]+)?;", after, re.S)
        ret = ""
        if ret_m and ret_m.group(1):
            ret = " " + ret_m.group(1).strip()
        rust_sig = f'extern "C" fn({_collapse_ws(inside)}){ret}'
        aliases[name] = {
            "unsafe": bool(m.group(2)),
            "rust": rust_sig,
        }

    # S2TraceResult
    tr = re.search(
        r"pub struct S2TraceResult \{\n(.*?)\n\}",
        rs,
        re.S,
    )
    rust_tr_fields = []
    if tr:
        for fm in re.finditer(r"pub (\w+):\s*([^,]+),", tr.group(1)):
            rust_tr_fields.append({"name": fm.group(1), "ty": fm.group(2).strip()})

    # Struct fields + groups
    sm = re.search(r"pub struct S2EngineOps \{(.*?)\n\}", rs, re.S)
    if not sm:
        raise SystemExit("no S2EngineOps in v8host.rs")
    ops = []
    current_group = None
    for line in sm.group(1).splitlines():
        gm = re.match(r"\s*// --- (.+?) ---", line)
        if gm:
            current_group = gm.group(1).strip()
            # strip historical "APPENDED after X; order is the ABI" noise to a short group
            current_group = re.sub(r"\s*\(.*", "", current_group)
            current_group = re.sub(r";.*", "", current_group)
            current_group = current_group.strip(" -")
            continue
        fm = re.match(r"\s*pub (\w+):\s*Option<(\w+)>\s*,\s*(?://\s*(.*))?", line)
        if not fm:
            continue
        name, alias, note = fm.group(1), fm.group(2), (fm.group(3) or "").strip()
        if alias not in aliases:
            raise SystemExit(f"field {name} alias {alias} has no rust type")
        op = {
            "name": name,
            "alias": alias,
            "rust": aliases[alias]["rust"],
            "group": current_group,
        }
        if aliases[alias]["unsafe"]:
            op["unsafe"] = True
        if note:
            op["note"] = note
        ops.append(op)

    # C typedefs
    c_fns: dict[str, dict] = {}
    for m in re.finditer(
        r"typedef\s+([\w\s*]+?)\s*\(\s*\*\s*(s2_\w+_fn)\s*\)\s*\(",
        h,
    ):
        c_ret = " ".join(m.group(1).split())
        c_name = m.group(2)
        params = _collapse_ws(_balanced_from(h, m.end() - 1))
        c_fns[c_name] = {"c_ret": c_ret, "c_params": params or "void"}

    # C S2TraceResult
    c_tr = re.search(r"typedef struct \{\n(.*?)\n\} S2TraceResult;", h, re.S)
    c_tr_fields = []
    if c_tr:
        for fm in re.finditer(r"^\s*(\S+(?:\s+\S+)*?)\s+(\w+);", c_tr.group(1), re.M):
            c_tr_fields.append({"ty": fm.group(1).strip(), "name": fm.group(2)})

    for op in ops:
        c_name = f"s2_{op['name']}_fn"
        if c_name not in c_fns:
            raise SystemExit(f"no C typedef {c_name}")
        op["c_ret"] = c_fns[c_name]["c_ret"]
        op["c_params"] = c_fns[c_name]["c_params"]

    # Shim assignments
    shim: dict[str, str] = {}
    for m in re.finditer(r"ops\.(\w+)\s*=\s*&(\w+)\s*;", cpp):
        shim[m.group(1)] = m.group(2)
    missing = [op["name"] for op in ops if op["name"] not in shim]
    if missing:
        raise SystemExit(f"shim fill missing: {missing}")
    extra = sorted(set(shim) - {op["name"] for op in ops} - {"duplicate_event"})
    # duplicate_event is a different struct
    for op in ops:
        op["shim"] = shim[op["name"]]

    helpers = [
        {
            "kind": "fn",
            "name": "EmitClassFn",
            "c_name": "s2_emit_class_fn",
            "rust": aliases["EmitClassFn"]["rust"],
            "c_ret": c_fns["s2_emit_class_fn"]["c_ret"],
            "c_params": c_fns["s2_emit_class_fn"]["c_params"],
            "comment": "Schema enumeration callbacks. Core provides these; the shim streams classes/fields.",
        },
        {
            "kind": "fn",
            "name": "EmitFieldFn",
            "c_name": "s2_emit_field_fn",
            "rust": aliases["EmitFieldFn"]["rust"],
            "c_ret": c_fns["s2_emit_field_fn"]["c_ret"],
            "c_params": c_fns["s2_emit_field_fn"]["c_params"],
        },
        {
            "kind": "fn",
            "name": "EmitEnumFn",
            "c_name": "s2_emit_enum_fn",
            "rust": aliases["EmitEnumFn"]["rust"],
            "c_ret": c_fns["s2_emit_enum_fn"]["c_ret"],
            "c_params": c_fns["s2_emit_enum_fn"]["c_params"],
        },
        {
            "kind": "struct",
            "name": "S2TraceResult",
            "c_name": "S2TraceResult",
            "rust_fields": rust_tr_fields,
            "c_fields": c_tr_fields,
            "comment": "TraceShape out-struct. Layout is the ABI; mirrors the C S2TraceResult.",
        },
    ]

    return {
        "_doc": "S2EngineOps source of truth. Order of `ops` IS the ABI. "
        "python3 scripts/gen-engine-ops.py  → rust + C header + shim fill. "
        "Do not replace this table with a runtime name-keyed map.",
        "helpers": helpers,
        "ops": ops,
    }


def _collapse_ws(s: str) -> str:
    return re.sub(r"\s+", " ", s).strip()


def dump_jsonc(data: dict) -> str:
    # Stable, reviewable. Keep `_doc` as a leading comment.
    doc = data.pop("_doc", "")
    body = json.dumps(data, indent=2, ensure_ascii=False)
    data["_doc"] = doc  # restore if reused
    lines = [
        "// S2EngineOps — one list, three generated copies (A7).",
        "// " + doc,
        "// Re-generate: python3 scripts/gen-engine-ops.py",
        body + "\n",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--extract", action="store_true", help="bootstrap jsonc from handwritten decls")
    args = ap.parse_args()
    if args.extract:
        data = extract()
        LIST.write_text(dump_jsonc(data))
        print(f"wrote {LIST.relative_to(ROOT)} ({len(data['ops'])} ops)")
        return 0
    if args.check:
        return check()
    data = load_list()
    write_outputs(data, OUT_RS, OUT_H, OUT_INC)
    print(
        f"generated {len(data['ops'])} ops → "
        f"{OUT_RS.relative_to(ROOT)}, {OUT_H.relative_to(ROOT)}, {OUT_INC.relative_to(ROOT)}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
