import type { SchemaModel } from "./model.ts";
import { flattenedFields, READ, WRITE, VEC_INFO } from "./model.ts";

const HEADER = "// GENERATED by `s2script gen-schema` from schema-catalog.json — DO NOT EDIT.";
const S = JSON.stringify;

export function emitJs(model: SchemaModel): string {
  const out: string[] = [HEADER, "(function () {", "  var off = __s2_schema_offset;", "  var A = {};"];
  const vecClasses = new Set<string>();
  for (const c of model.classes) for (const f of flattenedFields(model, c.className)) {
    const vi = VEC_INFO[f.accessorKind]; if (vi) vecClasses.add(vi.cls);
  }
  for (const cls of [...vecClasses].sort()) {
    out.push(`  var ${cls} = __s2require("@s2script/sdk/math").${cls};`);
  }
  for (const c of model.classes) {
    out.push(`  A[${S(c.className)}] = {`);
    for (const f of flattenedFields(model, c.className)) {
      const resolve = `off(${S(f.declaringClass)},${S(f.rawName)})`;
      let entry;
      if (f.accessorKind === "str") {
        entry = `get: function () { return this.ref.readString(${resolve}, ${f.strLen}); }`;
      } else if (f.accessorKind === "u64" || f.accessorKind === "i64") {
        // 64-bit ints -> decimal string (SM-parity, wire-safe); readUInt64/readInt64 are the bigint primitives.
        entry = `get: function () { var v = this.ref.${READ[f.accessorKind]}(${resolve}); return v === null ? null : v.toString(); }`;
      } else if (VEC_INFO[f.accessorKind]) {
        const vi = VEC_INFO[f.accessorKind]!;
        entry = `get: function () { var a = this.ref.readFloats(${resolve}, ${vi.count}); return a === null ? null : new ${vi.cls}(a[0], a[1], a[2]); }`;
      } else {
        entry = `get: function () { return this.ref.${READ[f.accessorKind]}(${resolve}); }`;
      }
      if (f.writable) {
        const wm = WRITE[f.accessorKind]!;
        entry += `, set: function (v) { var o = ${resolve}; if (this.ref.${wm}(o, v)) this.ref.notifyStateChanged(o); }`;
      }
      out.push(`    ${S(f.propName)}: { ${entry} },`);
    }
    out.push("  };");
  }
  out.push(
    "  function applyAccessors(proto, className) {",
    "    var defs = A[className]; if (!defs) return;",
    "    for (var name in defs) {",
    "      Object.defineProperty(proto, name, { get: defs[name].get, set: defs[name].set, enumerable: true, configurable: true });",
    "    }",
    "  }",
    "  function wrap(className, ref) { var o = { ref: ref }; applyAccessors(o, className); return o; }",
    "  globalThis.__s2pkg_cs2_schema = { applyAccessors: applyAccessors, wrap: wrap };",
    "})();",
  );
  return out.join("\n");
}
