import type { FieldDescriptor, SchemaModel } from "./model.ts";
import { TSTYPE, VEC_INFO } from "./model.ts";

const HEADER = "// GENERATED by `s2script gen-schema` from schema-catalog.json — DO NOT EDIT.";

export function emitDts(model: SchemaModel): string {
  // An enum field is declared as its enum type rather than `number`, so a stray integer is a compile
  // error. Falls back to the accessor type for an enum the dump did not describe.
  const enumTs = new Map(model.enums.map((e) => [e.className, e.tsName]));
  const tsType = (f: FieldDescriptor): string => {
    const id = f.enumType ? enumTs.get(f.enumType) : undefined;
    return id ? `${id} | null` : TSTYPE[f.accessorKind];
  };
  const names = new Set(model.classes.map((c) => c.className));
  const out: string[] = [HEADER, 'import type { EntityRef } from "@s2script/sdk/entity";'];
  const vecClasses = new Set<string>();
  for (const c of model.classes) for (const f of c.ownFields) {
    const vi = VEC_INFO[f.accessorKind]; if (vi) vecClasses.add(vi.cls);
  }
  for (const e of model.embedded) for (const f of e.fields) {
    const vi = VEC_INFO[f.accessorKind]; if (vi) vecClasses.add(vi.cls);
  }
  if (vecClasses.size) out.push(`import type { ${[...vecClasses].sort().join(", ")} } from "@s2script/sdk/math";`);
  out.push("");
  // Enum constants first: the field declarations below refer to these type names.
  //
  // A const object plus a value-union alias, rather than a TS `enum`. A `.d.ts` cannot declare a real
  // enum's runtime object without emitting code, and the union keeps assignment checked while still
  // accepting the plain integers the engine actually stores.
  for (const e of model.enums) {
    out.push(`export declare const ${e.tsName}: {`);
    for (const m of e.members) {
      const doc = m.name === m.raw ? "" : `  /** \`${m.raw}\` */\n`;
      out.push(`${doc}  readonly ${m.name}: ${m.value};`);
    }
    out.push("};");
    // Documented with the schema name when it differs, so a reader can find it in a dump.
    if (e.tsName !== e.className) out.push(`/** Schema enum \`${e.className}\`. */`);
    out.push(`export type ${e.tsName} = (typeof ${e.tsName})[keyof typeof ${e.tsName}];`, "");
  }
  // Embedded structs first: an entity interface below refers to these by name.
  for (const e of model.embedded) {
    out.push(`export interface ${e.className} {`);
    for (const f of e.fields) {
      out.push(`  ${f.writable ? "" : "readonly "}${f.propName}: ${tsType(f)};`);
    }
    for (const f of e.embeddedFields) out.push(`  readonly ${f.propName}: ${f.embeddedClass};`);
    out.push("}", "");
  }
  for (const c of model.classes) {
    const ext = c.parent && names.has(c.parent) ? ` extends ${c.parent}` : "";
    out.push(`export interface ${c.className}${ext} {`);
    for (const f of c.ownFields) {
      const ro = f.writable ? "" : "readonly ";
      out.push(`  ${ro}${f.propName}: ${tsType(f)};`);
    }
    // The accessor object itself is always readonly — you mutate its fields, not the binding.
    for (const f of c.embeddedFields) out.push(`  readonly ${f.propName}: ${f.embeddedClass};`);
    out.push("}", "");
  }

  // Entity classes only. An embedded struct is not independently addressable — it has no entity of
  // its own, only a base offset inside one — so it is reached through its owner, never wrapped.
  out.push("/** Every wrappable entity class, by schema name. */", "export interface SchemaClasses {");
  for (const c of model.classes) out.push(`  ${c.className}: ${c.className};`);
  out.push("}", "");
  out.push(
    "/**",
    " * Apply this schema class's field accessors to an entity reference.",
    " *",
    " * `createEntity` returns a bare `EntityRef` with no schema fields on it — this is how you get",
    " * them. `Player.pawn` is already wrapped; this is for entities you create or resolve yourself.",
    " *",
    " * The wrapper is a view, not a copy: it holds the ref and reads through it on every access, so",
    " * it stays correct as the entity changes and costs nothing to keep. Field reads return null",
    " * once the ref goes stale, exactly as they do on a pawn.",
    " *",
    " * @example",
    " * const prop = createEntity(\"prop_dynamic\");",
    " * prop.spawn();",
    " * const fields = wrapEntity(\"CBaseModelEntity\", prop);",
    " * fields.glow.glowing = true;",
    " */",
    "export declare function wrapEntity<K extends keyof SchemaClasses>(className: K, ref: EntityRef): SchemaClasses[K];",
    "",
  );
  return out.join("\n");
}
