import type { SchemaModel } from "./model.ts";
import type { FieldDescriptor } from "./model.ts";
import { READ, WRITE, VEC_INFO } from "./model.ts";

const HEADER = "// GENERATED by `s2script gen-schema` from schema-catalog.json — DO NOT EDIT.";
const S = JSON.stringify;

/**
 * One property descriptor. `resolve` is a JS expression yielding the ABSOLUTE byte offset, and
 * `guard` an expression that is true when that offset is unusable.
 *
 * Embedded structs need both to be parameterised: their offset is `base + fieldOffset`, and a
 * failed lookup returns the -1 sentinel — so `-1 + 8` would silently become a plausible-looking
 * offset 7 and read a neighbouring field. Hence an explicit guard rather than leaning on the
 * SDK's own bad-offset rejection, which only sees the summed value.
 */
/** Absolute-offset expression for a top-level field, including any flattened-wrapper delta. */
function resolveExpr(f: FieldDescriptor): string {
  const base = `off(${S(f.declaringClass)},${S(f.rawName)})`;
  return f.addOffset ? `${base} + ${f.addOffset}` : base;
}

function accessorEntry(f: FieldDescriptor, resolve: string, guard: string): string {
  // Keep the emitted text byte-identical to the un-guarded form when there is no guard, so adding
  // embedded support does not rewrite every line of the generated file.
  const g = guard === "" ? "" : `${guard} `;
  const gs = guard === "" ? "" : `${guard.replace("return null;", "return;")} `;
  let entry: string;
  if (f.accessorKind === "str") {
    entry = `get: function () { ${g}return this.ref.readString(${resolve}, ${f.strLen}); }`;
  } else if (f.accessorKind === "u64" || f.accessorKind === "i64") {
    // 64-bit ints -> decimal string (SM-parity, wire-safe); readUInt64/readInt64 are the bigint primitives.
    entry = `get: function () { ${g}var v = this.ref.${READ[f.accessorKind]}(${resolve}); return v === null ? null : v.toString(); }`;
  } else if (VEC_INFO[f.accessorKind]) {
    const vi = VEC_INFO[f.accessorKind]!;
    entry = `get: function () { ${g}var a = this.ref.readFloats(${resolve}, ${vi.count}); return a === null ? null : new ${vi.cls}(a[0], a[1], a[2]); }`;
  } else {
    entry = `get: function () { ${g}return this.ref.${READ[f.accessorKind]}(${resolve}); }`;
  }
  if (f.writable) {
    const wm = WRITE[f.accessorKind]!;
    entry += `, set: function (v) { ${gs}var o = ${resolve}; if (this.ref.${wm}(o, v)) this.ref.notifyStateChanged(o); }`;
  }
  return entry;
}

export function emitJs(model: SchemaModel): string {
  const out: string[] = [HEADER, "(function () {", "  var off = __s2_schema_offset;", "  var A = {};", "  var E = {};"];
  const vecClasses = new Set<string>();
  for (const c of model.classes) for (const f of c.ownFields) {
    const vi = VEC_INFO[f.accessorKind]; if (vi) vecClasses.add(vi.cls);
  }
  for (const cls of [...vecClasses].sort()) {
    out.push(`  var ${cls} = __s2require("@s2script/sdk/math").${cls};`);
  }
  for (const c of model.classes) {
    out.push(`  A[${S(c.className)}] = {`);
    for (const f of c.ownFields) {
      const entry = accessorEntry(f, resolveExpr(f), "");
      out.push(`    ${S(f.propName)}: { ${entry} },`);
    }
    for (const f of c.embeddedFields) {
      out.push(`    ${S(f.propName)}: { get: function () { return embed(${S(f.embeddedClass)}, this.ref, off(${S(f.declaringClass)},${S(f.rawName)})); } },`);
    }
    out.push("  };");
  }
  // Embedded struct accessors read at `this.base + <field offset within the struct>`.
  for (const e of model.embedded) {
    out.push(`  E[${S(e.className)}] = {`);
    for (const f of e.fields) {
      const sub = `off(${S(f.declaringClass)},${S(f.rawName)})`;
      const resolve = f.addOffset ? `this.base + ${sub} + ${f.addOffset}` : `this.base + ${sub}`;
      const guard = `if (this.base < 0 || ${sub} < 0) return null;`;
      out.push(`    ${S(f.propName)}: { ${accessorEntry(f, resolve, guard)} },`);
    }
    // A struct embedding a struct is the same (ref, base) pair one level down, so this is the
    // top-level emit with `this.base` folded into the new base rather than a separate mechanism.
    for (const f of e.embeddedFields) {
      const sub = `off(${S(f.declaringClass)},${S(f.rawName)})`;
      out.push(`    ${S(f.propName)}: { get: function () { var s = ${sub}; return embed(${S(f.embeddedClass)}, this.ref, (this.base < 0 || s < 0) ? -1 : this.base + s); } },`);
    }
    out.push("  };");
  }
  // Parent map: each table holds a class's OWN fields, and the chain is walked at apply time.
  out.push("  var P = {");
  for (const c of model.classes) if (c.parent) out.push(`    ${S(c.className)}: ${S(c.parent)},`);
  out.push("  };");
  out.push(
    "  // Walk the ancestor chain rather than storing every inherited accessor per class. Flattening",
    "  // into each table duplicated the whole chain 3.77x on the CS2 class set and grew as",
    "  // O(classes * depth), so every class added inflated every other one; this is O(total fields).",
    "  // Ancestors are applied FIRST so a derived class's own definition wins if a name repeats.",
    "  function applyAccessors(proto, className) {",
    "    var chain = [], c = className;",
    "    for (; c; c = P[c]) chain.unshift(c);",
    "    for (var i = 0; i < chain.length; i++) {",
    "      var defs = A[chain[i]]; if (!defs) continue;",
    "      for (var name in defs) {",
    "        Object.defineProperty(proto, name, { get: defs[name].get, set: defs[name].set, enumerable: true, configurable: true });",
    "      }",
    "    }",
    "  }",
    "  function wrap(className, ref) { var o = { ref: ref }; applyAccessors(o, className); return o; }",
    "  function embed(className, ref, base) {",
    "    var o = { ref: ref, base: base }, defs = E[className];",
    "    if (defs) for (var name in defs) {",
    "      Object.defineProperty(o, name, { get: defs[name].get, set: defs[name].set, enumerable: true, configurable: true });",
    "    }",
    "    return o;",
    "  }",
    "  globalThis.__s2pkg_cs2_schema = { applyAccessors: applyAccessors, wrap: wrap };",
    "  // Merge (not overwrite): this prelude runs FIRST, and pawn.js merges onto whatever it finds.",
    "  globalThis.__s2pkg_cs2 = Object.assign({}, globalThis.__s2pkg_cs2, { wrapEntity: wrap });",
    "})();",
  );
  return out.join("\n");
}
