// GENERATED by `s2script gen-events` from event-catalog.json — DO NOT EDIT.
import type { GameEvent, HookResultValue } from "@s2script/events";

export interface BombDefusedEvent extends GameEvent {
  getInt(key: "site"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface BombPlantedEvent extends GameEvent {
  getInt(key: "site"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface PlayerConnectFullEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface PlayerDeathEvent extends GameEvent {
  getBool(key: "attackerblind" | "headshot" | "noscope" | "thrusmoke"): boolean;
  getInt(key: "penetrated"): number;
  getPlayerSlot(key: "assister" | "attacker" | "userid"): number;
  getString(key: "weapon"): string;
}

export interface PlayerDisconnectEvent extends GameEvent {
  getInt(key: "reason"): number;
  getPlayerSlot(key: "userid"): number;
  getString(key: "name" | "networkid"): string;
}

export interface PlayerHurtEvent extends GameEvent {
  getInt(key: "armor" | "dmg_armor" | "dmg_health" | "health" | "hitgroup"): number;
  getPlayerSlot(key: "attacker" | "userid"): number;
  getString(key: "weapon"): string;
}

export interface PlayerSpawnEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface PlayerTeamEvent extends GameEvent {
  getBool(key: "disconnect"): boolean;
  getInt(key: "oldteam" | "team"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface RoundEndEvent extends GameEvent {
  getInt(key: "reason" | "winner"): number;
  getString(key: "message"): string;
}

export interface RoundFreezeEndEvent extends GameEvent {
}

export interface RoundStartEvent extends GameEvent {
  getInt(key: "fraglimit" | "timelimit"): number;
  getString(key: "objective"): string;
}

export interface WeaponFireEvent extends GameEvent {
  getBool(key: "silenced"): boolean;
  getPlayerSlot(key: "userid"): number;
  getString(key: "weapon"): string;
}

export interface GameEvents {
  bomb_defused: BombDefusedEvent;
  bomb_planted: BombPlantedEvent;
  player_connect_full: PlayerConnectFullEvent;
  player_death: PlayerDeathEvent;
  player_disconnect: PlayerDisconnectEvent;
  player_hurt: PlayerHurtEvent;
  player_spawn: PlayerSpawnEvent;
  player_team: PlayerTeamEvent;
  round_end: RoundEndEvent;
  round_freeze_end: RoundFreezeEndEvent;
  round_start: RoundStartEvent;
  weapon_fire: WeaponFireEvent;
}

export function on<K extends keyof GameEvents>(name: K, handler: (ev: GameEvents[K]) => void): void;
export function on(name: string, handler: (ev: GameEvent) => void): void;
export function onPre<K extends keyof GameEvents>(name: K, handler: (ev: GameEvents[K]) => HookResultValue | void): void;
export function onPre(name: string, handler: (ev: GameEvent) => HookResultValue | void): void;
export function fire<K extends keyof GameEvents>(name: K, fields?: Record<string, number | string | boolean | bigint>, dontBroadcast?: boolean): boolean;
export function fire(name: string, fields?: Record<string, number | string | boolean | bigint>, dontBroadcast?: boolean): boolean;
