// GENERATED by `s2script gen-events` from event-catalog.json — DO NOT EDIT.
import type { GameEvent, HookResultValue } from "@s2script/events";

export interface AchievementEarnedEvent extends GameEvent {
  getInt(key: "achievement"): number;
  getPlayerSlot(key: "player"): number;
}

export interface AchievementEarnedLocalEvent extends GameEvent {
  getInt(key: "achievement" | "splitscreenplayer"): number;
}

export interface AchievementEventEvent extends GameEvent {
  getInt(key: "cur_val" | "max_val"): number;
  getString(key: "achievement_name"): string;
}

export interface AchievementInfoLoadedEvent extends GameEvent {
}

export interface AchievementWriteFailedEvent extends GameEvent {
}

export interface AddBulletHitMarkerEvent extends GameEvent {
  getBool(key: "hit"): boolean;
  getInt(key: "ang_x" | "ang_y" | "ang_z" | "bone" | "pos_x" | "pos_y" | "pos_z" | "start_x" | "start_y" | "start_z"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface AddPlayerSonarIconEvent extends GameEvent {
  getFloat(key: "pos_x" | "pos_y" | "pos_z"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface AmmoPickupEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
  getString(key: "item"): string;
  getUint64(key: "index"): string;
}

export interface AmmoRefillEvent extends GameEvent {
  getBool(key: "success"): boolean;
  getPlayerSlot(key: "userid"): number;
}

export interface AnnouncePhaseEndEvent extends GameEvent {
}

export interface BeginNewMatchEvent extends GameEvent {
}

export interface BombAbortdefuseEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface BombAbortplantEvent extends GameEvent {
  getInt(key: "site"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface BombBeepEvent extends GameEvent {
  getUint64(key: "entindex"): string;
}

export interface BombBegindefuseEvent extends GameEvent {
  getBool(key: "haskit"): boolean;
  getPlayerSlot(key: "userid"): number;
}

export interface BombBeginplantEvent extends GameEvent {
  getInt(key: "site"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface BombDefusedEvent extends GameEvent {
  getInt(key: "site"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface BombDroppedEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
  getUint64(key: "entindex"): string;
}

export interface BombExplodedEvent extends GameEvent {
  getInt(key: "site"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface BombPickupEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface BombPlantedEvent extends GameEvent {
  getInt(key: "site"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface BonusUpdatedEvent extends GameEvent {
  getInt(key: "numadvanced" | "numbronze" | "numgold" | "numsilver"): number;
}

export interface BotTakeoverEvent extends GameEvent {
  getFloat(key: "p" | "r" | "y"): number;
  getPlayerSlot(key: "botid" | "userid"): number;
}

export interface BreakBreakableEvent extends GameEvent {
  getInt(key: "material"): number;
  getPlayerSlot(key: "userid"): number;
  getUint64(key: "entindex"): string;
}

export interface BreakPropEvent extends GameEvent {
  getBool(key: "player_dropped" | "player_held" | "player_thrown"): boolean;
  getPlayerSlot(key: "userid"): number;
  getUint64(key: "entindex"): string;
}

export interface BrokenBreakableEvent extends GameEvent {
  getInt(key: "material"): number;
  getPlayerSlot(key: "userid"): number;
  getUint64(key: "entindex"): string;
}

export interface BulletDamageEvent extends GameEvent {
  getBool(key: "in_air" | "no_scope"): boolean;
  getFloat(key: "aim_punch_x" | "aim_punch_y" | "aim_punch_z" | "attack_tick_frac" | "damage_dir_x" | "damage_dir_y" | "damage_dir_z" | "distance" | "inaccuracy_air" | "inaccuracy_move" | "inaccuracy_total" | "recoil_index" | "render_tick_frac" | "shoot_ang_x" | "shoot_ang_y" | "shoot_ang_z"): number;
  getInt(key: "attack_tick_count" | "num_penetrations" | "render_tick_count" | "type"): number;
  getPlayerSlot(key: "attacker" | "victim"): number;
}

export interface BulletImpactEvent extends GameEvent {
  getFloat(key: "x" | "y" | "z"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface BuymenuCloseEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface BuymenuOpenEvent extends GameEvent {
}

export interface BuytimeEndedEvent extends GameEvent {
}

export interface CartUpdatedEvent extends GameEvent {
}

export interface ChoppersIncomingWarningEvent extends GameEvent {
  getBool(key: "global"): boolean;
}

export interface ClientDisconnectEvent extends GameEvent {
}

export interface ClientLoadoutChangedEvent extends GameEvent {
}

export interface ClientsideLessonClosedEvent extends GameEvent {
  getString(key: "lesson_name"): string;
}

export interface ClientsideReloadCustomEconEvent extends GameEvent {
  getString(key: "steamid"): string;
}

export interface CsGameDisconnectedEvent extends GameEvent {
}

export interface CsIntermissionEvent extends GameEvent {
}

export interface CsMatchEndRestartEvent extends GameEvent {
}

export interface CsPreRestartEvent extends GameEvent {
}

export interface CsPrevNextSpectatorEvent extends GameEvent {
  getBool(key: "next"): boolean;
}

export interface CsRoundFinalBeepEvent extends GameEvent {
}

export interface CsRoundStartBeepEvent extends GameEvent {
}

export interface CsWinPanelMatchEvent extends GameEvent {
}

export interface CsWinPanelRoundEvent extends GameEvent {
  getBool(key: "show_timer_attack" | "show_timer_defend"): boolean;
  getInt(key: "final_event" | "timer_time"): number;
  getPlayerSlot(key: "funfact_player"): number;
  getString(key: "funfact_token"): string;
  getUint64(key: "funfact_data1" | "funfact_data2" | "funfact_data3"): string;
}

export interface DecoyDetonateEvent extends GameEvent {
  getFloat(key: "x" | "y" | "z"): number;
  getInt(key: "entityid"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface DecoyFiringEvent extends GameEvent {
  getFloat(key: "x" | "y" | "z"): number;
  getInt(key: "entityid"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface DecoyStartedEvent extends GameEvent {
  getFloat(key: "x" | "y" | "z"): number;
  getInt(key: "entityid"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface DefuserDroppedEvent extends GameEvent {
  getUint64(key: "entityid"): string;
}

export interface DefuserPickupEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
  getUint64(key: "entityid"): string;
}

export interface DemoSkipEvent extends GameEvent {
  getInt(key: "dota_hero_chase_list" | "local" | "user_message_list"): number;
  getUint64(key: "playback_tick" | "skipto_tick"): string;
}

export interface DemoStartEvent extends GameEvent {
  getInt(key: "dota_combatlog_list" | "dota_hero_chase_list" | "dota_pick_hero_list" | "local"): number;
}

export interface DemoStopEvent extends GameEvent {
}

export interface DifficultyChangedEvent extends GameEvent {
  getInt(key: "newDifficulty" | "oldDifficulty"): number;
  getString(key: "strDifficulty"): string;
}

export interface DmBonusWeaponStartEvent extends GameEvent {
  getInt(key: "Pos" | "time"): number;
}

export interface DoorBreakEvent extends GameEvent {
  getUint64(key: "dmgstate" | "entindex"): string;
}

export interface DoorCloseEvent extends GameEvent {
  getBool(key: "checkpoint"): boolean;
  getPlayerSlot(key: "userid"): number;
}

export interface DoorClosedEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
  getUint64(key: "entindex"): string;
}

export interface DoorMovingEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
  getUint64(key: "entindex"): string;
}

export interface DoorOpenEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
  getUint64(key: "entindex"): string;
}

export interface DroneAboveRoofEvent extends GameEvent {
  getInt(key: "cargo"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface DroneCargoDetachedEvent extends GameEvent {
  getBool(key: "delivered"): boolean;
  getInt(key: "cargo"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface DroneDispatchedEvent extends GameEvent {
  getInt(key: "drone_dispatched" | "priority"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface DronegunAttackEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface DropRateModifiedEvent extends GameEvent {
}

export interface DynamicShadowLightChangedEvent extends GameEvent {
}

export interface DzItemInteractionEvent extends GameEvent {
  getInt(key: "subject"): number;
  getPlayerSlot(key: "userid"): number;
  getString(key: "type"): string;
}

export interface EnableRestartVotingEvent extends GameEvent {
  getBool(key: "enable"): boolean;
}

export interface EndmatchCmmStartRevealItemsEvent extends GameEvent {
}

export interface EndmatchMapvoteSelectingMapEvent extends GameEvent {
  getInt(key: "count" | "slot1" | "slot10" | "slot2" | "slot3" | "slot4" | "slot5" | "slot6" | "slot7" | "slot8" | "slot9"): number;
}

export interface EnterBombzoneEvent extends GameEvent {
  getBool(key: "hasbomb" | "isplanted"): boolean;
  getPlayerSlot(key: "userid"): number;
}

export interface EnterBuyzoneEvent extends GameEvent {
  getBool(key: "canbuy"): boolean;
  getPlayerSlot(key: "userid"): number;
}

export interface EnterRescueZoneEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface EntityKilledEvent extends GameEvent {
  getUint64(key: "damagebits" | "entindex_attacker" | "entindex_inflictor" | "entindex_killed"): string;
}

export interface EntityVisibleEvent extends GameEvent {
  getInt(key: "subject"): number;
  getPlayerSlot(key: "userid"): number;
  getString(key: "classname" | "entityname"): string;
}

export interface EventTicketModifiedEvent extends GameEvent {
}

export interface ExitBombzoneEvent extends GameEvent {
  getBool(key: "hasbomb" | "isplanted"): boolean;
  getPlayerSlot(key: "userid"): number;
}

export interface ExitBuyzoneEvent extends GameEvent {
  getBool(key: "canbuy"): boolean;
  getPlayerSlot(key: "userid"): number;
}

export interface ExitRescueZoneEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface FinaleStartEvent extends GameEvent {
  getInt(key: "rushes"): number;
}

export interface FirstbombsIncomingWarningEvent extends GameEvent {
  getBool(key: "global"): boolean;
}

export interface FlareIgniteNpcEvent extends GameEvent {
  getUint64(key: "entindex"): string;
}

export interface FlashbangDetonateEvent extends GameEvent {
  getFloat(key: "x" | "y" | "z"): number;
  getInt(key: "entityid"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface GameEndEvent extends GameEvent {
  getInt(key: "winner"): number;
}

export interface GameInitEvent extends GameEvent {
}

export interface GameMessageEvent extends GameEvent {
  getInt(key: "target"): number;
  getString(key: "text"): string;
}

export interface GameNewmapEvent extends GameEvent {
  getBool(key: "transition"): boolean;
  getString(key: "mapname"): string;
}

export interface GamePhaseChangedEvent extends GameEvent {
  getInt(key: "new_phase"): number;
}

export interface GameStartEvent extends GameEvent {
  getString(key: "objective"): string;
  getUint64(key: "fraglimit" | "roundslimit" | "timelimit"): string;
}

export interface GameinstructorDrawEvent extends GameEvent {
}

export interface GameinstructorNodrawEvent extends GameEvent {
}

export interface GameuiHiddenEvent extends GameEvent {
}

export interface GcConnectedEvent extends GameEvent {
}

export interface GgKilledEnemyEvent extends GameEvent {
  getBool(key: "bonus"): boolean;
  getInt(key: "dominated" | "revenge"): number;
  getPlayerSlot(key: "attackerid" | "victimid"): number;
}

export interface GrenadeBounceEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface GrenadeThrownEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
  getString(key: "weapon"): string;
}

export interface GuardianWaveRestartEvent extends GameEvent {
}

export interface HegrenadeDetonateEvent extends GameEvent {
  getFloat(key: "x" | "y" | "z"): number;
  getInt(key: "entityid"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface HelicopterGrenadePuntMissEvent extends GameEvent {
}

export interface HideDeathpanelEvent extends GameEvent {
}

export interface HltvCameramanEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface HltvChangedModeEvent extends GameEvent {
  getUint64(key: "newmode" | "obs_target" | "oldmode"): string;
}

export interface HltvChaseEvent extends GameEvent {
  getInt(key: "distance" | "inertia" | "ineye" | "phi" | "theta"): number;
  getPlayerSlot(key: "target1" | "target2"): number;
}

export interface HltvChatEvent extends GameEvent {
  getString(key: "text"): string;
  getUint64(key: "steamID"): string;
}

export interface HltvFixedEvent extends GameEvent {
  getFloat(key: "fov"): number;
  getInt(key: "offset" | "phi" | "theta"): number;
  getPlayerSlot(key: "target"): number;
  getUint64(key: "posx" | "posy" | "posz"): string;
}

export interface HltvMessageEvent extends GameEvent {
  getString(key: "text"): string;
}

export interface HltvRankCameraEvent extends GameEvent {
  getFloat(key: "rank"): number;
  getInt(key: "index"): number;
  getPlayerSlot(key: "target"): number;
}

export interface HltvRankEntityEvent extends GameEvent {
  getFloat(key: "rank"): number;
  getPlayerSlot(key: "target" | "userid"): number;
}

export interface HltvReplayEvent extends GameEvent {
  getUint64(key: "delay" | "reason"): string;
}

export interface HltvReplayStatusEvent extends GameEvent {
  getUint64(key: "reason"): string;
}

export interface HltvStatusEvent extends GameEvent {
  getInt(key: "proxies"): number;
  getString(key: "master"): string;
  getUint64(key: "clients" | "slots"): string;
}

export interface HltvTitleEvent extends GameEvent {
  getString(key: "text"): string;
}

export interface HltvVersioninfoEvent extends GameEvent {
  getUint64(key: "version"): string;
}

export interface HostageCallForHelpEvent extends GameEvent {
  getInt(key: "hostage"): number;
}

export interface HostageFollowsEvent extends GameEvent {
  getInt(key: "hostage"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface HostageHurtEvent extends GameEvent {
  getInt(key: "hostage"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface HostageKilledEvent extends GameEvent {
  getInt(key: "hostage"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface HostageRescuedEvent extends GameEvent {
  getInt(key: "hostage" | "site"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface HostageRescuedAllEvent extends GameEvent {
}

export interface HostageStopsFollowingEvent extends GameEvent {
  getInt(key: "hostage"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface HostnameChangedEvent extends GameEvent {
  getString(key: "hostname"): string;
}

export interface InfernoExpireEvent extends GameEvent {
  getFloat(key: "x" | "y" | "z"): number;
  getInt(key: "entityid"): number;
}

export interface InfernoExtinguishEvent extends GameEvent {
  getFloat(key: "x" | "y" | "z"): number;
  getInt(key: "entityid"): number;
}

export interface InfernoStartburnEvent extends GameEvent {
  getFloat(key: "x" | "y" | "z"): number;
  getInt(key: "entityid"): number;
}

export interface InspectWeaponEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface InstructorCloseLessonEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
  getString(key: "hint_name"): string;
}

export interface InstructorServerHintCreateEvent extends GameEvent {
  getBool(key: "hint_allow_nodraw_target" | "hint_forcecaption" | "hint_local_player_only" | "hint_nooffscreen"): boolean;
  getFloat(key: "hint_icon_offset" | "hint_range" | "hint_vr_height_offset" | "hint_vr_offset_x" | "hint_vr_offset_y" | "hint_vr_offset_z"): number;
  getInt(key: "hint_timeout" | "hint_vr_panel_type"): number;
  getPlayerSlot(key: "hint_activator_userid" | "userid"): number;
  getString(key: "hint_activator_caption" | "hint_binding" | "hint_caption" | "hint_color" | "hint_gamepad_binding" | "hint_icon_offscreen" | "hint_icon_onscreen" | "hint_layoutfile" | "hint_name" | "hint_replace_key" | "hint_start_sound"): string;
  getUint64(key: "hint_entindex" | "hint_flags" | "hint_target"): string;
}

export interface InstructorServerHintStopEvent extends GameEvent {
  getString(key: "hint_name"): string;
  getUint64(key: "hint_entindex"): string;
}

export interface InstructorStartLessonEvent extends GameEvent {
  getBool(key: "vr_single_controller"): boolean;
  getInt(key: "vr_controller_type" | "vr_movement_type"): number;
  getPlayerSlot(key: "userid"): number;
  getString(key: "hint_name"): string;
  getUint64(key: "hint_target"): string;
}

export interface InventoryUpdatedEvent extends GameEvent {
  getInt(key: "itemdef"): number;
  getUint64(key: "itemid"): string;
}

export interface ItemEquipEvent extends GameEvent {
  getBool(key: "canzoom" | "hassilencer" | "hastracers" | "ispainted" | "issilenced"): boolean;
  getInt(key: "weptype"): number;
  getPlayerSlot(key: "userid"): number;
  getString(key: "item"): string;
  getUint64(key: "defindex"): string;
}

export interface ItemPickupEvent extends GameEvent {
  getBool(key: "silent"): boolean;
  getPlayerSlot(key: "userid"): number;
  getString(key: "item"): string;
  getUint64(key: "defindex"): string;
}

export interface ItemPickupFailedEvent extends GameEvent {
  getInt(key: "limit" | "reason"): number;
  getPlayerSlot(key: "userid"): number;
  getString(key: "item"): string;
}

export interface ItemPickupSlerpEvent extends GameEvent {
  getInt(key: "behavior" | "index"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface ItemPurchaseEvent extends GameEvent {
  getInt(key: "loadout" | "team"): number;
  getPlayerSlot(key: "userid"): number;
  getString(key: "weapon"): string;
}

export interface ItemRemoveEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
  getString(key: "item"): string;
  getUint64(key: "defindex"): string;
}

export interface ItemSchemaInitializedEvent extends GameEvent {
}

export interface JointeamFailedEvent extends GameEvent {
  getInt(key: "reason"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface LocalPlayerControllerTeamEvent extends GameEvent {
}

export interface LocalPlayerPawnChangedEvent extends GameEvent {
}

export interface LocalPlayerTeamEvent extends GameEvent {
}

export interface LootCrateOpenedEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
  getString(key: "type"): string;
}

export interface LootCrateVisibleEvent extends GameEvent {
  getInt(key: "subject"): number;
  getPlayerSlot(key: "userid"): number;
  getString(key: "type"): string;
}

export interface MapShutdownEvent extends GameEvent {
}

export interface MapTransitionEvent extends GameEvent {
}

export interface MatchEndConditionsEvent extends GameEvent {
  getUint64(key: "frags" | "max_rounds" | "time" | "win_rounds"): string;
}

export interface MaterialDefaultCompleteEvent extends GameEvent {
}

export interface MbInputLockCancelEvent extends GameEvent {
}

export interface MbInputLockSuccessEvent extends GameEvent {
}

export interface MolotovDetonateEvent extends GameEvent {
  getFloat(key: "x" | "y" | "z"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface NavBlockedEvent extends GameEvent {
  getBool(key: "blocked"): boolean;
  getUint64(key: "area"): string;
}

export interface NavGenerateEvent extends GameEvent {
}

export interface NextlevelChangedEvent extends GameEvent {
  getString(key: "mapgroup" | "nextlevel" | "skirmishmode"): string;
}

export interface OpenCrateInstrEvent extends GameEvent {
  getInt(key: "subject"): number;
  getPlayerSlot(key: "userid"): number;
  getString(key: "type"): string;
}

export interface OtherDeathEvent extends GameEvent {
  getBool(key: "attackerblind" | "headshot" | "noscope" | "thrusmoke"): boolean;
  getInt(key: "attacker" | "otherid" | "penetrated"): number;
  getString(key: "othertype" | "weapon" | "weapon_fauxitemid" | "weapon_itemid" | "weapon_originalowner_xuid"): string;
}

export interface ParachuteDeployEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface ParachutePickupEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface PhysgunPickupEvent extends GameEvent {
}

export interface PlayerActivateEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface PlayerAvengedTeammateEvent extends GameEvent {
  getPlayerSlot(key: "avenged_player_id" | "avenger_id"): number;
}

export interface PlayerBlindEvent extends GameEvent {
  getFloat(key: "blind_duration"): number;
  getInt(key: "entityid"): number;
  getPlayerSlot(key: "attacker" | "userid"): number;
}

export interface PlayerChangenameEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
  getString(key: "newname" | "oldname"): string;
}

export interface PlayerConnectEvent extends GameEvent {
  getBool(key: "bot"): boolean;
  getPlayerSlot(key: "userid"): number;
  getString(key: "name" | "networkid"): string;
  getUint64(key: "xuid"): string;
}

export interface PlayerConnectFullEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface PlayerDeathEvent extends GameEvent {
  getBool(key: "assistedflash" | "attackerblind" | "attackerinair" | "headshot" | "noreplay" | "noscope" | "thrusmoke"): boolean;
  getFloat(key: "distance"): number;
  getInt(key: "dmg_armor" | "dmg_health" | "dominated" | "hitgroup" | "penetrated" | "revenge" | "wipe"): number;
  getPlayerSlot(key: "assister" | "attacker" | "userid"): number;
  getString(key: "weapon" | "weapon_fauxitemid" | "weapon_itemid" | "weapon_originalowner_xuid"): string;
}

export interface PlayerDecalEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface PlayerDisconnectEvent extends GameEvent {
  getInt(key: "PlayerID" | "reason"): number;
  getPlayerSlot(key: "userid"): number;
  getString(key: "name" | "networkid"): string;
  getUint64(key: "xuid"): string;
}

export interface PlayerFalldamageEvent extends GameEvent {
  getFloat(key: "damage"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface PlayerFootstepEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface PlayerFullUpdateEvent extends GameEvent {
  getInt(key: "count"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface PlayerGivenC4Event extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface PlayerHintmessageEvent extends GameEvent {
  getString(key: "hintmessage"): string;
}

export interface PlayerHurtEvent extends GameEvent {
  getInt(key: "armor" | "dmg_armor" | "dmg_health" | "health" | "hitgroup"): number;
  getPlayerSlot(key: "attacker" | "userid"): number;
  getString(key: "weapon"): string;
}

export interface PlayerInfoEvent extends GameEvent {
  getBool(key: "bot"): boolean;
  getPlayerSlot(key: "userid"): number;
  getString(key: "name"): string;
  getUint64(key: "steamid"): string;
}

export interface PlayerJumpEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface PlayerPingEvent extends GameEvent {
  getBool(key: "urgent"): boolean;
  getFloat(key: "x" | "y" | "z"): number;
  getInt(key: "entityid"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface PlayerPingStopEvent extends GameEvent {
  getInt(key: "entityid"): number;
}

export interface PlayerRadioEvent extends GameEvent {
  getInt(key: "slot"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface PlayerResetVoteEvent extends GameEvent {
  getBool(key: "vote"): boolean;
  getPlayerSlot(key: "userid"): number;
}

export interface PlayerScoreEvent extends GameEvent {
  getInt(key: "deaths" | "kills" | "score"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface PlayerShootEvent extends GameEvent {
  getInt(key: "mode" | "weapon"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface PlayerSoundEvent extends GameEvent {
  getBool(key: "step"): boolean;
  getFloat(key: "duration"): number;
  getInt(key: "radius"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface PlayerSpawnEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface PlayerSpawnedEvent extends GameEvent {
  getBool(key: "inrestart"): boolean;
  getPlayerSlot(key: "userid"): number;
}

export interface PlayerStatsUpdatedEvent extends GameEvent {
  getBool(key: "forceupload"): boolean;
}

export interface PlayerTeamEvent extends GameEvent {
  getBool(key: "disconnect" | "isbot" | "silent"): boolean;
  getInt(key: "oldteam" | "team"): number;
  getPlayerSlot(key: "userid"): number;
  getString(key: "name"): string;
}

export interface RagdollDissolvedEvent extends GameEvent {
  getUint64(key: "entindex"): string;
}

export interface ReadGameTitledataEvent extends GameEvent {
  getInt(key: "controllerId"): number;
}

export interface RepostXboxAchievementsEvent extends GameEvent {
  getInt(key: "splitscreenplayer"): number;
}

export interface ResetGameTitledataEvent extends GameEvent {
  getInt(key: "controllerId"): number;
}

export interface RoundAnnounceFinalEvent extends GameEvent {
}

export interface RoundAnnounceLastRoundHalfEvent extends GameEvent {
}

export interface RoundAnnounceMatchPointEvent extends GameEvent {
}

export interface RoundAnnounceMatchStartEvent extends GameEvent {
}

export interface RoundAnnounceWarmupEvent extends GameEvent {
}

export interface RoundEndEvent extends GameEvent {
  getFloat(key: "time"): number;
  getInt(key: "legacy" | "nomusic" | "player_count" | "reason" | "winner"): number;
  getString(key: "message"): string;
}

export interface RoundEndUploadStatsEvent extends GameEvent {
}

export interface RoundFreezeEndEvent extends GameEvent {
}

export interface RoundMvpEvent extends GameEvent {
  getInt(key: "nomusic" | "reason"): number;
  getPlayerSlot(key: "userid"): number;
  getUint64(key: "musickitid" | "musickitmvps" | "value"): string;
}

export interface RoundOfficiallyEndedEvent extends GameEvent {
}

export interface RoundPoststartEvent extends GameEvent {
}

export interface RoundPrestartEvent extends GameEvent {
}

export interface RoundStartEvent extends GameEvent {
  getString(key: "objective"): string;
  getUint64(key: "fraglimit" | "timelimit"): string;
}

export interface RoundStartPostNavEvent extends GameEvent {
}

export interface RoundStartPreEntityEvent extends GameEvent {
}

export interface RoundTimeWarningEvent extends GameEvent {
}

export interface SeasoncoinLevelupEvent extends GameEvent {
  getInt(key: "category" | "rank"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface ServerCvarEvent extends GameEvent {
  getString(key: "cvarname" | "cvarvalue"): string;
}

export interface ServerMessageEvent extends GameEvent {
  getString(key: "text"): string;
}

export interface ServerPreShutdownEvent extends GameEvent {
  getString(key: "reason"): string;
}

export interface ServerShutdownEvent extends GameEvent {
  getString(key: "reason"): string;
}

export interface ServerSpawnEvent extends GameEvent {
  getBool(key: "dedicated" | "password"): boolean;
  getInt(key: "port"): number;
  getString(key: "addonname" | "address" | "game" | "hostname" | "mapname" | "os"): string;
  getUint64(key: "maxplayers"): string;
}

export interface SetInstructorGroupEnabledEvent extends GameEvent {
  getInt(key: "enabled"): number;
  getString(key: "group"): string;
}

export interface SfuieventEvent extends GameEvent {
  getInt(key: "slot"): number;
  getString(key: "action" | "data"): string;
}

export interface ShowDeathpanelEvent extends GameEvent {
  getInt(key: "damage_given" | "damage_taken" | "hits_given" | "hits_taken"): number;
  getPlayerSlot(key: "killer_controller" | "victim"): number;
}

export interface ShowSurvivalRespawnStatusEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
  getString(key: "loc_token"): string;
  getUint64(key: "duration"): string;
}

export interface SilencerDetachEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface SilencerOffEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface SilencerOnEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface SmokeBeaconParadropEvent extends GameEvent {
  getInt(key: "paradrop"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface SmokegrenadeDetonateEvent extends GameEvent {
  getFloat(key: "x" | "y" | "z"): number;
  getInt(key: "entityid"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface SmokegrenadeExpiredEvent extends GameEvent {
  getFloat(key: "x" | "y" | "z"): number;
  getInt(key: "entityid"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface SpecModeUpdatedEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface SpecTargetUpdatedEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface StartHalftimeEvent extends GameEvent {
}

export interface StartVoteEvent extends GameEvent {
  getInt(key: "type" | "vote_parameter"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface StorePricesheetUpdatedEvent extends GameEvent {
}

export interface SurvivalAnnouncePhaseEvent extends GameEvent {
  getInt(key: "phase"): number;
}

export interface SurvivalNoRespawnsFinalEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface SurvivalNoRespawnsWarningEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface SurvivalParadropBreakEvent extends GameEvent {
  getInt(key: "entityid"): number;
}

export interface SurvivalParadropSpawnEvent extends GameEvent {
  getInt(key: "entityid"): number;
}

export interface SurvivalTeammateRespawnEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface SwitchTeamEvent extends GameEvent {
  getInt(key: "avg_rank" | "numCTSlotsFree" | "numPlayers" | "numSpectators" | "numTSlotsFree"): number;
}

export interface TagrenadeDetonateEvent extends GameEvent {
  getFloat(key: "x" | "y" | "z"): number;
  getInt(key: "entityid"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface TeamInfoEvent extends GameEvent {
  getInt(key: "teamid"): number;
  getString(key: "teamname"): string;
}

export interface TeamIntroEndEvent extends GameEvent {
}

export interface TeamIntroStartEvent extends GameEvent {
}

export interface TeamScoreEvent extends GameEvent {
  getInt(key: "score" | "teamid"): number;
}

export interface TeamchangePendingEvent extends GameEvent {
  getInt(key: "toteam"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface TeamplayBroadcastAudioEvent extends GameEvent {
  getInt(key: "team"): number;
  getString(key: "sound"): string;
}

export interface TeamplayRoundStartEvent extends GameEvent {
  getBool(key: "full_reset"): boolean;
}

export interface TournamentRewardEvent extends GameEvent {
  getUint64(key: "accountid" | "defindex" | "totalrewards"): string;
}

export interface TrialTimeExpiredEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface UgcFileDownloadFinishedEvent extends GameEvent {
  getUint64(key: "hcontent"): string;
}

export interface UgcFileDownloadStartEvent extends GameEvent {
  getUint64(key: "hcontent" | "published_file_id"): string;
}

export interface UgcMapDownloadErrorEvent extends GameEvent {
  getUint64(key: "error_code" | "published_file_id"): string;
}

export interface UgcMapInfoReceivedEvent extends GameEvent {
  getUint64(key: "published_file_id"): string;
}

export interface UgcMapUnsubscribedEvent extends GameEvent {
  getUint64(key: "published_file_id"): string;
}

export interface UpdateMatchmakingStatsEvent extends GameEvent {
}

export interface UserDataDownloadedEvent extends GameEvent {
}

export interface VipEscapedEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface VipKilledEvent extends GameEvent {
  getPlayerSlot(key: "attacker" | "userid"): number;
}

export interface VoteCastEvent extends GameEvent {
  getInt(key: "team" | "vote_option"): number;
  getPlayerSlot(key: "userid"): number;
}

export interface VoteCastNoEvent extends GameEvent {
  getInt(key: "team"): number;
  getUint64(key: "entityid"): string;
}

export interface VoteCastYesEvent extends GameEvent {
  getInt(key: "team"): number;
  getUint64(key: "entityid"): string;
}

export interface VoteChangedEvent extends GameEvent {
  getInt(key: "noVotes" | "potentialVotes" | "vote_option1" | "vote_option2" | "vote_option3" | "vote_option4" | "vote_option5" | "yesVotes"): number;
}

export interface VoteEndedEvent extends GameEvent {
}

export interface VoteFailedEvent extends GameEvent {
  getInt(key: "reliable" | "team"): number;
}

export interface VoteOptionsEvent extends GameEvent {
  getInt(key: "count"): number;
  getString(key: "option1" | "option2" | "option3" | "option4" | "option5"): string;
}

export interface VotePassedEvent extends GameEvent {
  getInt(key: "reliable" | "team"): number;
  getString(key: "details" | "param1"): string;
}

export interface VoteStartedEvent extends GameEvent {
  getInt(key: "reliable" | "team"): number;
  getString(key: "issue" | "param1" | "votedata"): string;
  getUint64(key: "initiator"): string;
}

export interface WarmupEndEvent extends GameEvent {
}

export interface WeaponFireEvent extends GameEvent {
  getBool(key: "silenced"): boolean;
  getPlayerSlot(key: "userid"): number;
  getString(key: "weapon"): string;
}

export interface WeaponFireOnEmptyEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
  getString(key: "weapon"): string;
}

export interface WeaponReloadEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface WeaponZoomEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface WeaponZoomRifleEvent extends GameEvent {
  getPlayerSlot(key: "userid"): number;
}

export interface WeaponhudSelectionEvent extends GameEvent {
  getInt(key: "mode"): number;
  getPlayerSlot(key: "userid"): number;
  getUint64(key: "entindex"): string;
}

export interface WriteGameTitledataEvent extends GameEvent {
  getInt(key: "controllerId"): number;
}

export interface WriteProfileDataEvent extends GameEvent {
}

export interface GameEvents {
  achievement_earned: AchievementEarnedEvent;
  achievement_earned_local: AchievementEarnedLocalEvent;
  achievement_event: AchievementEventEvent;
  achievement_info_loaded: AchievementInfoLoadedEvent;
  achievement_write_failed: AchievementWriteFailedEvent;
  add_bullet_hit_marker: AddBulletHitMarkerEvent;
  add_player_sonar_icon: AddPlayerSonarIconEvent;
  ammo_pickup: AmmoPickupEvent;
  ammo_refill: AmmoRefillEvent;
  announce_phase_end: AnnouncePhaseEndEvent;
  begin_new_match: BeginNewMatchEvent;
  bomb_abortdefuse: BombAbortdefuseEvent;
  bomb_abortplant: BombAbortplantEvent;
  bomb_beep: BombBeepEvent;
  bomb_begindefuse: BombBegindefuseEvent;
  bomb_beginplant: BombBeginplantEvent;
  bomb_defused: BombDefusedEvent;
  bomb_dropped: BombDroppedEvent;
  bomb_exploded: BombExplodedEvent;
  bomb_pickup: BombPickupEvent;
  bomb_planted: BombPlantedEvent;
  bonus_updated: BonusUpdatedEvent;
  bot_takeover: BotTakeoverEvent;
  break_breakable: BreakBreakableEvent;
  break_prop: BreakPropEvent;
  broken_breakable: BrokenBreakableEvent;
  bullet_damage: BulletDamageEvent;
  bullet_impact: BulletImpactEvent;
  buymenu_close: BuymenuCloseEvent;
  buymenu_open: BuymenuOpenEvent;
  buytime_ended: BuytimeEndedEvent;
  cart_updated: CartUpdatedEvent;
  choppers_incoming_warning: ChoppersIncomingWarningEvent;
  client_disconnect: ClientDisconnectEvent;
  client_loadout_changed: ClientLoadoutChangedEvent;
  clientside_lesson_closed: ClientsideLessonClosedEvent;
  clientside_reload_custom_econ: ClientsideReloadCustomEconEvent;
  cs_game_disconnected: CsGameDisconnectedEvent;
  cs_intermission: CsIntermissionEvent;
  cs_match_end_restart: CsMatchEndRestartEvent;
  cs_pre_restart: CsPreRestartEvent;
  cs_prev_next_spectator: CsPrevNextSpectatorEvent;
  cs_round_final_beep: CsRoundFinalBeepEvent;
  cs_round_start_beep: CsRoundStartBeepEvent;
  cs_win_panel_match: CsWinPanelMatchEvent;
  cs_win_panel_round: CsWinPanelRoundEvent;
  decoy_detonate: DecoyDetonateEvent;
  decoy_firing: DecoyFiringEvent;
  decoy_started: DecoyStartedEvent;
  defuser_dropped: DefuserDroppedEvent;
  defuser_pickup: DefuserPickupEvent;
  demo_skip: DemoSkipEvent;
  demo_start: DemoStartEvent;
  demo_stop: DemoStopEvent;
  difficulty_changed: DifficultyChangedEvent;
  dm_bonus_weapon_start: DmBonusWeaponStartEvent;
  door_break: DoorBreakEvent;
  door_close: DoorCloseEvent;
  door_closed: DoorClosedEvent;
  door_moving: DoorMovingEvent;
  door_open: DoorOpenEvent;
  drone_above_roof: DroneAboveRoofEvent;
  drone_cargo_detached: DroneCargoDetachedEvent;
  drone_dispatched: DroneDispatchedEvent;
  dronegun_attack: DronegunAttackEvent;
  drop_rate_modified: DropRateModifiedEvent;
  dynamic_shadow_light_changed: DynamicShadowLightChangedEvent;
  dz_item_interaction: DzItemInteractionEvent;
  enable_restart_voting: EnableRestartVotingEvent;
  endmatch_cmm_start_reveal_items: EndmatchCmmStartRevealItemsEvent;
  endmatch_mapvote_selecting_map: EndmatchMapvoteSelectingMapEvent;
  enter_bombzone: EnterBombzoneEvent;
  enter_buyzone: EnterBuyzoneEvent;
  enter_rescue_zone: EnterRescueZoneEvent;
  entity_killed: EntityKilledEvent;
  entity_visible: EntityVisibleEvent;
  event_ticket_modified: EventTicketModifiedEvent;
  exit_bombzone: ExitBombzoneEvent;
  exit_buyzone: ExitBuyzoneEvent;
  exit_rescue_zone: ExitRescueZoneEvent;
  finale_start: FinaleStartEvent;
  firstbombs_incoming_warning: FirstbombsIncomingWarningEvent;
  flare_ignite_npc: FlareIgniteNpcEvent;
  flashbang_detonate: FlashbangDetonateEvent;
  game_end: GameEndEvent;
  game_init: GameInitEvent;
  game_message: GameMessageEvent;
  game_newmap: GameNewmapEvent;
  game_phase_changed: GamePhaseChangedEvent;
  game_start: GameStartEvent;
  gameinstructor_draw: GameinstructorDrawEvent;
  gameinstructor_nodraw: GameinstructorNodrawEvent;
  gameui_hidden: GameuiHiddenEvent;
  gc_connected: GcConnectedEvent;
  gg_killed_enemy: GgKilledEnemyEvent;
  grenade_bounce: GrenadeBounceEvent;
  grenade_thrown: GrenadeThrownEvent;
  guardian_wave_restart: GuardianWaveRestartEvent;
  hegrenade_detonate: HegrenadeDetonateEvent;
  helicopter_grenade_punt_miss: HelicopterGrenadePuntMissEvent;
  hide_deathpanel: HideDeathpanelEvent;
  hltv_cameraman: HltvCameramanEvent;
  hltv_changed_mode: HltvChangedModeEvent;
  hltv_chase: HltvChaseEvent;
  hltv_chat: HltvChatEvent;
  hltv_fixed: HltvFixedEvent;
  hltv_message: HltvMessageEvent;
  hltv_rank_camera: HltvRankCameraEvent;
  hltv_rank_entity: HltvRankEntityEvent;
  hltv_replay: HltvReplayEvent;
  hltv_replay_status: HltvReplayStatusEvent;
  hltv_status: HltvStatusEvent;
  hltv_title: HltvTitleEvent;
  hltv_versioninfo: HltvVersioninfoEvent;
  hostage_call_for_help: HostageCallForHelpEvent;
  hostage_follows: HostageFollowsEvent;
  hostage_hurt: HostageHurtEvent;
  hostage_killed: HostageKilledEvent;
  hostage_rescued: HostageRescuedEvent;
  hostage_rescued_all: HostageRescuedAllEvent;
  hostage_stops_following: HostageStopsFollowingEvent;
  hostname_changed: HostnameChangedEvent;
  inferno_expire: InfernoExpireEvent;
  inferno_extinguish: InfernoExtinguishEvent;
  inferno_startburn: InfernoStartburnEvent;
  inspect_weapon: InspectWeaponEvent;
  instructor_close_lesson: InstructorCloseLessonEvent;
  instructor_server_hint_create: InstructorServerHintCreateEvent;
  instructor_server_hint_stop: InstructorServerHintStopEvent;
  instructor_start_lesson: InstructorStartLessonEvent;
  inventory_updated: InventoryUpdatedEvent;
  item_equip: ItemEquipEvent;
  item_pickup: ItemPickupEvent;
  item_pickup_failed: ItemPickupFailedEvent;
  item_pickup_slerp: ItemPickupSlerpEvent;
  item_purchase: ItemPurchaseEvent;
  item_remove: ItemRemoveEvent;
  item_schema_initialized: ItemSchemaInitializedEvent;
  jointeam_failed: JointeamFailedEvent;
  local_player_controller_team: LocalPlayerControllerTeamEvent;
  local_player_pawn_changed: LocalPlayerPawnChangedEvent;
  local_player_team: LocalPlayerTeamEvent;
  loot_crate_opened: LootCrateOpenedEvent;
  loot_crate_visible: LootCrateVisibleEvent;
  map_shutdown: MapShutdownEvent;
  map_transition: MapTransitionEvent;
  match_end_conditions: MatchEndConditionsEvent;
  material_default_complete: MaterialDefaultCompleteEvent;
  mb_input_lock_cancel: MbInputLockCancelEvent;
  mb_input_lock_success: MbInputLockSuccessEvent;
  molotov_detonate: MolotovDetonateEvent;
  nav_blocked: NavBlockedEvent;
  nav_generate: NavGenerateEvent;
  nextlevel_changed: NextlevelChangedEvent;
  open_crate_instr: OpenCrateInstrEvent;
  other_death: OtherDeathEvent;
  parachute_deploy: ParachuteDeployEvent;
  parachute_pickup: ParachutePickupEvent;
  physgun_pickup: PhysgunPickupEvent;
  player_activate: PlayerActivateEvent;
  player_avenged_teammate: PlayerAvengedTeammateEvent;
  player_blind: PlayerBlindEvent;
  player_changename: PlayerChangenameEvent;
  player_connect: PlayerConnectEvent;
  player_connect_full: PlayerConnectFullEvent;
  player_death: PlayerDeathEvent;
  player_decal: PlayerDecalEvent;
  player_disconnect: PlayerDisconnectEvent;
  player_falldamage: PlayerFalldamageEvent;
  player_footstep: PlayerFootstepEvent;
  player_full_update: PlayerFullUpdateEvent;
  player_given_c4: PlayerGivenC4Event;
  player_hintmessage: PlayerHintmessageEvent;
  player_hurt: PlayerHurtEvent;
  player_info: PlayerInfoEvent;
  player_jump: PlayerJumpEvent;
  player_ping: PlayerPingEvent;
  player_ping_stop: PlayerPingStopEvent;
  player_radio: PlayerRadioEvent;
  player_reset_vote: PlayerResetVoteEvent;
  player_score: PlayerScoreEvent;
  player_shoot: PlayerShootEvent;
  player_sound: PlayerSoundEvent;
  player_spawn: PlayerSpawnEvent;
  player_spawned: PlayerSpawnedEvent;
  player_stats_updated: PlayerStatsUpdatedEvent;
  player_team: PlayerTeamEvent;
  ragdoll_dissolved: RagdollDissolvedEvent;
  read_game_titledata: ReadGameTitledataEvent;
  repost_xbox_achievements: RepostXboxAchievementsEvent;
  reset_game_titledata: ResetGameTitledataEvent;
  round_announce_final: RoundAnnounceFinalEvent;
  round_announce_last_round_half: RoundAnnounceLastRoundHalfEvent;
  round_announce_match_point: RoundAnnounceMatchPointEvent;
  round_announce_match_start: RoundAnnounceMatchStartEvent;
  round_announce_warmup: RoundAnnounceWarmupEvent;
  round_end: RoundEndEvent;
  round_end_upload_stats: RoundEndUploadStatsEvent;
  round_freeze_end: RoundFreezeEndEvent;
  round_mvp: RoundMvpEvent;
  round_officially_ended: RoundOfficiallyEndedEvent;
  round_poststart: RoundPoststartEvent;
  round_prestart: RoundPrestartEvent;
  round_start: RoundStartEvent;
  round_start_post_nav: RoundStartPostNavEvent;
  round_start_pre_entity: RoundStartPreEntityEvent;
  round_time_warning: RoundTimeWarningEvent;
  seasoncoin_levelup: SeasoncoinLevelupEvent;
  server_cvar: ServerCvarEvent;
  server_message: ServerMessageEvent;
  server_pre_shutdown: ServerPreShutdownEvent;
  server_shutdown: ServerShutdownEvent;
  server_spawn: ServerSpawnEvent;
  set_instructor_group_enabled: SetInstructorGroupEnabledEvent;
  sfuievent: SfuieventEvent;
  show_deathpanel: ShowDeathpanelEvent;
  show_survival_respawn_status: ShowSurvivalRespawnStatusEvent;
  silencer_detach: SilencerDetachEvent;
  silencer_off: SilencerOffEvent;
  silencer_on: SilencerOnEvent;
  smoke_beacon_paradrop: SmokeBeaconParadropEvent;
  smokegrenade_detonate: SmokegrenadeDetonateEvent;
  smokegrenade_expired: SmokegrenadeExpiredEvent;
  spec_mode_updated: SpecModeUpdatedEvent;
  spec_target_updated: SpecTargetUpdatedEvent;
  start_halftime: StartHalftimeEvent;
  start_vote: StartVoteEvent;
  store_pricesheet_updated: StorePricesheetUpdatedEvent;
  survival_announce_phase: SurvivalAnnouncePhaseEvent;
  survival_no_respawns_final: SurvivalNoRespawnsFinalEvent;
  survival_no_respawns_warning: SurvivalNoRespawnsWarningEvent;
  survival_paradrop_break: SurvivalParadropBreakEvent;
  survival_paradrop_spawn: SurvivalParadropSpawnEvent;
  survival_teammate_respawn: SurvivalTeammateRespawnEvent;
  switch_team: SwitchTeamEvent;
  tagrenade_detonate: TagrenadeDetonateEvent;
  team_info: TeamInfoEvent;
  team_intro_end: TeamIntroEndEvent;
  team_intro_start: TeamIntroStartEvent;
  team_score: TeamScoreEvent;
  teamchange_pending: TeamchangePendingEvent;
  teamplay_broadcast_audio: TeamplayBroadcastAudioEvent;
  teamplay_round_start: TeamplayRoundStartEvent;
  tournament_reward: TournamentRewardEvent;
  trial_time_expired: TrialTimeExpiredEvent;
  ugc_file_download_finished: UgcFileDownloadFinishedEvent;
  ugc_file_download_start: UgcFileDownloadStartEvent;
  ugc_map_download_error: UgcMapDownloadErrorEvent;
  ugc_map_info_received: UgcMapInfoReceivedEvent;
  ugc_map_unsubscribed: UgcMapUnsubscribedEvent;
  update_matchmaking_stats: UpdateMatchmakingStatsEvent;
  user_data_downloaded: UserDataDownloadedEvent;
  vip_escaped: VipEscapedEvent;
  vip_killed: VipKilledEvent;
  vote_cast: VoteCastEvent;
  vote_cast_no: VoteCastNoEvent;
  vote_cast_yes: VoteCastYesEvent;
  vote_changed: VoteChangedEvent;
  vote_ended: VoteEndedEvent;
  vote_failed: VoteFailedEvent;
  vote_options: VoteOptionsEvent;
  vote_passed: VotePassedEvent;
  vote_started: VoteStartedEvent;
  warmup_end: WarmupEndEvent;
  weapon_fire: WeaponFireEvent;
  weapon_fire_on_empty: WeaponFireOnEmptyEvent;
  weapon_reload: WeaponReloadEvent;
  weapon_zoom: WeaponZoomEvent;
  weapon_zoom_rifle: WeaponZoomRifleEvent;
  weaponhud_selection: WeaponhudSelectionEvent;
  write_game_titledata: WriteGameTitledataEvent;
  write_profile_data: WriteProfileDataEvent;
}

export function on<K extends keyof GameEvents>(name: K, handler: (ev: GameEvents[K]) => void): void;
export function on(name: string, handler: (ev: GameEvent) => void): void;
export function onPre<K extends keyof GameEvents>(name: K, handler: (ev: GameEvents[K]) => HookResultValue | void): void;
export function onPre(name: string, handler: (ev: GameEvent) => HookResultValue | void): void;
export function fire<K extends keyof GameEvents>(name: K, fields?: Record<string, number | string | boolean | bigint>, dontBroadcast?: boolean): boolean;
export function fire(name: string, fields?: Record<string, number | string | boolean | bigint>, dontBroadcast?: boolean): boolean;
