// GENERATED by `s2script gen-hooks` from gamedata/cs2/game.cs2.jsonc's `hooks` — DO NOT EDIT.
import type { HookResultValue } from "@s2script/sdk/events";
import type { EntityRef } from "@s2script/sdk/entity";

export interface OnTerminateRoundView {
  delay: number;
  reason: number;
}

export interface OnRespawnView {
  readonly player: EntityRef | null;
}

export interface CtxGameRules {
  onTerminateRound(handler: (view: OnTerminateRoundView) => HookResultValue | void): void;
}

export interface CtxPlayers {
  onRespawn(handler: (view: OnRespawnView) => HookResultValue | void): void;
}

declare module "@s2script/sdk/plugin" {
  interface PluginContext {
    readonly gameRules: CtxGameRules;
    readonly players: CtxPlayers;
  }
}
