// GENERATED by `s2script gen-nav` from nav-targets.json — DO NOT EDIT.
import type { Vector, QAngle } from "@s2script/math";
import type { EntityRef } from "@s2script/entity";

export interface AimPunchServices {
  readonly predictableBaseTickInterpAmount: number | null;
  readonly predictableBaseAngle: QAngle | null;
  readonly predictableBaseAngleVel: QAngle | null;
  readonly unpredictableBaseAngle: QAngle | null;
}

export interface MovementServices {
  readonly impulse: number | null;
  readonly queuedButtonDownMask: string | null;
  readonly queuedButtonChangeMask: string | null;
  readonly buttonDoublePressed: string | null;
  readonly lastCommandNumberProcessed: number | null;
  readonly toggleButtonDownMask: string | null;
  readonly cmdForwardMove: number | null;
  readonly cmdLeftMove: number | null;
  readonly cmdUpMove: number | null;
  readonly maxspeed: number | null;
  readonly forwardMove: number | null;
  readonly leftMove: number | null;
  readonly upMove: number | null;
  readonly lastMovementImpulses: Vector | null;
  readonly oldViewAngles: QAngle | null;
  readonly stepSoundTime: number | null;
  readonly fallVelocity: number | null;
  readonly groundNormal: Vector | null;
  readonly surfaceFriction: number | null;
  readonly stepside: number | null;
  readonly smoothedVelocity: Vector | null;
  readonly usingGroundTopologyOffset: boolean | null;
  readonly usingGroundTopologyOffsetTransitionSmoothing: number | null;
  readonly ladderNormal: Vector | null;
  readonly ladderSurfacePropIndex: number | null;
  readonly ducked: boolean | null;
  readonly duckAmount: number | null;
  readonly duckSpeed: number | null;
  readonly duckOverride: boolean | null;
  readonly desiresDuck: boolean | null;
  readonly ducking: boolean | null;
  readonly duckRootOffset: number | null;
  readonly duckViewOffset: number | null;
  readonly lastDuckTime: number | null;
  readonly bombPlantViewOffset: number | null;
  readonly duckUntilOnGround: boolean | null;
  readonly hasWalkMovedSinceLastJump: boolean | null;
  readonly inStuckTest: boolean | null;
  readonly traceCount: number | null;
  readonly stuckLast: number | null;
  readonly speedCropped: boolean | null;
  readonly oldWaterLevel: number | null;
  readonly waterEntryTime: number | null;
  readonly forward: Vector | null;
  readonly left: Vector | null;
  readonly up: Vector | null;
  readonly gameCodeHasMovedPlayerAfterCommand: number | null;
  readonly madeFootstepNoise: boolean | null;
  readonly footsteps: number | null;
  readonly buttonDownMaskPrev: string | null;
  readonly useFrictionStashedSpeed: boolean | null;
  readonly useFrictionStashedSpeedUntilFrac: number | null;
  readonly frictionStashedSpeed: number | null;
  readonly stamina: number | null;
  readonly heightAtJumpStart: number | null;
  readonly maxJumpHeightThisJump: number | null;
  readonly maxJumpHeightLastJump: number | null;
  readonly staminaAtJumpStart: number | null;
  readonly velMulAtJumpStart: number | null;
  readonly accumulatedJumpError: number | null;
  readonly lastJumpFrac: number | null;
  readonly lastJumpVelocityZ: number | null;
  readonly jumpApexPending: boolean | null;
  readonly ticksSinceLastSurfingDetected: number | null;
  readonly wasSurfing: boolean | null;
  readonly hasEverProcessedCommand: boolean | null;
}

export interface SceneNode {
  readonly rotation: QAngle | null;
  readonly scale: number | null;
  readonly absOrigin: Vector | null;
  readonly absRotation: QAngle | null;
  readonly absScale: number | null;
  readonly parentAttachmentOrBone: number | null;
  readonly debugAbsOriginChanges: boolean | null;
  readonly dormant: boolean | null;
  readonly forceParentToBeNetworked: boolean | null;
  readonly hierarchicalDepth: number | null;
  readonly hierarchyType: number | null;
  readonly doNotSetAnimTimeInInvalidatePhysicsCount: number | null;
  readonly clientLocalScale: number | null;
  readonly renderOrigin: Vector | null;
}

export interface WeaponServices {
  readonly activeWeapon: EntityRef | null;
  readonly lastWeapon: EntityRef | null;
  readonly preventWeaponPickup: boolean | null;
  readonly savedWeapon: EntityRef | null;
  readonly timeToMelee: number | null;
  readonly timeToSecondary: number | null;
  readonly timeToPrimary: number | null;
  readonly timeToSniperRifle: number | null;
  readonly isBeingGivenItem: boolean | null;
  readonly isPickingUpItemWithUse: boolean | null;
  readonly pickedUpWeapon: boolean | null;
  readonly disableAutoDeploy: boolean | null;
  readonly isPickingUpGroundWeapon: boolean | null;
  readonly blockInspectUntilNextGraphUpdate: boolean | null;
}
