// GENERATED by `s2script gen-schema` from schema-catalog.json — DO NOT EDIT.
import type { EntityRef } from "@s2script/sdk/entity";
import type { QAngle, Vector } from "@s2script/sdk/math";

export interface CAnimGraphControllerManager {
  graphBindingsCreated: boolean | null;
}

export interface CAttributeContainer {
  reapplyProvisionParity: number | null;
  readonly outer: EntityRef | null;
  preventLoopback: boolean | null;
  readonly item: CEconItemView;
}

export interface CAttributeList {
}

export interface CCollisionProperty {
  readonly mins: Vector | null;
  readonly maxs: Vector | null;
  usSolidFlags: number | null;
  triggerBloat: number | null;
  collisionGroup: number | null;
  enablePhysics: number | null;
  boundingRadius: number | null;
  readonly specifiedSurroundingMins: Vector | null;
  readonly specifiedSurroundingMaxs: Vector | null;
  readonly surroundingMaxs: Vector | null;
  readonly surroundingMins: Vector | null;
  readonly capsuleCenter1: Vector | null;
  readonly capsuleCenter2: Vector | null;
  capsuleRadius: number | null;
  readonly collisionAttribute: VPhysicsCollisionAttribute_t;
}

export interface CEconItemView {
  itemDefinitionIndex: number | null;
  entityQuality: number | null;
  entityLevel: number | null;
  readonly itemID: string | null;
  itemIDHigh: number | null;
  itemIDLow: number | null;
  accountID: number | null;
  inventoryPosition: number | null;
  initialized: boolean | null;
  readonly customName: string | null;
  readonly customNameOverride: string | null;
  readonly attributeList: CAttributeList;
  readonly networkedDynamicAttributes: CAttributeList;
}

export interface CEntityIOOutput {
}

export interface CGlowProperty {
  readonly glowColor: Vector | null;
  glowType: number | null;
  glowTeam: number | null;
  glowRange: number | null;
  glowRangeMin: number | null;
  glowColorOverride: number | null;
  flashing: boolean | null;
  glowTime: number | null;
  glowStartTime: number | null;
  eligibleForScreenHighlight: boolean | null;
  glowing: boolean | null;
}

export interface CHitboxComponent {
  boundsExpandRadius: number | null;
}

export interface CIronSightController {
  ironSightAvailable: boolean | null;
  ironSightAmount: number | null;
  ironSightAmountGained: number | null;
  ironSightAmountBiased: number | null;
}

export interface CMovementStatsProperty {
  useCounter: number | null;
  readonly emaMovementDirection: CVectorExponentialMovingAverage;
}

export interface CNetworkTransmitComponent {
  transmitStateOwnedCounter: number | null;
}

export interface CNetworkVelocityVector {
}

export interface CNetworkViewOffsetVector {
}

export interface CTouchExpansionComponent {
}

export interface CVectorExponentialMovingAverage {
}

export interface EntitySpottedState_t {
  spotted: boolean | null;
}

export interface IntervalTimer {
  timestamp: number | null;
}

export interface PhysicsRagdollPose_t {
  readonly owner: EntityRef | null;
  setFromDebugHistory: boolean | null;
}

export interface VPhysicsCollisionAttribute_t {
  readonly interactsAs: string | null;
  readonly interactsWith: string | null;
  readonly interactsExclude: string | null;
  entityId: number | null;
  ownerId: number | null;
  hierarchyId: number | null;
  detailLayerMask: number | null;
  detailLayerMaskType: number | null;
  targetDetailLayer: number | null;
  collisionGroup: number | null;
  collisionFunctionMask: number | null;
}

export interface fogparams_t {
  readonly dirPrimary: Vector | null;
  colorPrimary: number | null;
  colorSecondary: number | null;
  colorPrimaryLerpTo: number | null;
  colorSecondaryLerpTo: number | null;
  start: number | null;
  end: number | null;
  farz: number | null;
  maxdensity: number | null;
  exponent: number | null;
  hDRColorScale: number | null;
  skyboxFogFactor: number | null;
  skyboxFogFactorLerpTo: number | null;
  startLerpTo: number | null;
  endLerpTo: number | null;
  maxdensityLerpTo: number | null;
  lerptime: number | null;
  duration: number | null;
  blendtobackground: number | null;
  scattering: number | null;
  locallightscale: number | null;
  enable: boolean | null;
  blend: boolean | null;
  padding2: boolean | null;
  padding: boolean | null;
}

export interface sky3dparams_t {
  scale: number | null;
  readonly origin: Vector | null;
  clip3DSkyBoxNearToWorldFar: boolean | null;
  clip3DSkyBoxNearToWorldFarOffset: number | null;
  readonly fog: fogparams_t;
}

export interface CEntityInstance {
}

export interface CBaseEntity extends CEntityInstance {
  currentThinkContext: number | null;
  lastThinkTick: number | null;
  disabledContextThinks: boolean | null;
  lastNetworkChange: number | null;
  health: number | null;
  maxHealth: number | null;
  lifeState: number | null;
  damageAccumulator: number | null;
  takesDamage: boolean | null;
  waterTouch: number | null;
  slimeTouch: number | null;
  restoreInHierarchy: boolean | null;
  readonly damageFilter: EntityRef | null;
  moveDoneTime: number | null;
  animTime: number | null;
  simulationTime: number | null;
  createTime: number | null;
  clientSideRagdoll: boolean | null;
  ubInterpolationFrame: number | null;
  readonly prevVPhysicsUpdatePos: Vector | null;
  teamNum: number | null;
  sentToClients: number | null;
  speed: number | null;
  spawnflags: number | null;
  nextThinkTick: number | null;
  simulationTick: number | null;
  flags: number | null;
  readonly absVelocity: Vector | null;
  readonly baseVelocity: Vector | null;
  pushEnumCount: number | null;
  readonly effectEntity: EntityRef | null;
  readonly ownerEntity: EntityRef | null;
  effects: number | null;
  readonly groundEntity: EntityRef | null;
  groundBodyIndex: number | null;
  friction: number | null;
  elasticity: number | null;
  gravityScale: number | null;
  timeScale: number | null;
  waterLevel: number | null;
  gravityDisabled: boolean | null;
  animatedEveryTick: boolean | null;
  actualGravityScale: number | null;
  gravityActuallyDisabled: boolean | null;
  disableLowViolence: boolean | null;
  waterType: number | null;
  eFlags: number | null;
  initialTeamNum: number | null;
  navIgnoreUntilTime: number | null;
  readonly angVelocity: QAngle | null;
  networkQuantizeOriginAndAngles: boolean | null;
  lagCompensate: boolean | null;
  readonly blocker: EntityRef | null;
  localTime: number | null;
  vPhysicsUpdateLocalTime: number | null;
  readonly networkTransmitComponent: CNetworkTransmitComponent;
  readonly onKilled: CEntityIOOutput;
  readonly velocity: CNetworkVelocityVector;
  readonly onUser1: CEntityIOOutput;
  readonly onUser2: CEntityIOOutput;
  readonly onUser3: CEntityIOOutput;
  readonly onUser4: CEntityIOOutput;
}

export interface CBaseModelEntity extends CBaseEntity {
  destructiblePartInitialStateDestructed0_PartIndex: number | null;
  destructiblePartInitialStateDestructed1_PartIndex: number | null;
  destructiblePartInitialStateDestructed2_PartIndex: number | null;
  destructiblePartInitialStateDestructed3_PartIndex: number | null;
  destructiblePartInitialStateDestructed4_PartIndex: number | null;
  destructiblePartInitialStateDestructed0_GenerateBreakpieces: boolean | null;
  destructiblePartInitialStateDestructed1_GenerateBreakpieces: boolean | null;
  destructiblePartInitialStateDestructed2_GenerateBreakpieces: boolean | null;
  destructiblePartInitialStateDestructed3_GenerateBreakpieces: boolean | null;
  destructiblePartInitialStateDestructed4_GenerateBreakpieces: boolean | null;
  dissolveStartTime: number | null;
  allowFadeInView: boolean | null;
  render: number | null;
  renderToCubemaps: boolean | null;
  noInterpolate: boolean | null;
  glowBackfaceMult: number | null;
  fadeMinDist: number | null;
  fadeMaxDist: number | null;
  fadeScale: number | null;
  shadowStrength: number | null;
  objectCulling: number | null;
  readonly cHitboxComponent: CHitboxComponent;
  readonly onIgnite: CEntityIOOutput;
  readonly collision: CCollisionProperty;
  readonly glow: CGlowProperty;
  readonly viewOffset: CNetworkViewOffsetVector;
}

export interface CBasePlayerController extends CBaseEntity {
  readonly inButtonsWhichAreToggles: string | null;
  tickBase: number | null;
  readonly pawn: EntityRef | null;
  knownTeamMismatch: boolean | null;
  readonly splitOwner: EntityRef | null;
  isHLTV: boolean | null;
  readonly playerName: string | null;
  lerpTime: number | null;
  lagCompensation: boolean | null;
  predict: boolean | null;
  isLowViolence: boolean | null;
  gamePaused: boolean | null;
  lastPlayerTalkTime: number | null;
  lastEntitySteadyState: number | null;
  availableEntitySteadyState: number | null;
  hasAnySteadyStateEnts: boolean | null;
  readonly steamID: string | null;
  noClipEnabled: boolean | null;
  desiredFOV: number | null;
}

export interface CBaseAnimGraph extends CBaseModelEntity {
  initiallyPopulateInterpHistory: boolean | null;
  animGraphUpdateEnabled: boolean | null;
  animationUpdateScheduled: boolean | null;
  readonly force: Vector | null;
  forceBone: number | null;
  ragdollEnabled: boolean | null;
  ragdollClientSide: boolean | null;
  readonly graphControllerManager: CAnimGraphControllerManager;
  readonly ragdollPose: PhysicsRagdollPose_t;
}

export interface CCSPlayerController extends CBasePlayerController {
  ping: number | null;
  hasCommunicationAbuseMute: boolean | null;
  uiCommunicationMuteFlags: number | null;
  pendingTeamNum: number | null;
  forceTeamTime: number | null;
  compTeammateColor: number | null;
  everPlayedOnTeam: boolean | null;
  attemptedToGetColor: boolean | null;
  teammatePreferredColor: number | null;
  teamChanged: boolean | null;
  inSwitchTeam: boolean | null;
  hasSeenJoinGame: boolean | null;
  justBecameSpectator: boolean | null;
  switchTeamsOnNextRoundReset: boolean | null;
  removeAllItemsOnNextRoundReset: boolean | null;
  lastJoinTeamTime: number | null;
  coachingTeam: number | null;
  readonly playerDominated: string | null;
  readonly playerDominatingMe: string | null;
  competitiveRanking: number | null;
  competitiveWins: number | null;
  competitiveRankType: number | null;
  competitiveRankingPredicted_Win: number | null;
  competitiveRankingPredicted_Loss: number | null;
  competitiveRankingPredicted_Tie: number | null;
  endMatchNextMapVote: number | null;
  activeQuestId: number | null;
  rtActiveMissionPeriod: number | null;
  playerTvControlFlags: number | null;
  draftIndex: number | null;
  msQueuedModeDisconnectionTimestamp: number | null;
  uiAbandonRecordedReason: number | null;
  networkDisconnectionReason: number | null;
  cannotBeKicked: boolean | null;
  everFullyConnected: boolean | null;
  abandonAllowsSurrender: boolean | null;
  abandonOffersInstantSurrender: boolean | null;
  disconnection1MinWarningPrinted: boolean | null;
  scoreReported: boolean | null;
  disconnectionTick: number | null;
  controllingBot: boolean | null;
  hasControlledBotThisRound: boolean | null;
  hasBeenControlledByPlayerThisRound: boolean | null;
  botsControlledThisRound: number | null;
  canControlObservedBot: boolean | null;
  readonly playerPawn: EntityRef | null;
  readonly observerPawn: EntityRef | null;
  desiredObserverMode: number | null;
  pawnIsAlive: boolean | null;
  pawnHealth: number | null;
  pawnArmor: number | null;
  pawnHasDefuser: boolean | null;
  pawnHasHelmet: boolean | null;
  pawnCharacterDefIndex: number | null;
  pawnLifetimeStart: number | null;
  pawnLifetimeEnd: number | null;
  pawnBotDifficulty: number | null;
  readonly originalControllerOfCurrentPawn: EntityRef | null;
  score: number | null;
  roundScore: number | null;
  roundsWon: number | null;
  firstKill: number | null;
  killCount: number | null;
  mvpNoMusic: boolean | null;
  mvpReason: number | null;
  musicKitID: number | null;
  musicKitMVPs: number | null;
  mVPs: number | null;
  updateCounter: number | null;
  smoothedPing: number | null;
  showHints: boolean | null;
  nextTimeCheck: number | null;
  justDidTeamKill: boolean | null;
  punishForTeamKill: boolean | null;
  gaveTeamDamageWarning: boolean | null;
  gaveTeamDamageWarningThisRound: boolean | null;
  readonly dblLastReceivedPacketPlatFloatTime: number | null;
  lastTeamDamageWarningTime: number | null;
  lastTimePlayerWasDisconnectedForPawnsRemove: number | null;
  suspiciousHitCount: number | null;
  nonSuspiciousHitStreak: number | null;
  fireBulletsSeedSynchronized: boolean | null;
  readonly lastHeldVoteTimer: IntervalTimer;
}

export interface CBaseCombatCharacter extends CBaseAnimGraph {
  forceServerRagdoll: boolean | null;
  impactEnergyScale: number | null;
  applyStressDamage: boolean | null;
  deathEventsDispatched: boolean | null;
  navHullIdx: number | null;
  readonly movementStats: CMovementStatsProperty;
}

export interface CEconEntity extends CBaseAnimGraph {
  originalOwnerXuidLow: number | null;
  originalOwnerXuidHigh: number | null;
  fallbackPaintKit: number | null;
  fallbackSeed: number | null;
  fallbackWear: number | null;
  fallbackStatTrak: number | null;
  readonly oldProvidee: EntityRef | null;
  oldOwnerClass: number | null;
  readonly attributeManager: CAttributeContainer;
}

export interface CBasePlayerPawn extends CBaseCombatCharacter {
  readonly v_angle: QAngle | null;
  readonly v_anglePrevious: QAngle | null;
  hideHUD: number | null;
  timeLastHurt: number | null;
  deathTime: number | null;
  nextSuicideTime: number | null;
  initHUD: boolean | null;
  readonly controller: EntityRef | null;
  readonly defaultController: EntityRef | null;
  hltvReplayDelay: number | null;
  hltvReplayEnd: number | null;
  readonly skybox3d: sky3dparams_t;
}

export interface CBasePlayerWeapon extends CEconEntity {
  nextPrimaryAttackTick: number | null;
  nextPrimaryAttackTickRatio: number | null;
  nextSecondaryAttackTick: number | null;
  nextSecondaryAttackTickRatio: number | null;
  clip1: number | null;
  clip2: number | null;
  readonly onPlayerUse: CEntityIOOutput;
}

export interface CCSPlayerPawnBase extends CBasePlayerPawn {
  blindUntilTime: number | null;
  blindStartTime: number | null;
  respawning: boolean | null;
  hasMovedSinceSpawn: boolean | null;
  numSpawns: number | null;
  idleTimeSinceLastAction: number | null;
  nextRadarUpdateTime: number | null;
  flashDuration: number | null;
  flashMaxAlpha: number | null;
  progressBarStartTime: number | null;
  progressBarDuration: number | null;
  readonly originalController: EntityRef | null;
  readonly cTouchExpansionComponent: CTouchExpansionComponent;
}

export interface CCSWeaponBase extends CBasePlayerWeapon {
  removeable: boolean | null;
  playerAmmoStockOnPickup: boolean | null;
  requireUseToTouch: boolean | null;
  weaponGameplayAnimStateTimestamp: number | null;
  inspectCancelCompleteTime: number | null;
  inspectPending: boolean | null;
  inspectShouldLoop: boolean | null;
  lastEmptySoundCmdNum: number | null;
  fireOnEmpty: boolean | null;
  turningInaccuracyDelta: number | null;
  readonly turningInaccuracyEyeDirLast: Vector | null;
  turningInaccuracy: number | null;
  accuracyPenalty: number | null;
  lastAccuracyUpdateTime: number | null;
  accuracySmoothedForZoom: number | null;
  m_iRecoilIndex: number | null;
  m_flRecoilIndex: number | null;
  burstMode: boolean | null;
  postponeFireReadyTicks: number | null;
  postponeFireReadyFrac: number | null;
  inReload: boolean | null;
  deployTick: number | null;
  droppedAtTime: number | null;
  isHauledBack: boolean | null;
  silencerOn: boolean | null;
  timeSilencerSwitchComplete: number | null;
  weaponActionPlaybackRate: number | null;
  originalTeamNumber: number | null;
  mostRecentTeamNumber: number | null;
  droppedNearBuyZone: boolean | null;
  nextAttackRenderTimeOffset: number | null;
  canBePickedUp: boolean | null;
  useCanOverrideNextOwnerTouchTime: boolean | null;
  nextOwnerTouchTime: number | null;
  nextPrevOwnerTouchTime: number | null;
  nextPrevOwnerUseTime: number | null;
  readonly prevOwner: EntityRef | null;
  dropTick: number | null;
  wasActiveWeaponWhenDropped: boolean | null;
  donated: boolean | null;
  lastShotTime: number | null;
  wasOwnedByCT: boolean | null;
  wasOwnedByTerrorist: boolean | null;
  numRemoveUnownedWeaponThink: number | null;
  ironSightMode: number | null;
  lastLOSTraceFailureTime: number | null;
  watTickOffset: number | null;
  lastShakeTime: number | null;
  readonly onPlayerPickup: CEntityIOOutput;
  readonly ironSightController: CIronSightController;
}

export interface CCSPlayerPawn extends CCSPlayerPawnBase {
  characterDefIndex: number | null;
  hasFemaleVoice: boolean | null;
  readonly lastPlaceName: string | null;
  inHostageResetZone: boolean | null;
  inBuyZone: boolean | null;
  wasInBuyZone: boolean | null;
  inHostageRescueZone: boolean | null;
  inBombZone: boolean | null;
  wasInHostageRescueZone: boolean | null;
  retakesOffering: number | null;
  retakesOfferingCard: number | null;
  retakesHasDefuseKit: boolean | null;
  retakesMVPLastRound: boolean | null;
  retakesMVPBoostItem: number | null;
  healthShotBoostExpirationTime: number | null;
  landingTimeSeconds: number | null;
  isBuyMenuOpen: boolean | null;
  lastLandTime: number | null;
  onGroundLastTick: boolean | null;
  playerLocked: number | null;
  timeOfLastInjury: number | null;
  nextSprayDecalTime: number | null;
  nextSprayDecalTimeExpedited: boolean | null;
  ragdollDamageBone: number | null;
  readonly ragdollDamageForce: Vector | null;
  readonly ragdollDamagePosition: Vector | null;
  readonly ragdollDamageWeaponName: string | null;
  ragdollDamageHeadshot: boolean | null;
  readonly ragdollServerOrigin: Vector | null;
  econGlovesChanged: number | null;
  readonly deathEyeAngles: QAngle | null;
  leftHanded: boolean | null;
  switchedHandednessTime: number | null;
  viewmodelOffsetX: number | null;
  viewmodelOffsetY: number | null;
  viewmodelOffsetZ: number | null;
  viewmodelFOV: number | null;
  isWalking: boolean | null;
  lastGivenDefuserTime: number | null;
  lastGivenBombTime: number | null;
  dealtDamageToEnemyMostRecentTimestamp: number | null;
  displayHistoryBits: number | null;
  lastAttackedTeammate: number | null;
  allowAutoFollowTime: number | null;
  resetArmorNextSpawn: boolean | null;
  spotRules: number | null;
  isScoped: boolean | null;
  resumeZoom: boolean | null;
  isDefusing: boolean | null;
  isGrabbingHostage: boolean | null;
  emitSoundTime: number | null;
  inNoDefuseArea: boolean | null;
  whichBombZone: number | null;
  inBombZoneTrigger: boolean | null;
  wasInBombZoneTrigger: boolean | null;
  shotsFired: number | null;
  flinchStack: number | null;
  velocityModifier: number | null;
  readonly totalBulletForce: Vector | null;
  waitForNoAttack: boolean | null;
  ignoreLadderJumpTime: number | null;
  killedByHeadshot: boolean | null;
  lastHitBox: number | null;
  botAllowActive: boolean | null;
  lastPickupPriority: number | null;
  lastPickupPriorityTime: number | null;
  armorValue: number | null;
  currentEquipmentValue: number | null;
  roundStartEquipmentValue: number | null;
  freezetimeEndEquipmentValue: number | null;
  lastWeaponFireUsercmd: number | null;
  isSpawning: boolean | null;
  deathFlags: number | null;
  hasDeathInfo: boolean | null;
  deathInfoTime: number | null;
  readonly deathInfoOrigin: Vector | null;
  gunGameImmunityColor: number | null;
  grenadeParameterStashTime: number | null;
  grenadeParametersStashed: boolean | null;
  readonly stashedShootAngles: QAngle | null;
  readonly stashedGrenadeThrowPosition: Vector | null;
  readonly stashedVelocity: Vector | null;
  committingSuicideOnTeamChange: boolean | null;
  wasNotKilledNaturally: boolean | null;
  immuneToGunGameDamageTime: number | null;
  gunGameImmunity: boolean | null;
  molotovDamageTime: number | null;
  readonly eyeAngles: QAngle | null;
  readonly econGloves: CEconItemView;
  readonly entitySpottedState: EntitySpottedState_t;
}
