// GENERATED by `s2script gen-schema` from schema-catalog.json — DO NOT EDIT.
import type { EntityRef } from "@s2script/sdk/entity";
import type { QAngle, Vector } from "@s2script/sdk/math";

export interface CEntityInstance {
}

export interface CBaseEntity extends CEntityInstance {
  currentThinkContext: number | null;
  disabledContextThinks: boolean | null;
  lastNetworkChange: number | null;
  health: number | null;
  maxHealth: number | null;
  lifeState: number | null;
  damageAccumulator: number | null;
  takesDamage: boolean | null;
  waterTouch: number | null;
  slimeTouch: number | null;
  restoreInHierarchy: boolean | null;
  readonly damageFilter: EntityRef | null;
  moveDoneTime: number | null;
  animTime: number | null;
  simulationTime: number | null;
  clientSideRagdoll: boolean | null;
  ubInterpolationFrame: number | null;
  readonly prevVPhysicsUpdatePos: Vector | null;
  teamNum: number | null;
  sentToClients: number | null;
  speed: number | null;
  spawnflags: number | null;
  simulationTick: number | null;
  flags: number | null;
  readonly absVelocity: Vector | null;
  readonly baseVelocity: Vector | null;
  pushEnumCount: number | null;
  readonly effectEntity: EntityRef | null;
  readonly ownerEntity: EntityRef | null;
  effects: number | null;
  readonly groundEntity: EntityRef | null;
  groundBodyIndex: number | null;
  friction: number | null;
  elasticity: number | null;
  gravityScale: number | null;
  timeScale: number | null;
  waterLevel: number | null;
  gravityDisabled: boolean | null;
  animatedEveryTick: boolean | null;
  actualGravityScale: number | null;
  gravityActuallyDisabled: boolean | null;
  disableLowViolence: boolean | null;
  waterType: number | null;
  eFlags: number | null;
  initialTeamNum: number | null;
  readonly angVelocity: QAngle | null;
  networkQuantizeOriginAndAngles: boolean | null;
  lagCompensate: boolean | null;
  readonly blocker: EntityRef | null;
  localTime: number | null;
  vPhysicsUpdateLocalTime: number | null;
}

export interface CBaseModelEntity extends CBaseEntity {
  destructiblePartInitialStateDestructed0_PartIndex: number | null;
  destructiblePartInitialStateDestructed1_PartIndex: number | null;
  destructiblePartInitialStateDestructed2_PartIndex: number | null;
  destructiblePartInitialStateDestructed3_PartIndex: number | null;
  destructiblePartInitialStateDestructed4_PartIndex: number | null;
  destructiblePartInitialStateDestructed0_GenerateBreakpieces: boolean | null;
  destructiblePartInitialStateDestructed1_GenerateBreakpieces: boolean | null;
  destructiblePartInitialStateDestructed2_GenerateBreakpieces: boolean | null;
  destructiblePartInitialStateDestructed3_GenerateBreakpieces: boolean | null;
  destructiblePartInitialStateDestructed4_GenerateBreakpieces: boolean | null;
  allowFadeInView: boolean | null;
  renderToCubemaps: boolean | null;
  noInterpolate: boolean | null;
  glowBackfaceMult: number | null;
  fadeMinDist: number | null;
  fadeMaxDist: number | null;
  fadeScale: number | null;
  shadowStrength: number | null;
  objectCulling: number | null;
}

export interface CBasePlayerController extends CBaseEntity {
  readonly inButtonsWhichAreToggles: string | null;
  tickBase: number | null;
  readonly pawn: EntityRef | null;
  knownTeamMismatch: boolean | null;
  readonly splitOwner: EntityRef | null;
  isHLTV: boolean | null;
  readonly playerName: string | null;
  lerpTime: number | null;
  lagCompensation: boolean | null;
  predict: boolean | null;
  isLowViolence: boolean | null;
  gamePaused: boolean | null;
  lastPlayerTalkTime: number | null;
  lastEntitySteadyState: number | null;
  availableEntitySteadyState: number | null;
  hasAnySteadyStateEnts: boolean | null;
  readonly steamID: string | null;
  noClipEnabled: boolean | null;
  desiredFOV: number | null;
}

export interface CBaseAnimGraph extends CBaseModelEntity {
  initiallyPopulateInterpHistory: boolean | null;
  animGraphUpdateEnabled: boolean | null;
  animationUpdateScheduled: boolean | null;
  readonly force: Vector | null;
  forceBone: number | null;
  ragdollEnabled: boolean | null;
  ragdollClientSide: boolean | null;
}

export interface CCSPlayerController extends CBasePlayerController {
  ping: number | null;
  hasCommunicationAbuseMute: boolean | null;
  uiCommunicationMuteFlags: number | null;
  pendingTeamNum: number | null;
  compTeammateColor: number | null;
  everPlayedOnTeam: boolean | null;
  attemptedToGetColor: boolean | null;
  teammatePreferredColor: number | null;
  teamChanged: boolean | null;
  inSwitchTeam: boolean | null;
  hasSeenJoinGame: boolean | null;
  justBecameSpectator: boolean | null;
  switchTeamsOnNextRoundReset: boolean | null;
  removeAllItemsOnNextRoundReset: boolean | null;
  coachingTeam: number | null;
  readonly playerDominated: string | null;
  readonly playerDominatingMe: string | null;
  competitiveRanking: number | null;
  competitiveWins: number | null;
  competitiveRankType: number | null;
  competitiveRankingPredicted_Win: number | null;
  competitiveRankingPredicted_Loss: number | null;
  competitiveRankingPredicted_Tie: number | null;
  endMatchNextMapVote: number | null;
  activeQuestId: number | null;
  rtActiveMissionPeriod: number | null;
  playerTvControlFlags: number | null;
  draftIndex: number | null;
  msQueuedModeDisconnectionTimestamp: number | null;
  uiAbandonRecordedReason: number | null;
  networkDisconnectionReason: number | null;
  cannotBeKicked: boolean | null;
  everFullyConnected: boolean | null;
  abandonAllowsSurrender: boolean | null;
  abandonOffersInstantSurrender: boolean | null;
  disconnection1MinWarningPrinted: boolean | null;
  scoreReported: boolean | null;
  disconnectionTick: number | null;
  controllingBot: boolean | null;
  hasControlledBotThisRound: boolean | null;
  hasBeenControlledByPlayerThisRound: boolean | null;
  botsControlledThisRound: number | null;
  canControlObservedBot: boolean | null;
  readonly playerPawn: EntityRef | null;
  readonly observerPawn: EntityRef | null;
  desiredObserverMode: number | null;
  pawnIsAlive: boolean | null;
  pawnHealth: number | null;
  pawnArmor: number | null;
  pawnHasDefuser: boolean | null;
  pawnHasHelmet: boolean | null;
  pawnCharacterDefIndex: number | null;
  pawnLifetimeStart: number | null;
  pawnLifetimeEnd: number | null;
  pawnBotDifficulty: number | null;
  readonly originalControllerOfCurrentPawn: EntityRef | null;
  score: number | null;
  roundScore: number | null;
  roundsWon: number | null;
  firstKill: number | null;
  killCount: number | null;
  mvpNoMusic: boolean | null;
  mvpReason: number | null;
  musicKitID: number | null;
  musicKitMVPs: number | null;
  mVPs: number | null;
  updateCounter: number | null;
  smoothedPing: number | null;
  showHints: boolean | null;
  nextTimeCheck: number | null;
  justDidTeamKill: boolean | null;
  punishForTeamKill: boolean | null;
  gaveTeamDamageWarning: boolean | null;
  gaveTeamDamageWarningThisRound: boolean | null;
  readonly dblLastReceivedPacketPlatFloatTime: number | null;
  suspiciousHitCount: number | null;
  nonSuspiciousHitStreak: number | null;
  fireBulletsSeedSynchronized: boolean | null;
}

export interface CBaseCombatCharacter extends CBaseAnimGraph {
  forceServerRagdoll: boolean | null;
  impactEnergyScale: number | null;
  applyStressDamage: boolean | null;
  deathEventsDispatched: boolean | null;
  navHullIdx: number | null;
}

export interface CEconEntity extends CBaseAnimGraph {
  originalOwnerXuidLow: number | null;
  originalOwnerXuidHigh: number | null;
  fallbackPaintKit: number | null;
  fallbackSeed: number | null;
  fallbackWear: number | null;
  fallbackStatTrak: number | null;
  readonly oldProvidee: EntityRef | null;
  oldOwnerClass: number | null;
}

export interface CBasePlayerPawn extends CBaseCombatCharacter {
  readonly v_angle: QAngle | null;
  readonly v_anglePrevious: QAngle | null;
  hideHUD: number | null;
  initHUD: boolean | null;
  readonly controller: EntityRef | null;
  readonly defaultController: EntityRef | null;
  hltvReplayDelay: number | null;
  hltvReplayEnd: number | null;
}

export interface CBasePlayerWeapon extends CEconEntity {
  nextPrimaryAttackTickRatio: number | null;
  nextSecondaryAttackTickRatio: number | null;
  clip1: number | null;
  clip2: number | null;
}

export interface CCSPlayerPawnBase extends CBasePlayerPawn {
  respawning: boolean | null;
  hasMovedSinceSpawn: boolean | null;
  numSpawns: number | null;
  idleTimeSinceLastAction: number | null;
  nextRadarUpdateTime: number | null;
  flashDuration: number | null;
  flashMaxAlpha: number | null;
  progressBarStartTime: number | null;
  progressBarDuration: number | null;
  readonly originalController: EntityRef | null;
}

export interface CCSWeaponBase extends CBasePlayerWeapon {
  removeable: boolean | null;
  playerAmmoStockOnPickup: boolean | null;
  requireUseToTouch: boolean | null;
  inspectPending: boolean | null;
  inspectShouldLoop: boolean | null;
  lastEmptySoundCmdNum: number | null;
  fireOnEmpty: boolean | null;
  turningInaccuracyDelta: number | null;
  readonly turningInaccuracyEyeDirLast: Vector | null;
  turningInaccuracy: number | null;
  accuracyPenalty: number | null;
  accuracySmoothedForZoom: number | null;
  m_iRecoilIndex: number | null;
  m_flRecoilIndex: number | null;
  burstMode: boolean | null;
  postponeFireReadyFrac: number | null;
  inReload: boolean | null;
  isHauledBack: boolean | null;
  silencerOn: boolean | null;
  weaponActionPlaybackRate: number | null;
  originalTeamNumber: number | null;
  mostRecentTeamNumber: number | null;
  droppedNearBuyZone: boolean | null;
  nextAttackRenderTimeOffset: number | null;
  canBePickedUp: boolean | null;
  useCanOverrideNextOwnerTouchTime: boolean | null;
  readonly prevOwner: EntityRef | null;
  wasActiveWeaponWhenDropped: boolean | null;
  donated: boolean | null;
  wasOwnedByCT: boolean | null;
  wasOwnedByTerrorist: boolean | null;
  numRemoveUnownedWeaponThink: number | null;
  ironSightMode: number | null;
  watTickOffset: number | null;
}

export interface CCSPlayerPawn extends CCSPlayerPawnBase {
  characterDefIndex: number | null;
  hasFemaleVoice: boolean | null;
  readonly lastPlaceName: string | null;
  inHostageResetZone: boolean | null;
  inBuyZone: boolean | null;
  wasInBuyZone: boolean | null;
  inHostageRescueZone: boolean | null;
  inBombZone: boolean | null;
  wasInHostageRescueZone: boolean | null;
  retakesOffering: number | null;
  retakesOfferingCard: number | null;
  retakesHasDefuseKit: boolean | null;
  retakesMVPLastRound: boolean | null;
  retakesMVPBoostItem: number | null;
  landingTimeSeconds: number | null;
  isBuyMenuOpen: boolean | null;
  onGroundLastTick: boolean | null;
  playerLocked: number | null;
  nextSprayDecalTimeExpedited: boolean | null;
  ragdollDamageBone: number | null;
  readonly ragdollDamageForce: Vector | null;
  readonly ragdollDamagePosition: Vector | null;
  readonly ragdollDamageWeaponName: string | null;
  ragdollDamageHeadshot: boolean | null;
  readonly ragdollServerOrigin: Vector | null;
  econGlovesChanged: number | null;
  readonly deathEyeAngles: QAngle | null;
  leftHanded: boolean | null;
  viewmodelOffsetX: number | null;
  viewmodelOffsetY: number | null;
  viewmodelOffsetZ: number | null;
  viewmodelFOV: number | null;
  isWalking: boolean | null;
  lastGivenDefuserTime: number | null;
  lastGivenBombTime: number | null;
  dealtDamageToEnemyMostRecentTimestamp: number | null;
  displayHistoryBits: number | null;
  lastAttackedTeammate: number | null;
  resetArmorNextSpawn: boolean | null;
  spotRules: number | null;
  isScoped: boolean | null;
  resumeZoom: boolean | null;
  isDefusing: boolean | null;
  isGrabbingHostage: boolean | null;
  inNoDefuseArea: boolean | null;
  whichBombZone: number | null;
  inBombZoneTrigger: boolean | null;
  wasInBombZoneTrigger: boolean | null;
  shotsFired: number | null;
  flinchStack: number | null;
  velocityModifier: number | null;
  readonly totalBulletForce: Vector | null;
  waitForNoAttack: boolean | null;
  ignoreLadderJumpTime: number | null;
  killedByHeadshot: boolean | null;
  lastHitBox: number | null;
  botAllowActive: boolean | null;
  lastPickupPriority: number | null;
  lastPickupPriorityTime: number | null;
  armorValue: number | null;
  currentEquipmentValue: number | null;
  roundStartEquipmentValue: number | null;
  freezetimeEndEquipmentValue: number | null;
  lastWeaponFireUsercmd: number | null;
  isSpawning: boolean | null;
  deathFlags: number | null;
  hasDeathInfo: boolean | null;
  deathInfoTime: number | null;
  readonly deathInfoOrigin: Vector | null;
  grenadeParametersStashed: boolean | null;
  readonly stashedShootAngles: QAngle | null;
  readonly stashedGrenadeThrowPosition: Vector | null;
  readonly stashedVelocity: Vector | null;
  committingSuicideOnTeamChange: boolean | null;
  wasNotKilledNaturally: boolean | null;
  gunGameImmunity: boolean | null;
  molotovDamageTime: number | null;
  readonly eyeAngles: QAngle | null;
}
