// GENERATED by `s2script gen-schema` from schema-catalog.json — DO NOT EDIT.
import type { EntityRef } from "@s2script/sdk/entity";
import type { QAngle, Vector } from "@s2script/sdk/math";

export interface CAnimGraphControllerManager {
  graphBindingsCreated: boolean | null;
}

export interface CAttributeContainer {
  reapplyProvisionParity: number | null;
  readonly outer: EntityRef | null;
  preventLoopback: boolean | null;
  readonly item: CEconItemView;
}

export interface CAttributeList {
}

export interface CCollisionProperty {
  readonly mins: Vector | null;
  readonly maxs: Vector | null;
  usSolidFlags: number | null;
  triggerBloat: number | null;
  collisionGroup: number | null;
  enablePhysics: number | null;
  boundingRadius: number | null;
  readonly specifiedSurroundingMins: Vector | null;
  readonly specifiedSurroundingMaxs: Vector | null;
  readonly surroundingMaxs: Vector | null;
  readonly surroundingMins: Vector | null;
  readonly capsuleCenter1: Vector | null;
  readonly capsuleCenter2: Vector | null;
  capsuleRadius: number | null;
  readonly collisionAttribute: VPhysicsCollisionAttribute_t;
}

export interface CEconItemView {
  itemDefinitionIndex: number | null;
  entityQuality: number | null;
  entityLevel: number | null;
  readonly itemID: string | null;
  itemIDHigh: number | null;
  itemIDLow: number | null;
  accountID: number | null;
  inventoryPosition: number | null;
  initialized: boolean | null;
  readonly customName: string | null;
  readonly customNameOverride: string | null;
  readonly attributeList: CAttributeList;
  readonly networkedDynamicAttributes: CAttributeList;
}

export interface CEntityIOOutput {
}

export interface CGlowProperty {
  readonly glowColor: Vector | null;
  glowType: number | null;
  glowTeam: number | null;
  glowRange: number | null;
  glowRangeMin: number | null;
  glowColorOverride: number | null;
  flashing: boolean | null;
  glowTime: number | null;
  glowStartTime: number | null;
  eligibleForScreenHighlight: boolean | null;
  glowing: boolean | null;
}

export interface CHitboxComponent {
  boundsExpandRadius: number | null;
}

export interface CIronSightController {
  ironSightAvailable: boolean | null;
  ironSightAmount: number | null;
  ironSightAmountGained: number | null;
  ironSightAmountBiased: number | null;
}

export interface CMovementStatsProperty {
  useCounter: number | null;
  readonly emaMovementDirection: CVectorExponentialMovingAverage;
}

export interface CNetworkTransmitComponent {
  transmitStateOwnedCounter: number | null;
}

export interface CNetworkVarChainer {
  pathIndex: number | null;
}

export interface CNetworkVelocityVector {
}

export interface CNetworkViewOffsetVector {
}

export interface CPropDataComponent {
  dmgModBullet: number | null;
  dmgModClub: number | null;
  dmgModExplosive: number | null;
  dmgModFire: number | null;
  interactions: number | null;
  spawnMotionDisabled: boolean | null;
  disableTakePhysicsDamageSpawnFlag: number | null;
  motionDisabledSpawnFlag: number | null;
}

export interface CRetakeGameRules {
  matchSeed: number | null;
  blockersPresent: boolean | null;
  roundInProgress: boolean | null;
  firstSecondHalfRound: number | null;
  bombSite: number | null;
  readonly bombPlanter: EntityRef | null;
}

export interface CTouchExpansionComponent {
}

export interface CVectorExponentialMovingAverage {
}

export interface EntitySpottedState_t {
  spotted: boolean | null;
}

export interface IntervalTimer {
  timestamp: number | null;
}

export interface PhysicsRagdollPose_t {
  readonly owner: EntityRef | null;
  setFromDebugHistory: boolean | null;
}

export interface VPhysicsCollisionAttribute_t {
  readonly interactsAs: string | null;
  readonly interactsWith: string | null;
  readonly interactsExclude: string | null;
  entityId: number | null;
  ownerId: number | null;
  hierarchyId: number | null;
  detailLayerMask: number | null;
  detailLayerMaskType: number | null;
  targetDetailLayer: number | null;
  collisionGroup: number | null;
  collisionFunctionMask: number | null;
}

export interface fogparams_t {
  readonly dirPrimary: Vector | null;
  colorPrimary: number | null;
  colorSecondary: number | null;
  colorPrimaryLerpTo: number | null;
  colorSecondaryLerpTo: number | null;
  start: number | null;
  end: number | null;
  farz: number | null;
  maxdensity: number | null;
  exponent: number | null;
  hDRColorScale: number | null;
  skyboxFogFactor: number | null;
  skyboxFogFactorLerpTo: number | null;
  startLerpTo: number | null;
  endLerpTo: number | null;
  maxdensityLerpTo: number | null;
  lerptime: number | null;
  duration: number | null;
  blendtobackground: number | null;
  scattering: number | null;
  locallightscale: number | null;
  enable: boolean | null;
  blend: boolean | null;
  padding2: boolean | null;
  padding: boolean | null;
}

export interface locksound_t {
  flwaitSound: number | null;
}

export interface ragdoll_t {
  allowStretch: boolean | null;
  unused: boolean | null;
}

export interface sky3dparams_t {
  scale: number | null;
  readonly origin: Vector | null;
  clip3DSkyBoxNearToWorldFar: boolean | null;
  clip3DSkyBoxNearToWorldFarOffset: number | null;
  readonly fog: fogparams_t;
}

export interface CEntityInstance {
}

export interface CGameRules {
  readonly questName: string | null;
  questPhase: number | null;
  lastMatchTime: number | null;
  readonly lastMatchTime_MatchID64: string | null;
  totalPausedTicks: number | null;
  pauseStartTick: number | null;
  gamePaused: boolean | null;
  readonly __m_pChainEntity: CNetworkVarChainer;
}

export interface CBaseEntity extends CEntityInstance {
  currentThinkContext: number | null;
  lastThinkTick: number | null;
  disabledContextThinks: boolean | null;
  lastNetworkChange: number | null;
  health: number | null;
  maxHealth: number | null;
  lifeState: number | null;
  damageAccumulator: number | null;
  takesDamage: boolean | null;
  waterTouch: number | null;
  slimeTouch: number | null;
  restoreInHierarchy: boolean | null;
  readonly damageFilter: EntityRef | null;
  moveDoneTime: number | null;
  animTime: number | null;
  simulationTime: number | null;
  createTime: number | null;
  clientSideRagdoll: boolean | null;
  ubInterpolationFrame: number | null;
  readonly prevVPhysicsUpdatePos: Vector | null;
  teamNum: number | null;
  sentToClients: number | null;
  speed: number | null;
  spawnflags: number | null;
  nextThinkTick: number | null;
  simulationTick: number | null;
  flags: number | null;
  readonly absVelocity: Vector | null;
  readonly baseVelocity: Vector | null;
  pushEnumCount: number | null;
  readonly effectEntity: EntityRef | null;
  readonly ownerEntity: EntityRef | null;
  effects: number | null;
  readonly groundEntity: EntityRef | null;
  groundBodyIndex: number | null;
  friction: number | null;
  elasticity: number | null;
  gravityScale: number | null;
  timeScale: number | null;
  waterLevel: number | null;
  gravityDisabled: boolean | null;
  animatedEveryTick: boolean | null;
  actualGravityScale: number | null;
  gravityActuallyDisabled: boolean | null;
  disableLowViolence: boolean | null;
  waterType: number | null;
  eFlags: number | null;
  initialTeamNum: number | null;
  navIgnoreUntilTime: number | null;
  readonly angVelocity: QAngle | null;
  networkQuantizeOriginAndAngles: boolean | null;
  lagCompensate: boolean | null;
  readonly blocker: EntityRef | null;
  localTime: number | null;
  vPhysicsUpdateLocalTime: number | null;
  readonly networkTransmitComponent: CNetworkTransmitComponent;
  readonly onKilled: CEntityIOOutput;
  readonly velocity: CNetworkVelocityVector;
  readonly onUser1: CEntityIOOutput;
  readonly onUser2: CEntityIOOutput;
  readonly onUser3: CEntityIOOutput;
  readonly onUser4: CEntityIOOutput;
}

export interface CMultiplayRules extends CGameRules {
}

export interface CBaseModelEntity extends CBaseEntity {
  destructiblePartInitialStateDestructed0_PartIndex: number | null;
  destructiblePartInitialStateDestructed1_PartIndex: number | null;
  destructiblePartInitialStateDestructed2_PartIndex: number | null;
  destructiblePartInitialStateDestructed3_PartIndex: number | null;
  destructiblePartInitialStateDestructed4_PartIndex: number | null;
  destructiblePartInitialStateDestructed0_GenerateBreakpieces: boolean | null;
  destructiblePartInitialStateDestructed1_GenerateBreakpieces: boolean | null;
  destructiblePartInitialStateDestructed2_GenerateBreakpieces: boolean | null;
  destructiblePartInitialStateDestructed3_GenerateBreakpieces: boolean | null;
  destructiblePartInitialStateDestructed4_GenerateBreakpieces: boolean | null;
  dissolveStartTime: number | null;
  allowFadeInView: boolean | null;
  render: number | null;
  renderToCubemaps: boolean | null;
  noInterpolate: boolean | null;
  glowBackfaceMult: number | null;
  fadeMinDist: number | null;
  fadeMaxDist: number | null;
  fadeScale: number | null;
  shadowStrength: number | null;
  objectCulling: number | null;
  readonly cHitboxComponent: CHitboxComponent;
  readonly onIgnite: CEntityIOOutput;
  readonly collision: CCollisionProperty;
  readonly glow: CGlowProperty;
  readonly viewOffset: CNetworkViewOffsetVector;
}

export interface CBasePlayerController extends CBaseEntity {
  readonly inButtonsWhichAreToggles: string | null;
  tickBase: number | null;
  readonly pawn: EntityRef | null;
  knownTeamMismatch: boolean | null;
  readonly splitOwner: EntityRef | null;
  isHLTV: boolean | null;
  readonly playerName: string | null;
  lerpTime: number | null;
  lagCompensation: boolean | null;
  predict: boolean | null;
  isLowViolence: boolean | null;
  gamePaused: boolean | null;
  lastPlayerTalkTime: number | null;
  lastEntitySteadyState: number | null;
  availableEntitySteadyState: number | null;
  hasAnySteadyStateEnts: boolean | null;
  readonly steamID: string | null;
  noClipEnabled: boolean | null;
  desiredFOV: number | null;
}

export interface CTeam extends CBaseEntity {
  score: number | null;
  readonly teamname: string | null;
}

export interface CTeamplayRules extends CMultiplayRules {
}

export interface CBaseAnimGraph extends CBaseModelEntity {
  initiallyPopulateInterpHistory: boolean | null;
  animGraphUpdateEnabled: boolean | null;
  animationUpdateScheduled: boolean | null;
  readonly force: Vector | null;
  forceBone: number | null;
  ragdollEnabled: boolean | null;
  ragdollClientSide: boolean | null;
  readonly graphControllerManager: CAnimGraphControllerManager;
  readonly ragdollPose: PhysicsRagdollPose_t;
}

export interface CBaseToggle extends CBaseModelEntity {
  moveDistance: number | null;
  wait: number | null;
  lip: number | null;
  alwaysFireBlockedOutputs: boolean | null;
  readonly position1: Vector | null;
  readonly position2: Vector | null;
  readonly moveAng: QAngle | null;
  readonly angle1: QAngle | null;
  readonly angle2: QAngle | null;
  height: number | null;
  readonly activator: EntityRef | null;
  readonly finalDest: Vector | null;
  readonly finalAngle: QAngle | null;
  movementType: number | null;
}

export interface CBeam extends CBaseModelEntity {
  frameRate: number | null;
  hDRColorScale: number | null;
  fireTime: number | null;
  damage: number | null;
  numBeamEnts: number | null;
  beamFlags: number | null;
  width: number | null;
  endWidth: number | null;
  fadeLength: number | null;
  haloScale: number | null;
  amplitude: number | null;
  startFrame: number | null;
  m_fSpeed: number | null;
  frame: number | null;
  turnedOff: boolean | null;
  readonly endPos: Vector | null;
  readonly endEntity: EntityRef | null;
  dissolveType: number | null;
}

export interface CCSGameRules extends CTeamplayRules {
  freezePeriod: boolean | null;
  warmupPeriod: boolean | null;
  warmupPeriodEnd: number | null;
  warmupPeriodStart: number | null;
  terroristTimeOutActive: boolean | null;
  cTTimeOutActive: boolean | null;
  terroristTimeOutRemaining: number | null;
  cTTimeOutRemaining: number | null;
  terroristTimeOuts: number | null;
  cTTimeOuts: number | null;
  technicalTimeOut: boolean | null;
  matchWaitingForResume: boolean | null;
  freezeTime: number | null;
  roundTime: number | null;
  matchStartTime: number | null;
  roundStartTime: number | null;
  restartRoundTime: number | null;
  gameRestart: boolean | null;
  gameStartTime: number | null;
  timeUntilNextPhaseStarts: number | null;
  gamePhase: number | null;
  m_totalRoundsPlayed: number | null;
  roundsPlayedThisPhase: number | null;
  overtimePlaying: number | null;
  hostagesRemaining: number | null;
  anyHostageReached: boolean | null;
  mapHasBombTarget: boolean | null;
  mapHasRescueZone: boolean | null;
  mapHasBuyZone: boolean | null;
  isQueuedMatchmaking: boolean | null;
  queuedMatchmakingMode: number | null;
  isValveDS: boolean | null;
  logoMap: boolean | null;
  playAllStepSoundsOnServer: boolean | null;
  spectatorSlotCount: number | null;
  matchDevice: number | null;
  hasMatchStarted: boolean | null;
  nextMapInMapgroup: number | null;
  readonly tournamentEventName: string | null;
  readonly tournamentEventStage: string | null;
  readonly matchStatTxt: string | null;
  readonly tournamentPredictionsTxt: string | null;
  tournamentPredictionsPct: number | null;
  cMMItemDropRevealStartTime: number | null;
  cMMItemDropRevealEndTime: number | null;
  isDroppingItems: boolean | null;
  isQuestEligible: boolean | null;
  isHltvActive: boolean | null;
  bombPlanted: boolean | null;
  numBestOfMaps: number | null;
  halloweenMaskListSeed: number | null;
  bombDropped: boolean | null;
  roundWinStatus: number | null;
  roundWinReason: number | null;
  tCantBuy: boolean | null;
  cTCantBuy: boolean | null;
  readonly minimapMins: Vector | null;
  readonly minimapMaxs: Vector | null;
  readonly ullLocalMatchID: string | null;
  endMatchMapVoteWinner: number | null;
  numConsecutiveCTLoses: number | null;
  numConsecutiveTerroristLoses: number | null;
  hasHostageBeenTouched: boolean | null;
  intermissionStartTime: number | null;
  intermissionEndTime: number | null;
  levelInitialized: boolean | null;
  m_iTotalRoundsPlayed: number | null;
  unBalancedRounds: number | null;
  endMatchOnRoundReset: boolean | null;
  endMatchOnThink: boolean | null;
  numTerrorist: number | null;
  numCT: number | null;
  numSpawnableTerrorist: number | null;
  numSpawnableCT: number | null;
  spawnPointsRandomSeed: number | null;
  firstConnected: boolean | null;
  completeReset: boolean | null;
  pickNewTeamsOnReset: boolean | null;
  scrambleTeamsOnRestart: boolean | null;
  swapTeamsOnRestart: boolean | null;
  needToAskPlayersForContinueVote: boolean | null;
  numQueuedMatchmakingAccounts: number | null;
  avgPlayerRank: number | null;
  numTotalTournamentDrops: number | null;
  numSpectatorsCountMax: number | null;
  numSpectatorsCountMaxTV: number | null;
  numSpectatorsCountMaxLnk: number | null;
  cTsAliveAtFreezetimeEnd: number | null;
  terroristsAliveAtFreezetimeEnd: number | null;
  forceTeamChangeSilent: boolean | null;
  loadingRoundBackupData: boolean | null;
  matchInfoShowType: number | null;
  matchInfoDecidedTime: number | null;
  mTeamDMLastWinningTeamNumber: number | null;
  mTeamDMLastThinkTime: number | null;
  teamDMLastAnnouncementTime: number | null;
  accountTerrorist: number | null;
  accountCT: number | null;
  spawnPointCount_Terrorist: number | null;
  spawnPointCount_CT: number | null;
  maxNumTerrorists: number | null;
  maxNumCTs: number | null;
  loserBonusMostRecentTeam: number | null;
  tmNextPeriodicThink: number | null;
  voiceWonMatchBragFired: boolean | null;
  warmupNextChatNoticeTime: number | null;
  hostagesRescued: number | null;
  hostagesTouched: number | null;
  nextHostageAnnouncement: number | null;
  noTerroristsKilled: boolean | null;
  noCTsKilled: boolean | null;
  noEnemiesKilled: boolean | null;
  canDonateWeapons: boolean | null;
  firstKillTime: number | null;
  firstBloodTime: number | null;
  hostageWasInjured: boolean | null;
  hostageWasKilled: boolean | null;
  voteCalled: boolean | null;
  serverVoteOnReset: boolean | null;
  voteCheckThrottle: number | null;
  buyTimeEnded: boolean | null;
  lastFreezeEndBeep: number | null;
  targetBombed: boolean | null;
  bombDefused: boolean | null;
  mapHasBombZone: boolean | null;
  readonly mainCTSpawnPos: Vector | null;
  respawningAllRespawnablePlayers: boolean | null;
  nextCTSpawnPoint: number | null;
  cTSpawnPointUsedTime: number | null;
  nextTerroristSpawnPoint: number | null;
  terroristSpawnPointUsedTime: number | null;
  isUnreservedGameServer: boolean | null;
  autobalanceDisplayTime: number | null;
  allowWeaponSwitch: boolean | null;
  roundTimeWarningTriggered: boolean | null;
  phaseChangeAnnouncementTime: number | null;
  nextUpdateTeamClanNamesTime: number | null;
  lastThinkTime: number | null;
  accumulatedRoundOffDamage: number | null;
  shorthandedBonusLastEvalRound: number | null;
  matchAbortedEarlyReason: number | null;
  hasTriggeredRoundStartMusic: boolean | null;
  switchingTeamsAtRoundReset: boolean | null;
  readonly playerResource: EntityRef | null;
  matchEndCount: number | null;
  tTeamIntroVariant: number | null;
  cTTeamIntroVariant: number | null;
  teamIntroPeriod: boolean | null;
  teamIntroPeriodEnd: number | null;
  playedTeamIntroVO: boolean | null;
  roundEndWinnerTeam: number | null;
  roundEndReason: number | null;
  roundEndShowTimerDefend: boolean | null;
  roundEndTimerTime: number | null;
  roundEndFunFactData1: number | null;
  roundEndFunFactData2: number | null;
  roundEndFunFactData3: number | null;
  roundEndPlayerCount: number | null;
  roundEndNoMusic: boolean | null;
  roundEndLegacy: number | null;
  roundEndCount: number | null;
  roundStartRoundNumber: number | null;
  roundStartCount: number | null;
  readonly lastPerfSampleTime: number | null;
  readonly retakeRules: CRetakeGameRules;
}

export interface CCSPlayerController extends CBasePlayerController {
  ping: number | null;
  hasCommunicationAbuseMute: boolean | null;
  uiCommunicationMuteFlags: number | null;
  pendingTeamNum: number | null;
  forceTeamTime: number | null;
  compTeammateColor: number | null;
  everPlayedOnTeam: boolean | null;
  attemptedToGetColor: boolean | null;
  teammatePreferredColor: number | null;
  teamChanged: boolean | null;
  inSwitchTeam: boolean | null;
  hasSeenJoinGame: boolean | null;
  justBecameSpectator: boolean | null;
  switchTeamsOnNextRoundReset: boolean | null;
  removeAllItemsOnNextRoundReset: boolean | null;
  lastJoinTeamTime: number | null;
  coachingTeam: number | null;
  readonly playerDominated: string | null;
  readonly playerDominatingMe: string | null;
  competitiveRanking: number | null;
  competitiveWins: number | null;
  competitiveRankType: number | null;
  competitiveRankingPredicted_Win: number | null;
  competitiveRankingPredicted_Loss: number | null;
  competitiveRankingPredicted_Tie: number | null;
  endMatchNextMapVote: number | null;
  activeQuestId: number | null;
  rtActiveMissionPeriod: number | null;
  playerTvControlFlags: number | null;
  draftIndex: number | null;
  msQueuedModeDisconnectionTimestamp: number | null;
  uiAbandonRecordedReason: number | null;
  networkDisconnectionReason: number | null;
  cannotBeKicked: boolean | null;
  everFullyConnected: boolean | null;
  abandonAllowsSurrender: boolean | null;
  abandonOffersInstantSurrender: boolean | null;
  disconnection1MinWarningPrinted: boolean | null;
  scoreReported: boolean | null;
  disconnectionTick: number | null;
  controllingBot: boolean | null;
  hasControlledBotThisRound: boolean | null;
  hasBeenControlledByPlayerThisRound: boolean | null;
  botsControlledThisRound: number | null;
  canControlObservedBot: boolean | null;
  readonly playerPawn: EntityRef | null;
  readonly observerPawn: EntityRef | null;
  desiredObserverMode: number | null;
  pawnIsAlive: boolean | null;
  pawnHealth: number | null;
  pawnArmor: number | null;
  pawnHasDefuser: boolean | null;
  pawnHasHelmet: boolean | null;
  pawnCharacterDefIndex: number | null;
  pawnLifetimeStart: number | null;
  pawnLifetimeEnd: number | null;
  pawnBotDifficulty: number | null;
  readonly originalControllerOfCurrentPawn: EntityRef | null;
  score: number | null;
  roundScore: number | null;
  roundsWon: number | null;
  firstKill: number | null;
  killCount: number | null;
  mvpNoMusic: boolean | null;
  mvpReason: number | null;
  musicKitID: number | null;
  musicKitMVPs: number | null;
  mVPs: number | null;
  updateCounter: number | null;
  smoothedPing: number | null;
  showHints: boolean | null;
  nextTimeCheck: number | null;
  justDidTeamKill: boolean | null;
  punishForTeamKill: boolean | null;
  gaveTeamDamageWarning: boolean | null;
  gaveTeamDamageWarningThisRound: boolean | null;
  readonly dblLastReceivedPacketPlatFloatTime: number | null;
  lastTeamDamageWarningTime: number | null;
  lastTimePlayerWasDisconnectedForPawnsRemove: number | null;
  suspiciousHitCount: number | null;
  nonSuspiciousHitStreak: number | null;
  fireBulletsSeedSynchronized: boolean | null;
  readonly lastHeldVoteTimer: IntervalTimer;
}

export interface CCSTeam extends CTeam {
  lastRecievedShorthandedRoundBonus: number | null;
  shorthandedRoundBonusStartRound: number | null;
  surrendered: boolean | null;
  readonly teamMatchStat: string | null;
  numMapVictories: number | null;
  scoreFirstHalf: number | null;
  scoreSecondHalf: number | null;
  scoreOvertime: number | null;
  readonly clanTeamname: string | null;
  clanID: number | null;
  readonly teamFlagImage: string | null;
  readonly teamLogoImage: string | null;
  nextResourceTime: number | null;
  lastUpdateSentAt: number | null;
}

export interface CModelPointEntity extends CBaseModelEntity {
}

export interface CBaseButton extends CBaseToggle {
  readonly moveEntitySpace: QAngle | null;
  stayPushed: boolean | null;
  rotating: boolean | null;
  locked: boolean | null;
  disabled: boolean | null;
  useLockedTime: number | null;
  solidBsp: boolean | null;
  state: number | null;
  forceNpcExclude: boolean | null;
  readonly glowEntity: EntityRef | null;
  usable: boolean | null;
  readonly ls: locksound_t;
  readonly onDamaged: CEntityIOOutput;
  readonly onPressed: CEntityIOOutput;
  readonly onUseLocked: CEntityIOOutput;
  readonly onIn: CEntityIOOutput;
  readonly onOut: CEntityIOOutput;
}

export interface CBaseCombatCharacter extends CBaseAnimGraph {
  forceServerRagdoll: boolean | null;
  impactEnergyScale: number | null;
  applyStressDamage: boolean | null;
  deathEventsDispatched: boolean | null;
  navHullIdx: number | null;
  readonly movementStats: CMovementStatsProperty;
}

export interface CBaseDoor extends CBaseToggle {
  readonly moveEntitySpace: QAngle | null;
  readonly moveDirParentSpace: Vector | null;
  forceClosed: boolean | null;
  doorGroup: boolean | null;
  locked: boolean | null;
  ignoreDebris: boolean | null;
  noNPCs: boolean | null;
  blockDamage: number | null;
  loopMoveSound: boolean | null;
  createNavObstacle: boolean | null;
  isChaining: boolean | null;
  isUsable: boolean | null;
  readonly ls: locksound_t;
  readonly onBlockedClosing: CEntityIOOutput;
  readonly onBlockedOpening: CEntityIOOutput;
  readonly onUnblockedClosing: CEntityIOOutput;
  readonly onUnblockedOpening: CEntityIOOutput;
  readonly onFullyClosed: CEntityIOOutput;
  readonly onFullyOpen: CEntityIOOutput;
  readonly onClose: CEntityIOOutput;
  readonly onOpen: CEntityIOOutput;
  readonly onLockedUse: CEntityIOOutput;
}

export interface CBaseGrenade extends CBaseAnimGraph {
  hasWarnedAI: boolean | null;
  isSmokeGrenade: boolean | null;
  isLive: boolean | null;
  dmgRadius: number | null;
  detonateTime: number | null;
  warnAITime: number | null;
  damage: number | null;
  readonly thrower: EntityRef | null;
  nextAttack: number | null;
  readonly originalThrower: EntityRef | null;
  readonly onPlayerPickup: CEntityIOOutput;
  readonly onExplode: CEntityIOOutput;
}

export interface CBaseProp extends CBaseAnimGraph {
  modelOverrodeBlockLOS: boolean | null;
  shapeType: number | null;
  conformToCollisionBounds: boolean | null;
}

export interface CBaseTrigger extends CBaseToggle {
  readonly filter: EntityRef | null;
  disabled: boolean | null;
  useAsyncQueries: boolean | null;
  readonly onStartTouch: CEntityIOOutput;
  readonly onStartTouchAll: CEntityIOOutput;
  readonly onEndTouch: CEntityIOOutput;
  readonly onEndTouchAll: CEntityIOOutput;
  readonly onTouching: CEntityIOOutput;
  readonly onTouchingEachEntity: CEntityIOOutput;
  readonly onNotTouching: CEntityIOOutput;
}

export interface CEconEntity extends CBaseAnimGraph {
  originalOwnerXuidLow: number | null;
  originalOwnerXuidHigh: number | null;
  fallbackPaintKit: number | null;
  fallbackSeed: number | null;
  fallbackWear: number | null;
  fallbackStatTrak: number | null;
  readonly oldProvidee: EntityRef | null;
  oldOwnerClass: number | null;
  readonly attributeManager: CAttributeContainer;
}

export interface CPlantedC4 extends CBaseAnimGraph {
  bombTicking: boolean | null;
  c4Blow: number | null;
  bombSite: number | null;
  sourceSoundscapeHash: number | null;
  abortDetonationBecauseWorldIsFrozen: boolean | null;
  cannotBeDefused: boolean | null;
  spotRules: number | null;
  hasExploded: boolean | null;
  bombDefused: boolean | null;
  trainingPlacedByPlayer: boolean | null;
  timerLength: number | null;
  beingDefused: boolean | null;
  lastDefuseTime: number | null;
  defuseLength: number | null;
  defuseCountDown: number | null;
  readonly bombDefuser: EntityRef | null;
  progressBarTime: number | null;
  voiceAlertFired: boolean | null;
  nextBotBeepTime: number | null;
  readonly catchUpToPlayerEye: QAngle | null;
  lastSpinDetectionTime: number | null;
  readonly attributeManager: CAttributeContainer;
  readonly onBombDefused: CEntityIOOutput;
  readonly onBombBeginDefuse: CEntityIOOutput;
  readonly onBombDefuseAborted: CEntityIOOutput;
  readonly entitySpottedState: EntitySpottedState_t;
}

export interface CPointWorldText extends CModelPointEntity {
  readonly messageText: string | null;
  readonly fontName: string | null;
  readonly backgroundMaterialName: string | null;
  enabled: boolean | null;
  fullbright: boolean | null;
  worldUnitsPerPx: number | null;
  fontSize: number | null;
  depthOffset: number | null;
  drawBackground: boolean | null;
  backgroundBorderWidth: number | null;
  backgroundBorderHeight: number | null;
  backgroundWorldToUV: number | null;
  color: number | null;
}

export interface CRagdollProp extends CBaseAnimGraph {
  startDisabled: boolean | null;
  lastUpdateTickCount: number | null;
  allAsleep: boolean | null;
  firstCollisionAfterLaunch: boolean | null;
  updateNavWhenMoving: boolean | null;
  forceNavObstacleCut: boolean | null;
  attachedToReferenceFrame: boolean | null;
  readonly damageEntity: EntityRef | null;
  readonly killer: EntityRef | null;
  readonly physicsAttacker: EntityRef | null;
  lastPhysicsInfluenceTime: number | null;
  fadeOutStartTime: number | null;
  fadeTime: number | null;
  readonly lastOrigin: Vector | null;
  awakeTime: number | null;
  lastOriginChangeTime: number | null;
  hasBeenPhysgunned: boolean | null;
  allowStretch: boolean | null;
  blendWeight: number | null;
  defaultFadeScale: number | null;
  shouldDeleteActivationRecord: boolean | null;
  readonly ragdoll: ragdoll_t;
}

export interface CBaseCSGrenadeProjectile extends CBaseGrenade {
  readonly initialPosition: Vector | null;
  readonly initialVelocity: Vector | null;
  bounces: number | null;
  explodeEffectTickBegin: number | null;
  readonly explodeEffectOrigin: Vector | null;
  spawnTime: number | null;
  oGSExtraFlags: number | null;
  detonationRecorded: boolean | null;
  itemIndex: number | null;
  readonly originalSpawnLocation: Vector | null;
  lastBounceSoundTime: number | null;
  readonly lastHitSurfaceNormal: Vector | null;
  ticksAtZeroVelocity: number | null;
  hasEverHitEnemy: boolean | null;
}

export interface CBasePlayerPawn extends CBaseCombatCharacter {
  readonly v_angle: QAngle | null;
  readonly v_anglePrevious: QAngle | null;
  hideHUD: number | null;
  timeLastHurt: number | null;
  deathTime: number | null;
  nextSuicideTime: number | null;
  initHUD: boolean | null;
  readonly controller: EntityRef | null;
  readonly defaultController: EntityRef | null;
  hltvReplayDelay: number | null;
  hltvReplayEnd: number | null;
  readonly skybox3d: sky3dparams_t;
}

export interface CBasePlayerWeapon extends CEconEntity {
  nextPrimaryAttackTick: number | null;
  nextPrimaryAttackTickRatio: number | null;
  nextSecondaryAttackTick: number | null;
  nextSecondaryAttackTickRatio: number | null;
  clip1: number | null;
  clip2: number | null;
  readonly onPlayerUse: CEntityIOOutput;
}

export interface CBreakableProp extends CBaseProp {
  impactEnergyScale: number | null;
  minHealthDmg: number | null;
  readonly preferredCarryAngles: QAngle | null;
  pressureDelay: number | null;
  defBurstScale: number | null;
  readonly defBurstOffset: Vector | null;
  readonly breaker: EntityRef | null;
  preventDamageBeforeTime: number | null;
  hasBreakPiecesOrCommands: boolean | null;
  explodeDamage: number | null;
  explodeRadius: number | null;
  explosionDelay: number | null;
  readonly physicsAttacker: EntityRef | null;
  lastPhysicsInfluenceTime: number | null;
  defaultFadeScale: number | null;
  readonly lastAttacker: EntityRef | null;
  usePuntSound: boolean | null;
  originalBlockLOS: boolean | null;
  readonly cPropDataComponent: CPropDataComponent;
  readonly onStartDeath: CEntityIOOutput;
  readonly onBreak: CEntityIOOutput;
  readonly onTakeDamage: CEntityIOOutput;
}

export interface CCSPlayerPawnBase extends CBasePlayerPawn {
  blindUntilTime: number | null;
  blindStartTime: number | null;
  respawning: boolean | null;
  hasMovedSinceSpawn: boolean | null;
  numSpawns: number | null;
  idleTimeSinceLastAction: number | null;
  nextRadarUpdateTime: number | null;
  flashDuration: number | null;
  flashMaxAlpha: number | null;
  progressBarStartTime: number | null;
  progressBarDuration: number | null;
  readonly originalController: EntityRef | null;
  readonly cTouchExpansionComponent: CTouchExpansionComponent;
}

export interface CCSWeaponBase extends CBasePlayerWeapon {
  removeable: boolean | null;
  playerAmmoStockOnPickup: boolean | null;
  requireUseToTouch: boolean | null;
  weaponGameplayAnimStateTimestamp: number | null;
  inspectCancelCompleteTime: number | null;
  inspectPending: boolean | null;
  inspectShouldLoop: boolean | null;
  lastEmptySoundCmdNum: number | null;
  fireOnEmpty: boolean | null;
  turningInaccuracyDelta: number | null;
  readonly turningInaccuracyEyeDirLast: Vector | null;
  turningInaccuracy: number | null;
  accuracyPenalty: number | null;
  lastAccuracyUpdateTime: number | null;
  accuracySmoothedForZoom: number | null;
  m_iRecoilIndex: number | null;
  m_flRecoilIndex: number | null;
  burstMode: boolean | null;
  postponeFireReadyTicks: number | null;
  postponeFireReadyFrac: number | null;
  inReload: boolean | null;
  deployTick: number | null;
  droppedAtTime: number | null;
  isHauledBack: boolean | null;
  silencerOn: boolean | null;
  timeSilencerSwitchComplete: number | null;
  weaponActionPlaybackRate: number | null;
  originalTeamNumber: number | null;
  mostRecentTeamNumber: number | null;
  droppedNearBuyZone: boolean | null;
  nextAttackRenderTimeOffset: number | null;
  canBePickedUp: boolean | null;
  useCanOverrideNextOwnerTouchTime: boolean | null;
  nextOwnerTouchTime: number | null;
  nextPrevOwnerTouchTime: number | null;
  nextPrevOwnerUseTime: number | null;
  readonly prevOwner: EntityRef | null;
  dropTick: number | null;
  wasActiveWeaponWhenDropped: boolean | null;
  donated: boolean | null;
  lastShotTime: number | null;
  wasOwnedByCT: boolean | null;
  wasOwnedByTerrorist: boolean | null;
  numRemoveUnownedWeaponThink: number | null;
  ironSightMode: number | null;
  lastLOSTraceFailureTime: number | null;
  watTickOffset: number | null;
  lastShakeTime: number | null;
  readonly onPlayerPickup: CEntityIOOutput;
  readonly ironSightController: CIronSightController;
}

export interface CDynamicProp extends CBreakableProp {
  createNavObstacle: boolean | null;
  navObstacleUpdatesOverridden: boolean | null;
  useHitboxesForRenderBox: boolean | null;
  useAnimGraph: boolean | null;
  randomizeCycle: boolean | null;
  startDisabled: boolean | null;
  firedStartEndOutput: boolean | null;
  forceNpcExclude: boolean | null;
  createNonSolid: boolean | null;
  isOverrideProp: boolean | null;
  initialGlowState: number | null;
  glowRange: number | null;
  glowRangeMin: number | null;
  glowColor: number | null;
  glowTeam: number | null;
  readonly outputAnimBegun: CEntityIOOutput;
  readonly outputAnimOver: CEntityIOOutput;
  readonly outputAnimLoopCycleOver: CEntityIOOutput;
  readonly onAnimReachedStart: CEntityIOOutput;
  readonly onAnimReachedEnd: CEntityIOOutput;
}

export interface CPhysicsProp extends CBreakableProp {
  forceNavIgnore: boolean | null;
  noNavmeshBlocker: boolean | null;
  forceNpcExclude: boolean | null;
  massScale: number | null;
  buoyancyScale: number | null;
  damageType: number | null;
  damageToEnableMotion: number | null;
  forceToEnableMotion: number | null;
  thrownByPlayer: boolean | null;
  droppedByPlayer: boolean | null;
  touchedByPlayer: boolean | null;
  firstCollisionAfterLaunch: boolean | null;
  hasBeenAwakened: boolean | null;
  isOverrideProp: boolean | null;
  lastBurn: number | null;
  nextCheckDisableMotionContactsTime: number | null;
  initialGlowState: number | null;
  glowRange: number | null;
  glowRangeMin: number | null;
  glowColor: number | null;
  shouldAutoConvertBackFromDebris: boolean | null;
  muteImpactEffects: boolean | null;
  updateNavWhenMoving: boolean | null;
  forceNavObstacleCut: boolean | null;
  allowObstacleConvexHullMerging: boolean | null;
  acceptDamageFromHeldObjects: boolean | null;
  enableUseOutput: boolean | null;
  removableForAmmoBalancing: boolean | null;
  awake: boolean | null;
  attachedToReferenceFrame: boolean | null;
  readonly motionEnabled: CEntityIOOutput;
  readonly onAwakened: CEntityIOOutput;
  readonly onAwake: CEntityIOOutput;
  readonly onAsleep: CEntityIOOutput;
  readonly onPlayerUse: CEntityIOOutput;
  readonly onOutOfWorld: CEntityIOOutput;
  readonly onPlayerPickup: CEntityIOOutput;
}

export interface CCSPlayerPawn extends CCSPlayerPawnBase {
  characterDefIndex: number | null;
  hasFemaleVoice: boolean | null;
  readonly lastPlaceName: string | null;
  inHostageResetZone: boolean | null;
  inBuyZone: boolean | null;
  wasInBuyZone: boolean | null;
  inHostageRescueZone: boolean | null;
  inBombZone: boolean | null;
  wasInHostageRescueZone: boolean | null;
  retakesOffering: number | null;
  retakesOfferingCard: number | null;
  retakesHasDefuseKit: boolean | null;
  retakesMVPLastRound: boolean | null;
  retakesMVPBoostItem: number | null;
  healthShotBoostExpirationTime: number | null;
  landingTimeSeconds: number | null;
  isBuyMenuOpen: boolean | null;
  lastLandTime: number | null;
  onGroundLastTick: boolean | null;
  playerLocked: number | null;
  timeOfLastInjury: number | null;
  nextSprayDecalTime: number | null;
  nextSprayDecalTimeExpedited: boolean | null;
  ragdollDamageBone: number | null;
  readonly ragdollDamageForce: Vector | null;
  readonly ragdollDamagePosition: Vector | null;
  readonly ragdollDamageWeaponName: string | null;
  ragdollDamageHeadshot: boolean | null;
  readonly ragdollServerOrigin: Vector | null;
  econGlovesChanged: number | null;
  readonly deathEyeAngles: QAngle | null;
  leftHanded: boolean | null;
  switchedHandednessTime: number | null;
  viewmodelOffsetX: number | null;
  viewmodelOffsetY: number | null;
  viewmodelOffsetZ: number | null;
  viewmodelFOV: number | null;
  isWalking: boolean | null;
  lastGivenDefuserTime: number | null;
  lastGivenBombTime: number | null;
  dealtDamageToEnemyMostRecentTimestamp: number | null;
  displayHistoryBits: number | null;
  lastAttackedTeammate: number | null;
  allowAutoFollowTime: number | null;
  resetArmorNextSpawn: boolean | null;
  spotRules: number | null;
  isScoped: boolean | null;
  resumeZoom: boolean | null;
  isDefusing: boolean | null;
  isGrabbingHostage: boolean | null;
  emitSoundTime: number | null;
  inNoDefuseArea: boolean | null;
  whichBombZone: number | null;
  inBombZoneTrigger: boolean | null;
  wasInBombZoneTrigger: boolean | null;
  shotsFired: number | null;
  flinchStack: number | null;
  velocityModifier: number | null;
  readonly totalBulletForce: Vector | null;
  waitForNoAttack: boolean | null;
  ignoreLadderJumpTime: number | null;
  killedByHeadshot: boolean | null;
  lastHitBox: number | null;
  botAllowActive: boolean | null;
  lastPickupPriority: number | null;
  lastPickupPriorityTime: number | null;
  armorValue: number | null;
  currentEquipmentValue: number | null;
  roundStartEquipmentValue: number | null;
  freezetimeEndEquipmentValue: number | null;
  lastWeaponFireUsercmd: number | null;
  isSpawning: boolean | null;
  deathFlags: number | null;
  hasDeathInfo: boolean | null;
  deathInfoTime: number | null;
  readonly deathInfoOrigin: Vector | null;
  gunGameImmunityColor: number | null;
  grenadeParameterStashTime: number | null;
  grenadeParametersStashed: boolean | null;
  readonly stashedShootAngles: QAngle | null;
  readonly stashedGrenadeThrowPosition: Vector | null;
  readonly stashedVelocity: Vector | null;
  committingSuicideOnTeamChange: boolean | null;
  wasNotKilledNaturally: boolean | null;
  immuneToGunGameDamageTime: number | null;
  gunGameImmunity: boolean | null;
  molotovDamageTime: number | null;
  readonly eyeAngles: QAngle | null;
  readonly econGloves: CEconItemView;
  readonly entitySpottedState: EntitySpottedState_t;
}

/** Every wrappable entity class, by schema name. */
export interface SchemaClasses {
  CEntityInstance: CEntityInstance;
  CGameRules: CGameRules;
  CBaseEntity: CBaseEntity;
  CMultiplayRules: CMultiplayRules;
  CBaseModelEntity: CBaseModelEntity;
  CBasePlayerController: CBasePlayerController;
  CTeam: CTeam;
  CTeamplayRules: CTeamplayRules;
  CBaseAnimGraph: CBaseAnimGraph;
  CBaseToggle: CBaseToggle;
  CBeam: CBeam;
  CCSGameRules: CCSGameRules;
  CCSPlayerController: CCSPlayerController;
  CCSTeam: CCSTeam;
  CModelPointEntity: CModelPointEntity;
  CBaseButton: CBaseButton;
  CBaseCombatCharacter: CBaseCombatCharacter;
  CBaseDoor: CBaseDoor;
  CBaseGrenade: CBaseGrenade;
  CBaseProp: CBaseProp;
  CBaseTrigger: CBaseTrigger;
  CEconEntity: CEconEntity;
  CPlantedC4: CPlantedC4;
  CPointWorldText: CPointWorldText;
  CRagdollProp: CRagdollProp;
  CBaseCSGrenadeProjectile: CBaseCSGrenadeProjectile;
  CBasePlayerPawn: CBasePlayerPawn;
  CBasePlayerWeapon: CBasePlayerWeapon;
  CBreakableProp: CBreakableProp;
  CCSPlayerPawnBase: CCSPlayerPawnBase;
  CCSWeaponBase: CCSWeaponBase;
  CDynamicProp: CDynamicProp;
  CPhysicsProp: CPhysicsProp;
  CCSPlayerPawn: CCSPlayerPawn;
}

/**
 * Apply this schema class's field accessors to an entity reference.
 *
 * `createEntity` returns a bare `EntityRef` with no schema fields on it — this is how you get
 * them. `Player.pawn` is already wrapped; this is for entities you create or resolve yourself.
 *
 * The wrapper is a view, not a copy: it holds the ref and reads through it on every access, so
 * it stays correct as the entity changes and costs nothing to keep. Field reads return null
 * once the ref goes stale, exactly as they do on a pawn.
 *
 * @example
 * const prop = createEntity("prop_dynamic");
 * prop.spawn();
 * const fields = wrapEntity("CBaseModelEntity", prop);
 * fields.glow.glowing = true;
 */
export declare function wrapEntity<K extends keyof SchemaClasses>(className: K, ref: EntityRef): SchemaClasses[K];
